### ISSUE TITLE
Custom keyboard shortcut to pause and resume

### ISSUE THREAD

**Issue by byungjikroh** [xmichelo/Beeftext#100]
I pause and resume Beeftext a lot while I'm working with automatic combo triggering.

So it would be great if there is a feature to add a custom shortcut like Ctrl+F1 to pause and resume Beeftext easily without moving and clicking by a mouse.

In addition, there could be a short feedback or tooltip to notify it is paused or resumed. 

Please consider it and you can close this if you don't like it.
Thanks. :)

**Comment by xmichelo** [comment]
Hi.

Good point. I will add a global shortcut, with a possibility to configure the keystroke. It's not going to be Ctrl+F1 by default because many application use it.

There is already some feedback in place for the pause state of the application. When the application is paused the icon in the notification area (a.k.a. system tray) is grey instead of red. Of course you need to have Beeftext displayed in the notification area. Beeftext will not display pop-up/toast notifications.

**Comment by byungjikroh** [comment]
Thanks for the feedback. :) 

Yes, I know Beeftext becomes grey when it is paused. But I have to place it visible on the area and will have to check again when it has a global shortcut after updating. 

Logitech Options provides an indicator on the middle of screen as an overlay, it could be annoying to someone but useful to me. It helps me not to check if Caps Lock key is on or off by eyes. (https://support.logitech.com/en_us/article/39610)

If Beeftext provides an indicator as an opt-in option like Logitech Options, it will increase user's productivity much more. I have no problem even if you don't want it. :)

I'm looking forward to the next update!

**Comment by xmichelo** [comment]
A custom made overlay could be an option that the user can turn off could be a solution.

My problem with tray notifications (a.k.a. toast notifications) is that they are a pain in the to manager in Windows 10, as they stay in the action center, and tend to repeat themselves when you reach the maximum count.

**Comment by byungjikroh** [comment]
Yes, I agree that toast notifications remaining at the action center are annoying and needed to be clear manually. 

I meant small balloon tip notification on the icon in the system tray like this https://www.dreamincode.net/forums/uploads/post-235728-1248302592.jpg. But now I checked it works as an toast notification on Windows 10. Sorry about making you confused.

I think an option for an overlay indicator would be great. :)

**Comment by ryhaph** [comment]
*INSERT ENCOURAGEMENT HERE*
You can do it! (please) :)

**Comment by xmichelo** [comment]
This been delayed too many times. The feature list for v6.0 is locked, but it will be implemented for v7.0.

**Comment by yuru7** [comment]
By default in v6.0, pause/resume global shortcut is `ctrl-alt-shift-V`. This conflicts with other applications in my PC. Will this be resolved in v7.0?

Thank you for your hard work. :)

**Comment by xmichelo** [comment]
Yes that's the plan.

**Comment by xmichelo** [comment]
The feature is implemented. Here are test builds:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngfFZyqcZG4sppjmKbA?e=5SjhMn)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngfFaNGqVOs6yTkWJpQ?e=f6XhmD)

The shortcut is disabled by default. You can enable it and change the shortcut in the `Behavior` tab of the preferences.

**Comment by yuru7** [comment]
@xmichelo It's great work! thanks :)
