### ISSUE TITLE
Question: how to include key combinations in the keyword section

### ISSUE THREAD

**Issue by low-decarie** [xmichelo/Beeftext#102]
Not a bug report or feature request.

Thanks for such a great open source tool!

How does one include key combinations in the keyword section?

For example alt-5 to trigger a specific snippet?

Thank you

**Comment by xmichelo** [comment]
Hi @low-decarie 

This is not supported yet. It is an often requested feature so it might appear in a future release. But I cannot commit to any ETA.

**Comment by xmichelo** [comment]
Did some test. The way the application work it is not going to work reliably. Closing.
