### ISSUE TITLE
Clipboard cache feature request

### ISSUE THREAD

**Issue by e-stonia** [xmichelo/Beeftext#108]
Hey, love this one as moved from PhraseExpress that is buggy and charges money. Would pay if no bugs though. Anywy, it had cool feature - pressing alt+ENTER opened my last items in clipboad in menu and with arrow down and enter I quickly got the item pasted.

**Comment by xmichelo** [comment]
Hi @e-stonia,

Thank you for your support. At the moment Beeftext will remain a tool focused on managing text snippet, so there will be no such thing as advanced clipboard management in the foreseeable future.

I guess you can find many clipboard managers out there. A quick google search led me to [ArsClip](http://www.joejoesoft.com/vcms/97/), which I have not tested, but seem to be doing what you are looking for.
