### ISSUE TITLE
Improve date variable to support dates/times other than the current ones.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#111]
Currently, the dateTime variable can only insert the current date/Time. Allow shift to support variables for dates like yesterday and tomorrow, or times +/- x hours.

**Comment by g33k247** [comment]
Would love to see support for date/time variables like in BASH.

**Comment by Corey-Keller** [comment]
@xmichelo Additionally, it would be nice to be able to output the time in UTC.

**Comment by NDscham** [comment]
In Beeftext 6.0+, I have had success in creating a custom date/time variable like this:

**Current date +2 days:** `#{dateTime:+2d:dddd.MM.yyyy}`
**Current time +2 hours and 15 minutes: ** `#{dateTime:+2h+15m:hh:mm}`

Feel free to adapt this. What is missing is to have a certain weekday, i.e. next monday.

**Comment by xmichelo** [comment]
Hi @NDscham.

Indeed, targeting a day of the week is not possible at the moment.

**Comment by ZuntyhK** [comment]
Hello everybody
Sorry for my bad english, i'm french user
I want to use it, but it's possible to combine with #{input:}  ?
Exemple : 
I want to tell 
Your RDN has planified for #{dateTime:+Xd:dd/MM}
X = Variable to defined 

It's possible to defined X with #{input:} ?

Thx

**Comment by xmichelo** [comment]
Hi.

No, it is not possible
