### ISSUE TITLE
The keyword does not support Chinese.

### ISSUE THREAD

**Issue by Jarvanh** [xmichelo/Beeftext#113]
### Expected behavior
Enter Chinese keywords and replace them with snippet.
### Actual behavior
Input Chinese keyword is not replaced with snippet.
### Steps to reproduce the behavior
Use Chinese keywords.
### Operating system
Windows 10 64 bit.

**Comment by xmichelo** [comment]
Hi. 

I know very little about the way Chinese people type text, but having seen a Chinese friend type using a companion app that transforms roman characters into chinese symbols, it is unfortunately incompatible with the way Beeftext works.
