### ISSUE TITLE
Add cursor position in snippet

### ISSUE THREAD

**Issue by Li-An** [xmichelo/Beeftext#114]
Hello, I would like to have the ability to define cursor position in snippet. And thanks for Beeftext, it’s a very cool application (and I tested all the alternatives).

**Comment by xmichelo** [comment]
Hi @Li-An.

It is possible to do that using the variable `#{cursor}`. You can find more information about variables in the [dedicated wiki page](https://github.com/xmichelo/Beeftext/wiki/Variables)

**Comment by Li-An** [comment]
Thanks, I completely missed this.
