### ISSUE TITLE
Import from TextExpander for Mac?

### ISSUE THREAD

**Issue by DustinWehr** [xmichelo/Beeftext#116]
I don't see an option to import a `.textexpander` XML exported snippets file. Is there a tool somewhere for converting the file to Beeftext's JSON format? Mine is very long!

**Comment by DustinWehr** [comment]
If it hasn't been done yet, I don't mind writing a python script that can do it.

**Comment by xmichelo** [comment]
Hi @DustinWehr 

TextExpander being a major player in the market, Supporting import and export/from to its XML format will be a nice feature. PhraseExpress could also be supported.

This could be one of the next  'new features' of Beeftext. The Qt framework makes it very straightforward to parse XML, so It shouldn't be a big issue. 

Timing is more of a problem. I'm pretty busy right now with my day job, and I promised some features I need to implement first. If you are willing to import your TextExpander snippets ASAP, the best way for you is indeed to write a script that convert exported TextExpander snippets to Beeftext JSON combo lists, and import them into Beeftext. The JSON format is pretty simple and should be easy to understand. Just create some dummy combos and export them to a JSON file. Just ask if you need help.

In the end, there will be support for Import/Export from others majors text snippets tools.

**Comment by DustinWehr** [comment]
@xmichelo I have an in-browser solution with instructions that you could just launch from Beeftext:
https://repl.it/@DustinWehr/textExpanderToBeeftextpy

**Comment by xmichelo** [comment]
Hi @DustinWehr.

Thank you for the script. I quickly tested it from my mac and it worked just fine.  I will tweet about it. Do you have a twitter account, so I can credit you?

Unfortunately the copy/paste method seems to work only on Mac. The export fonction to a .textexpander file is also not available on Windows, probably because it uses [Apple's XML property list format](https://en.wikipedia.org/wiki/Property_list#macOS), and Smile did not take the time to write Windows I/O functions for this format.

The only universal way to export TextExpander snippet is apparently to use the export feature that is available from your TextExpander account page. It uses a very simple CSV file format and you can only export one group at a time.

I will try to implement support for this CSV file format in the coming weeks.

**Comment by DustinWehr** [comment]
Sure! I'm @duswehr

**Comment by xmichelo** [comment]
Implemented. See issue #104 for details.

**Comment by mathieucaroff** [comment]
Below is the Python script I used to read the TextExpander XML file that Breevy exported and convert it to the CSV format expected by BeefText.

I'm interested in writing a simple web-based program which parses TextExpander's XML and outputs BeefText's JSON. -- Preserving groups is important for me as I have 34 of them.

---

```py
# This script requires python 3.7+
# (maybe even 3.8+)

import csv
from dataclasses import dataclass
import xml.etree.ElementTree as ET

OUTPUT_FILE_PATH = r'Expansion-CSV.csv'
INPUT_FILE_PATH = r'Settings.textexpander'

tree = ET.parse(INPUT_FILE_PATH)
root = tree.getroot()
rootdict = root[0]

snippetOutputArray = []


@dataclass
class Snippet:
    abbreviation: str
    expansion: str
    label: str

    def row(self):
        return [self.abbreviation, self.expansion, self.label]


for snippetEntry in rootdict[15]:
    assert snippetEntry[0].text == 'label', snippetEntry[0].text
    label=snippetEntry[1].text

    assert snippetEntry[2].text == 'abbreviation', snippetEntry[2].text
    abbreviation=snippetEntry[3].text

    assert snippetEntry[4].text == 'plainText', snippetEntry[4].text
    expansion=snippetEntry[5].text

    snippetOutput = Snippet(
        label=label,
        abbreviation=abbreviation,
        expansion=expansion,
    )

    snippetOutputArray.append(snippetOutput)


with open(OUTPUT_FILE_PATH, 'w', encoding='utf-8') as handle:
    writer = csv.writer(handle)
    for snippetOutput in snippetOutputArray:
        writer.writerow(snippetOutput.row())
```
