### ISSUE TITLE
Keyword collisions

### ISSUE THREAD

**Issue by lixuss** [xmichelo/Beeftext#117]
It would be so nice if keywords were not so hungry...explain:

### Actual behavior
I cannot define keyword "sp" and "spades" together.

### Expected behavior
"sp" and "spades" will exists both
_spades_ is longer, so it has priority. I write _sp_, okay go on, continue _spades_. Well then hit shortcut to expand it.

**Comment by xmichelo** [comment]
Hi @lixuss.

You're right, Beeftext should let you do that. The error message is a non-sense if you are using Beeftext in 'manual combo triggering' mode.
