### ISSUE TITLE
Feature request: More variables/special keys

### ISSUE THREAD

**Issue by okoetter** [xmichelo/Beeftext#124]
I'd like to habe more variables added that can send special keys like e.g. #{TAB}, #{ENTER}, #{LEFT}, {#RIGHT}, #{BACKSPACE}. This way you can automate filling forms.

**Comment by xmichelo** [comment]
Hi. 
Unfortunately, special keys are incompatible with the way Beeftext operates. At best the work intermittently. Until there is a rewrite of the core application. This will not be possible.
