### ISSUE TITLE
Add a way pick combos from a menu.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#127]
Combo collections can be quite big, and one can easily forget combo keyword. A good way to help the user would be to have a global shortcut that would pop a menu where the user can navigate groups and combos.

**Comment by alienfxfiend** [comment]
This would be very important, yes. I would've made a similar entry if this weren't there, it's a must-have for those with lots of similar related text replacements --a popup is a crucial addition !

**Comment by xmichelo** [comment]
The feature as been implemented, but not as a menu, see issue #166 for details and test build.
