### ISSUE TITLE
Trying to launch Beeftext while already running should not give an error message.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#128]
Currently, trying to launch a second instance of Beeftext will result in an error message. It is confusing some users. It would be better to open the main window of the existing instance silently.

**Comment by Celinch** [comment]
Hi,
I totally agree with that.
I am unable to use correctly the portable version of beeftext because I have no icon in the system tray and can't open the main window of the application. Beeftext is working but I can't change or create any combo.
Thanks for this application.

**Comment by xmichelo** [comment]
Hi @Celinch 

Not having the icon in the system tray is not normal. Are you sure it is not in the overflow area?

![overflowareademo](https://user-images.githubusercontent.com/1926756/53878840-35084e00-400d-11e9-8cc2-13712e9acf6e.gif)

**Comment by Celinch** [comment]
It's not in the overflow area. My guess was that there are restrictions on the icons of the system tray on this computer.

**Comment by xmichelo** [comment]
Oh I see. That's indeed the likely cause. I'm increasing this issue's status to high priority, because it simply make the software unusable in restricted environments. 

I will post test builds once I have something ready.

**Comment by xmichelo** [comment]
Hi @Celinch 

I have implemented the change. Here are some test build if you wan to try:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSnvAb1v7TBS90xTh1R)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSnvAXOQuUfT7goB7Zg)

**Comment by Celinch** [comment]
I just tested the portable edition and it was usable now. Even if I have no icon, I can "call" the main window by  double-clicking again on the application file.

Thanks !

**Comment by xmichelo** [comment]
I'm pleased to hear that. The official release should happen this week.
