### ISSUE TITLE
In Outlook, some characters disappear if clipboard is not used for substitution.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#131]
When the user does not have the 'Use clipboard for combo substitution option' activated, some characters get lost during expansion.

**Comment by xmichelo** [comment]
It seems that the problem come from the fact that Beeftext is simulating keystrokes too fast.

I have made a test build that include a new preference in the advances section. **Delay between simulated keystrokes**, which defines a delay that is introduced between every simulated keystroke during combo substitution. 

Try increasing progressively the delay until the problem disappear. Of course the drawback of this is that the more you increase the delay, the slower the substitution will be.

Download links

- [Installer](https://1drv.ms/u/s!AjydspuvJDSnvAFJy-ciqp31qhOb)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSnvABRyk1mLYna0wfD)

**Comment by MO92119** [comment]
Even a high number (e.g. 444ms) does not change anything. The blank at the end is still missing...

**Comment by xmichelo** [comment]
@MO92119 

OK, so your problem is different. Is the *Use clipboard for combo substitution* option checked on your system?

**Comment by xmichelo** [comment]
@MO92119 I think I nailed the problem. 

I could actually reproduce the issue when Beeftext uses the clipboard for combo substitution. The problem is a feature of Outlook (and other office apps) called *Smart cut and paste*. If you manually copy your snippet (with the space at then end) in the clipboard, and paste manually in Outlook, you will see that the space also disappear.

It is actually Outlook that is removing the space. To disable this, in the latest version, go to `File ➜ Options ➜ Mail ➜ Editor Options ➜ Advanced` and uncheck *Use smart cut and paste*. 

The option also exists in Word.

Could you please confirm it solves the issue?

**Comment by xmichelo** [comment]
With the *Delay between simulated keystrokes* option coming to v1.9, this issue seems fixed. Feel free to re-open if the issue persists.
