### ISSUE TITLE
Old combos still linger (in memory?)

### ISSUE THREAD

**Issue by SevenD7D** [xmichelo/Beeftext#137]
When doing some testing for my initial bug reporting, things got stranger and more confusing. I hope this confusing is not showing too much in this report.

This bug report seems to only affect my original 4 combos that I have set-up. They use triggers of this type: "..sig". I use the copy and paste method.
I expect that the Combo expands to the Snippet. The snippets are either an English sentence or a paragraph.

Initially, I noticed that the combo seemed to get substituted twice, with the length of the keyword being cut from the first substitution. (i.e. "This is the snippThis is the snippet.")

Then for testing I have created a new Combo called "Test".
Group: Default Group
Matching strict
Keyword: ..test
Snippet: This is a test.

Writing: 12345678 ..test
Expecting: 12345678 This is a test.
Actual output: 12345678 This is a test.

As you can see, that one does not show the double substitution problem (although it also sometimes replaces the keyword with nothing at all).

Here are the steps I have taken so far:

1. Exit Beeftext

2. Edited comboList.json (for the first time - the bug existed before I touched the file) in Notepad++, changing just the snippet text to remove personal information.

3. Started Beeftext

4. Used the keyword "..sig"
EXPECTED: \<My new signature\>
ACTUAL: \<My new signature\>\<My old signature\>

The comboList.json file does not contain My old signature anymore. Where is the text coming from?

### Operating system
Beeftext 1.8
Windows 10

**Comment by xmichelo** [comment]
Hi @SevenD7D.

A Quick test: Exit beeftext, and type ..sig

My idea is that you may have another text expansion program still installed and running without your knowledge? (Text Expander, Phrase Express...).

Because that's the only reason I see the old signature still popping up after being removed from the comboList.json file.

**Comment by SevenD7D** [comment]
Hello,
You are absolutely right. DOH! After a restart Texter started up again.
And I just finished installing Visual Studio to go bug hunting.

**Comment by SevenD7D** [comment]
Thank you so much for this excellent program!

**Comment by xmichelo** [comment]
Thank you, @SevenD7D 

Don't worry, you're not the first experiencing this issue ;)
