### ISSUE TITLE
Backspace to undo _OR_ Manual Confirmation

### ISSUE THREAD

**Issue by alienfxfiend** [xmichelo/Beeftext#138]
### Expected behavior
Backspacing a triggered word undo's the replacement (& can be re-triggered by space again.) This makes up for the lack of manual replacement & is present in Pidgin Text Replacement plug-in & makes up for unwanted triggers & makes it more manageable. _OR_ manual confirmation with Tab key to auto-complete [with a popup.] The former is easier to implement. I use this for chatting purposes, for example, I convert "hi" to "Hiya !" so I have to be careful...
### Actual behavior
Triggers words instantly & executes unwanted phrases —by requesting user input from popups or tab or undo[backspace], would work with fewer misfires.
### Operating system
Windows 10

**Comment by xmichelo** [comment]
Ctrl+Z works.

Also I suggest you pick keywords that are unlikely to be triggered by mistake. Personnally I prefix everything with `xx`. For instance my email address is mapped to the `xxem` keyword.
