### ISSUE TITLE
Message box for Input variable opens on wrong monitor

### ISSUE THREAD

**Issue by blauebank** [xmichelo/Beeftext#141]
### Expected behavior
In a setup with two monitors:
When typing a shortcut for text with an input variable, the message box for that input variable should open above the window in which I typed the shortcut.

### Actual behavior
The message box opens on the monitor, in which the Beeftext window itself is displayed, not on the monitor in which the txt was typed. I have to search for that message box.

### Steps to reproduce the behavior
Start Beeftext on a system with two monitors. Display Beeftext on one monitor, a text editor on the other monitor. Type a combo that will show a message box.

### Operating system
Windows 10

BTW: The new input variable is great. Thank you for adding it.

**Comment by xmichelo** [comment]
Hi @blauebank 
This is strange, because I get a different behaviour. I have a three monitor setup, and the input dialog does not pop on the monitor where Beeftext is, but on the monitor where the mouse cursor is located.

- What happens if the Beeftext window is closed?
- Do you use any extra window or monitor management tool, like DisplayFusion?

**Comment by blauebank** [comment]
I tried again this morning. It seems like the 
first input dialog after I start Beeftext will 
always pop up on my main monitor. The input dialogs afterwards are correct.

Here is a short screen capture:
https://www.screencast.com/t/3XYvApaaoHIX

- First I type the shortcut in the text editor on 
the right monitor. The Beeftext pop up  appears on the left monitor.
- Then I click randomly for  5 second, please ignore.
- Then I type again in the text editor on the 
right monitor. This time the Beeftext pop  up  appears on the right monitor.
If I close Beeftext and restart it, I can repeat this behavior.

I don't use any extra window management tool.





At 21:14 26.03.2019 -0700, you wrote:

**Comment by xmichelo** [comment]
Hi.

From what I see in your screencast, the dialog pops-up on the monitor where the mouse pointer is located, which is the expected behavior.

**Comment by blauebank** [comment]
So the dialog does not care about the cursor, but pops up on the window of the mouse pointer? 

Ahh...
I didn't get that the dialog followed the mouse pointer. I was expecting it the pop up on the window of the cursor.
