### ISSUE TITLE
Input does not allow content copy in another application

### ISSUE THREAD

**Issue by Li-An** [xmichelo/Beeftext#142]
### Expected behavior
Possibility to copy external text and paste in input field when input windows is opened. I created different input fields and I need to copy the different content from external  #source
### Actual behavior
The input window closes automatically when selecting another application/window
### Steps to reproduce the behavior
Try to copy some text in another application when Input window is waiting for content
### Operating system
Windows 10 64 bits

**Comment by xmichelo** [comment]
Hi. 
This is a limitation of Beeftext. The input dialog disappear on purpose when it loses the focus, because if you switch to another application, Beeftext has no more knowledge of the initial window where you typed you combo.

**Comment by Li-An** [comment]
I supposed there was a problem like this. I meet some problems with clipboard content update.
