### ISSUE TITLE
Activating Beeftext could be easier

### ISSUE THREAD

**Issue by HenrikRClausen** [xmichelo/Beeftext#147]
### Expected behavior
If Beeftext is running in the background and you try to launch it again, it should show the configuration window. The new instance could quite easily request the running instance to maximize.

### Actual behavior
When Beeftext is already running, and you launch it again, you just get a message "Another instance of Beeftext is already running". An option to maximize that instance is not given.

### Steps to reproduce the behavior
Run Beeftext, and minimize/hide it.
Run Beeftext again. You get the message, but not access to the program.

### Operating system
Windows 10

### Background
At Komputer for alle, Scandinavias largest computer magazine, we have several readers reporting their inconvenience over this behaviour.

**Comment by xmichelo** [comment]
Hi @HenrikRClausen 

This has already been changed (it was requested in #128), and it is included in [Beeftext v1.9](https://github.com/xmichelo/Beeftext/releases/tag/v1.9) that was released earlier this week.

If you still have the problem with v1.9, please re-open the issue.

**Comment by HenrikRClausen** [comment]
Thanks, excellent. We will upgrade to the latest version and have happy
readers.

Best regards
Henrik Ræder Clausen
Komputer for alle

A programmer is ideally an essayist who works with traditional aesthetic
and literary forms, as well as with mathematical concepts, to communicate
the way that an algorithm works.”
― Donald E. Knuth, Computer Science God

fre. 29. mar. 2019 06.39 skrev Xavier Michelon <notifications@github.com>:
