### ISSUE TITLE
Ability to convert text to be inserted to lowercase/uppercase

### ISSUE THREAD

**Issue by frusnuf** [xmichelo/Beeftext#150]
I would like to have the possibility to instruct BeefText to convert to uppercase or lowercase before inserting. My guess would be to add a new "variable", syntax would resemble #{tolower:combo:xxc}. But any other solution would suit me of course...

To be very specific, I would like to be able to insert dates in format "8apr2019", all lowercase (because it's the way I like the date to appear in my meeting minutes :-) )

**Comment by xmichelo** [comment]
Hi @frusnuf 
Interesting suggestion. I will implement that.

**Comment by frusnuf** [comment]
Thanks Xavier for considering my point.
Sincerely, François-Xavier

Le mer. 10 avr. 2019 à 05:25, Xavier Michelon <notifications@github.com> a
écrit :

**Comment by frusnuf** [comment]
Merci Xavier, quelle rapidité...

Le ven. 12 avr. 2019 à 07:30, Xavier Michelon <notifications@github.com> a
écrit :

**Comment by emanaydin** [comment]
Any update on this feature? I'd really love this.
