### ISSUE TITLE
Feature request: Attach multiple snippets by trigger

### ISSUE THREAD

**Issue by DweEroz** [xmichelo/Beeftext#154]
Hello,
How about adding a fonction in order to attach multiple snippets to one trigger?
It could be useful in cases where we must regularly answer the same sentence but with different turns :)

Thank you!

**Comment by xmichelo** [comment]
I really like this idea. Thank you for the suggestion. I'll work on that for the next release.

**Comment by xmichelo** [comment]
Hi @DweEroz 

The feature is implemented and will be in the next release. If you want to help testing, please use the following test builds.

- [Installer](https://1drv.ms/u/s!AjydspuvJDSnvRulTXgKVyMeNHVd)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSnvRz19L6-4q4MeAsR)
