### ISSUE TITLE
Beeftext stops working on local host when connected via VNC

### ISSUE THREAD

**Issue by OARS-Inc** [xmichelo/Beeftext#156]
Beeftext will not paste a snippet to the local host if connected to a remote host via VNC (we use TightVNC).  Once the VNC connection is terminated, it works correctly on the local host again.  This may be related to issue #94.

Steps:
1. Verify Beeftext is working by using a keyword to paste a snippet on the local host - notice that it works correctly.
2. Connect to a remote host using VNC.
3. Reattempt using a keyword to paste a snippet on the local host - notice that the sound is played, but nothing is pasted.
4. Use a keyword to paste a snippet on the remote host - notice that it works correctly.
5. Disconnect from the remote host.
6. Reattempt using a keyword to paste a snippet on the local host - notice that it works correctly.

Operating system is Windows 7

**Comment by xmichelo** [comment]
Hi @OARS-Inc 

I tried to reproduce on both my Windows 10 dev machine and a Windows 7 VM. I could reproduce the problem in Windows 7, but it works fine on Windows 10.

Apparently TightVNC is messing with the clipboard, and Beeftext, by default, uses the clipboard for combo substitution.

Unfortunately, I have no time to investigate this issue further. Here are the two workarounds I have to offer:

- Disable clipboard transfer in the TightVNC settings.
- Disable use of the clipboard by Beeftext by unchecking '*Use clipboard for combo substitution*' in the '*Advanced*' section of the preferences. This will make substitution slower and less safe, but at least it should work fine with TightVNC.
