### ISSUE TITLE
Feature request: combo sharing

### ISSUE THREAD

**Issue by DickerPeter** [xmichelo/Beeftext#157]
Good day,

I find your program interesting.
But what is missing is a function for a synchronization to a central database.
So that several people who do not work in a network together can use the same text modules.
is something planned to install?

**Comment by xmichelo** [comment]
Hi @DickerPeter.

Thank you for you suggestion. Sharing with a team is definitely not coming to Beeftext anytime soon. Doing it properly requires a server, and an authentication mechanism that represent too much development. If that's really what you need, I invite you to check commercial solutions like TextExpander or PhraseExpress.

However I am planning something (in a not so distant future, but without any ETA), that might interest you:
- Beeftext will let you export a file with your combos and groups, that you would put online (via the web, or a network share).
- Other people (or yourself, on a different computer) will 'subscribe' to this file, and will get 'read-only' access to the combos you published. 

Actually, subscribing would be one of two options. If you subscribe, you will automatically get updates when the list is changed, but you will not be able to modify the combos. The other option will be to import the list of combos. With that option, they will be modifiable, but you will not get updates.

**Comment by VijayS1** [comment]
It seems like the portable option takes care of this issue for the basic use case.

**Comment by SuperCC25** [comment]
Hey everyone, great app. I too would love to be able to drop my database file in something like Dropbox or Google Drive. Is it doable? VijayS1, you're talking about using the portable version to achieve this?

Any help would be appreciated. Thinking of switching over to this app from PhraseExpress, but would love to have all of my combos synced somewhere.

**Comment by xmichelo** [comment]
You can relocate your combo list to a shared drive, on the network, or on the cloud. Beware however:
In its current form, Beeftext does not detect that the combo file has been modified by an external app (another instance of Beeftext on an other computer). One solution is to always ensure only one instance of Beeftext is running at any time. Of course that easier said than done.

My approach to sharing at the moment: I use a git repository on github. Of course I have to sync manually using git push and pull, but it's the safest method for now.

I have ideas for a server-less sync mechanism, but that's quite a lot of development and testing, and unfortunately, I'm quite busy with my day job at the moment.

**Comment by SuperCC25** [comment]
Amazing! What file should I be relocating to my dropbox folder on my PC? And would it be better to use the portable version to achieve this?

**Comment by xmichelo** [comment]
Although it is possible to use the installer based version, it can be tricky and can lead to losing all you combos if you do not do it properly.

That's why I recommend you to use the Portable Edition.
1. Unzip the portable edition on a shared / cloud folder.
2. Installer/Portable Edition do no share the same combo list file, so you will need to import your combo in the Portable Edition. In the installer version, export a backup of your combo list (`Advanced ➜ Backup`). It's a good idea to save this copy in a safe place.
3. Shut down the install version.
4. Launch the Portable Edition from your shared/cloud folder.
5. Import your combo from the backup file (`Advanced ➜ Restore`).

**Comment by SuperCC25** [comment]
Amazing service! Wow! I did all that, worked perfectly. After importing the file into the portable app, where does the database now reside? Is it in the portable folder somewhere? Is my backup json file still needed?

**Comment by SuperCC25** [comment]
Hey xmichelo,

Just wanted to tell you that everything is running smoothly now thanks to your help. Have officially switched over from PhraseExpress, thanks to your help.

Cheers! Thanks again!

**Comment by xmichelo** [comment]
Hi.

I'm happy to hear it works fine for you.
