### ISSUE TITLE
Feature request: paste clipboard without formatting

### ISSUE THREAD

**Issue by SanderGit** [xmichelo/Beeftext#159]
It would be nice if a shortcut could be chosen for 'paste clipboard without formatting'.
The app 'Fingertips' has this feature as well.

The native Ctrl-Shift-V shortcut does not always work in browsers or other apps, see e.g. https://github.com/ckeditor/ckeditor-dev/issues/469

**Comment by xmichelo** [comment]
Hi @SanderGit 

Thank you for the suggestion. Unfortunately, this is a bit out of the scope of Beeftext, which is a text snippet management tool, and I already lack time to develop core features I would like to see integrated.

I have to reject the suggestion.
