### ISSUE TITLE
Does not complete the expansion

### ISSUE THREAD

**Issue by ganosborne** [xmichelo/Beeftext#160]
### Operating system
Windows 7 Pro.

**Comment by xmichelo** [comment]
Hi @ganosborne 

A couple of questions:

- Are you using any other application that may interfere with the clipboard? For instance clipboard enhancement tools like ClipboardFusion or ArsClip.
- Are you using any form of remote access (VNC/Citrix...).
- In the preferences dialog, in the `Advanced`  section, is the `Use clipboard for combo substitution` option checked ? If you change this option, does it work better?

**Comment by ganosborne** [comment]
Unfortunately I am not.  Although it is odd that I restarted  and BeefText started automatically. I was typing and I used a common acronym and it worked. It expanded with the sound and I assumed it had somehow rectified. I tried it again immediately afterwards and it stopped working.


Gan Osborne

Public Safety Assistant Director

2000 Riverchase Galleria

Suite 181B

Hoover, AL 35244

Office: 205-444-3117

Cellular: 205-305-2786

Email: GOsborne@andyfrain.com


________________________________

**Comment by ganosborne** [comment]
Alright, I found something strange, my acronyms  auto expand while using MS Outlook. while  BeefText is off.

ie: PSAD Gan Osborne, Public Safety Director Dexter Cunningham etcetera.

 When I turn BeefText on is when I have an issue.

While BeefText is on, in Google Chrome, MS Word I it wont work.  But in MS Teams it will.

**Comment by ganosborne** [comment]
Gan Osborne

Public Safety Assistant Director

2000 Riverchase Galleria

Suite 181B

Hoover, AL 35244

Office: 205-444-3117

Cellular: 205-305-2786

Email: GOsborne@andyfrain.com


________________________________
From: Gan Osborne
Sent: Monday, May 27, 2019 10:19 AM
To: xmichelo/Beeftext
Subject: RE: [xmichelo/Beeftext] Does not complete the expansion (#160)


Alright, I found something strange, my acronyms  auto expand while using MS Outlook. while  BeefText is off.

ie: PSAD Gan Osborne, Public Safety Director Dexter Cunningham etcetera.

 When I turn BeefText on is when I have an issue.

While BeefText is on, in Google Chrome, MS Word I it wont work.  But in MS Teams it will.

**Comment by xmichelo** [comment]
If beeftext is off and expansion occurs, it generally means another application is doing the replacement. Have you installed another similar piece of software (TextExpander or PhraseExpress, for instance) ?

**Comment by ganosborne** [comment]
No, I did have some auto correct options set up in Word at one point.


Gan Osborne

Public Safety Assistant Director

2000 Riverchase Galleria

Suite 181B

Hoover, AL 35244

Office: 205-444-3117

Cellular: 205-305-2786

Email: GOsborne@andyfrain.com

________________________________

**Comment by xmichelo** [comment]
`In the preferences dialog, in the Advanced section, is the Use clipboard for combo substitution option checked ? If you change this option, does it work better?`

Have you tried this, as I suggested in my first reply?

**Comment by ganosborne** [comment]
It worked. You're fantastic. It was checked, now it isn't. I don't know why it worked but it did.


Gan Osborne

Public Safety Assistant Director

2000 Riverchase Galleria

Suite 181B

Hoover, AL 35244

Office: 205-444-3117

Cellular: 205-305-2786

Email: GOsborne@andyfrain.com

________________________________
