### ISSUE TITLE
Setup should propose the currently installation folder upon upgrade

### ISSUE THREAD

**Issue by TerDale** [xmichelo/Beeftext#161]
### Expected behavior
While having Beeftext already installed, launching the setup for a new version, the proposed installation path should be the one the previous version is currently located.
Thanks in advance!

### Actual behavior
The installation path is the default one: `%ProgramFiles(x86)%\Beeftext`

### Steps to reproduce the behavior
Install Beeftext vM in a non-default folder, then update to vN.

### Operating system
Microsoft Windows [Version 6.1.7601]

**Comment by xmichelo** [comment]
Fair point. I'll give it a low priority though.
