### ISSUE TITLE
Feature Request: Inline search like the textexpander one

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [xmichelo/Beeftext#162]
First of all, thank you so much for this amazing app, I just migrated from textexpander to Beeftext and liked it a lot and will be happy to support it, however, I missed some features, I'll request these features that I missed one by one if I did not find someone else requested them before.

The first feature is the inline search, adding inline search feature will really make our lives easier.

**Comment by xmichelo** [comment]
Hi @MohammedAl-Mahdawi 

I'm working on a feature right now named **combo picker**. I think it is what you call inline search. by invoking a keyboard shortcut, you get a window where you can type and search for a combo. Here is a quick demo: 

![ComboPicker](https://user-images.githubusercontent.com/1926756/59007111-5bfd3880-8825-11e9-9881-9448449f74cd.gif)

It will be included in the next release.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @xmichelo 

Yes! it is exactly what I mean by inline search, great news, thank you so much!

**Comment by xmichelo** [comment]
Perfect. The feature has been implemented, and I have made test build for testing. See issue #166.

**Comment by dp1702** [comment]
Hi @xmichelo

Could you please implement the use of multiple keywords in the combo picker? In the image above, I'd like to use "sample japanese" to narrow down the search. It's a very useful feature when you have hundreds of snippets.

Thank you very much.

**Comment by mathieucaroff** [comment]
@dp1702

I do not understand what you mean / what you want. Are you talking about multiple physical keyboards or multiple keyboard layouts? How does it relate to narrowing down the snippet search?

Also, I believe this should exist as a separate issue, with a link to this one, using `#`: `#162`

**Comment by dp1702** [comment]
@xmichelo

Thanks for answering and sorry for not being clear.  I'm talking about searching with multiple words or strings. That's why I posted here. In the combo picker, in the image above, if you type "sample" it will return all entries with that word. Now just imagine if you have samples for 20 languages but you want to select the Japanese one. In that case, searching for "sample japanese" would be the fastest way to narrow the results and find what you want.

**Comment by xmichelo** [comment]
That's a good idea. I have create a issue #283 for that. You can subscribe to be informed of the progress.
