### ISSUE TITLE
Caps lock triggered unexpectedly

### ISSUE THREAD

**Issue by KNCRD** [xmichelo/Beeftext#164]
### Expected behavior
Respect the caps lock activation
### Actual behavior
Sometimes with snippets replacing upper case with lower case, caps lock is triggered for a while, this occurs especially with fast typing
Experienced on several computers
### Steps to reproduce the behavior
Example : Snippet "Tu" replacing "TU" triggers caps lock

### Operating system
Windows 10

**Comment by TerDale** [comment]
Confirmed on my side too. Though, in my case, neither the trigger nor the snippet include uppercase characters. 
Indeed, I faced it systematically with this trigger: "(ie." associated with that snippet "(i.e. " (note the trailing space), or with "ie." and "i.e. ".
When it happens, the keyboard is as if caps lock was enabled, while the corresponding LED is off, as if one of the <shift> key was stuck down. To get back to "normal" I need to hit <shift> keys a few times.

BTW, I'm quite sure that this started occurring with the latest version.
Pretty annoying bug...
Thanks in advance

**Comment by KNCRD** [comment]
Yes, excatly the same behavior on my side.
As I need to type fast it may have occured with other snippets but I never had the chance to identify them.

**Comment by xmichelo** [comment]
Hi @KNCRD and @TerDale 

I will investigate this issue. I did a quick test and could not reproduce this issue. Could both of you give me a few details:

- Does the problem occur in any application, or just in one (for instance MS Word)?
- In your preferences, is the `Use clipboard for combo substitution` option checked?
- What language/keyboard layout are you using?

If you can, a screenshot of your preferences would be helpful.

Thanks in advance.
Xavier

**Comment by TerDale** [comment]
Hi @xmichelo 

> * Does the problem occur in any application, or just in one (for instance MS Word)?

Several

> * In your preferences, is the `Use clipboard for combo substitution` option checked?

Yep

> * What language/keyboard layout are you using?

French (France)

> If you can, a screenshot of your preferences would be helpful.

![image](https://user-images.githubusercontent.com/1826224/59187146-04d4cc00-8b75-11e9-86bc-eea4adb7dbba.png)


HTH

Jean-Marc

**Comment by xmichelo** [comment]
OK. I managed to reproduce the issue.  The problem occurs when the last character of the keyword requires you to have the shift key pressed. If you happen to release the shift key at the moment the combo expansion occurs, the system, for some unexplained reason, does not generate an event for the release of the Shift key.

So from the system's perspective, the Shift key is still pressed. Hence the 'Caps Lock' like effect.

I'll work on a fix ASAP.

**Comment by xmichelo** [comment]
Hi @KNCRD and @TerDale.

Sorry for the long delay. I have made some changes to the code that - I hope - will fix your issue. Could you please test the following build and tell me if the problem is solved?

- [Installer](https://1drv.ms/u/s!AjydspuvJDSnwBBhSbnd7KJCJuhy?e=ue4jxh)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSnwA8o8b7lK-ZSTLNR)

**Comment by TerDale** [comment]
Hi @xmichelo,

Hey, no worries, we didn't give anything to use Beeftext, so it is understandable that you deal with issues as your other occupations allow! ;-) 
Thanks anyway for having investigating this annoying one!
Just installed the pointed build, and happy to state that it fixes the issue in my case, though I have to use it a bit longer to be definitive. 

There is a little glitch though, my snippets are declared to end with a space, but is never present after replacement of the keyword. For instance the keyword "eg." was set up to be replaced by the snippet "e.g. " while its is by "e.g." actually.  However, this is really a minor one, far less annoying than the actual issue, so I can live with it ;-)

Thanks for your efforts Xavier

**Comment by KNCRD** [comment]
Hey ! Thanks so much for the update, the issue seems to be fixed ;)

Thanks again !

**Comment by xmichelo** [comment]
Great to hear it fixed the problem. The issue is clearly identified, but tricky to work around. I'm now more or less ready to release v3.0.

@TerDale: isn't you problem linked to Office? See issue #115 (I see you were involved in this issue, but I ask anyway).  If it's not the case, I suggest you file a new issue for this `missing spaces at the end` problem.

**Comment by TerDale** [comment]
@xmichelo Nope, I'm using neither Office nor Outlook, as stated in #115. Concerning the ending space, not a big issue, forget it!
