### ISSUE TITLE
Implement a way to search combo easily.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#166]
Having a lot of combos makes it difficult to remembers all the keywords. A way to search for combos from any application should be implemented.

**Comment by xmichelo** [comment]
The new feature is called *Combo Picker*. By default the global shortcut to invoke the combo picker is `Win+Shift+Enter`.

![ComboPickerDemo](https://user-images.githubusercontent.com/1926756/59081837-8667f800-88f0-11e9-83e1-001c387c1978.gif)


Test builds are available:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSnvm8HXQjSEYkjVJbA?e=wxCubW)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSnvnB9CX2B0Tyao9Ix?e=wxfNXW)

WARNING: when using these builds the combo list file format will be updated to v5. There is not conversion back to the old format, in case you want to return to the official release. You can restore an automatic backup if you have the option enabled, but you may want to backup your combo list file manually, for safety.

**Comment by MohammedAl-Mahdawi** [comment]
Hi @xmichelo I tested it and it worked for me like a charm! Thank you
