### ISSUE TITLE
In a mult-screen environment, the menu is shown only on the main screen...

### ISSUE THREAD

**Issue by BobMilli** [xmichelo/Beeftext#170]
See the menu on the screen where the Beeftext window is

The menu opens but on the "principal" screen

Just move the Beeftext window on a another screen than the main one a pull a menu

Windows 10

**Comment by xmichelo** [comment]
Hi. 

Thanks for reporting. I could reproduce it. It's a bug in the Qt framework, probably too minor to fix.
