### ISSUE TITLE
Hotkeys support

### ISSUE THREAD

**Issue by wilhelmmedetz** [xmichelo/Beeftext#171]
Hi,

thanks for BeefText, works absolutely fine.

Maybe you could add support for hotkeys like Ctrl+Shift+Insert OR Ctrl+K.

A possible use would be to insert unformatted clipboard text with Ctrl+Shift+Insert.

**Comment by xmichelo** [comment]
Hi.

Thank you for your suggestion. For now, Beeftext will focus only on text snippet expansion. The reason is simple: I have limited resources, and the list of request for core features is already quite long.
