### ISSUE TITLE
Confirmation dialog

### ISSUE THREAD

**Issue by wilhelmmedetz** [xmichelo/Beeftext#172]
Hi,

would it be possible to display a confirmation dialog before inserting a snippet?
It could be confirmed by pressing TAB and afterwards insert the snippet.
If it is canceled by pressing ESC, the original keyword text should remain unaltered.

Thanks

Wilhelm

**Comment by xmichelo** [comment]
Hi. 

I will reject this suggestion, as I want to keep the options to a minimum. If you need to confirm before expanding a snippet, you can use activate `Manual` combo triggering using a shortcut in the preferences.
