### ISSUE TITLE
feature request: reserved parameter

### ISSUE THREAD

**Issue by tuchit** [xmichelo/Beeftext#178]
Can you add some parameter like
%c --- clipboard
%t --- current time
%d --- date
{enter} --- enter
# --- win key
^ --- CTRL key
! ---shift key
%| --- curse position
and so on...

**Comment by xmichelo** [comment]
Hi @tuchit 

Clipboard content, time, date, and final cursor position are already available via the *variable* system. Have a look at the [dedicated wiki page](https://github.com/xmichelo/Beeftext/wiki/Variables).

Regarding generation of keystrokes, it has already been requested (for tab) in issue #163. It could be implement at some point, but it's not going to happen in the near future.

I'm closing this issue as duplicate.
