### ISSUE TITLE
Beeftext unexpected quit

### ISSUE THREAD

**Issue by Thefaroah** [xmichelo/Beeftext#186]

**Comment by Thefaroah** [comment]
Checked the new option to use custom sound. Clicked PLAY (accidentally) instead of CHANGE. Beeftext terminated. Restarted and did it the right way and all is well.
Win 10 1903

**Comment by xmichelo** [comment]
Hi @Thefaroah.
Thanks you for reporting this. I could repoduce it, the play button causes a crash if the file is empty or points to an unexisting location.
