### ISSUE TITLE
keywords not replaced or partially replaced in certain web apps

### ISSUE THREAD

**Issue by maraluke** [xmichelo/Beeftext#190]
### Expected behavior
typed in any combo, for example`#date`, combo triggered, keywords replaced with pre-specified snippet, does not happen elsewhere as far as I know

### Actual behavior
after typing `#date`, `#date` either partially or fully remains, and the snippet will be inserted in front of `#date`

### Steps to reproduce the behavior
triggering any combo at [Dynalist](https://dynalist.io/) using Chrome Browser; when using Microsoft Edge it bugs out in a different way that I described [here](https://github.com/xmichelo/Beeftext/issues/180#issuecomment-527666995); does not happen in software like Word.

### Operating system
Win 10 Enterprise, 10.0.16299

**Comment by xmichelo** [comment]
Hi @maraluke,

Thank you for reporting the issue. I could also reproduce the issue in Firefox. 

The problem is that the editor used by dynalist (probably writting in Javascript) does not seem to properly support the 'fast typing' that Beeftext does. 

Unfortunately, I have no fix to offer.
