### ISSUE TITLE
Feature Request: Whitespace trimming variable (#{trim:})

### ISSUE THREAD

**Issue by Corey-Keller** [xmichelo/Beeftext#192]
Assumptions:

1.  There is a trimming variable (I personally suggest ``#{trim:}``)

1. There is the following combo:
  keyword: ``xyz``
  snippet: ``"       some text goes here       "`` (The quotes are just to keep markdown from swallowing the leading/trailing spaces. They aren't in the snippet)
1. A snippet of ``#{trim:xyz}`` would produce ``some text goes here``

**Comment by xmichelo** [comment]
Hi. I like the idea.

**Comment by ZenButterfly** [comment]
Could the trim function be modified to work with the clipboard variable as well as the user-defined combos? 

I have several combos set up that use the clipboard to create a url and if I accidently grab an extra space, they break and I don't always notice.  So something like #{trim:clipboard} here?

Thanks for the consideration. Love the program!!

**Comment by xmichelo** [comment]
That's a good suggestion. thanks.

**Comment by xmichelo** [comment]
The feature is implemented. Here are some test builds:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngfFV7VFOyMGhdfQ5oQ?e=AzWHbi).
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngfFWws7JChatHI7hrQ?e=UY3DKI)

@ZenButterfly I did not implement a specific variable for the clipboard, but you can work around this by creating a combo that just expand to the clipboard content, and use it in a `#{trim:}` variable in a second combo.
