### ISSUE TITLE
Feature Request: Active / Inactive Combos

### ISSUE THREAD

**Issue by prestashopxx** [xmichelo/Beeftext#195]
Can you introduce the functionality to disable / enable individual combos.

Active / Inactive

The point is that it can be turned off, archived, and not deleted.

That we could possibly return in the future.

**Comment by xmichelo** [comment]
@prestashopxx 

It's already implemented: Right click on a combo, and select `Disable` in the context menu.

**Comment by prestashopxx** [comment]
:) Great

Sorry :)

**Comment by prestashopxx** [comment]
And if asleep could not disappear from the list.

Is there a switch on this?
So that you can show, hide.

**Comment by xmichelo** [comment]
No, there's always displayed, they're just greyed-out. 

I'm not too fond of the toggle idea, because it would be easy to forget that you are hiding combos. I suggest you create a combo group and move all your disabled combos there.

**Comment by prestashopxx** [comment]
OK :)

**Comment by prestashopxx** [comment]
Or maybe such an "archive/disabled combos" list would be created automatically?

Okay, okay ... Don't worry ;)

**Comment by prestashopxx** [comment]
Only individual elements can be turned off.

Is it possible to switch off several marked elements (with the SHIFT button) - simultaneously?
