### ISSUE TITLE
Make Beeftext a chocolatey package

### ISSUE THREAD

**Issue by Kalaschnik** [xmichelo/Beeftext#197]
I’m a big fan of chocolatey, which is basically the one and only package manager for Windows, after a fresh install I install a bunch of software using, e.g.:
`choco install 7zip vlc filezilla teamviewer git nodejs vscode opera spotify microsoft-teams office365proplus`

I would love to able to add beeftext in that. Maybe you might want to consider adding you app to chcolatey:
https://chocolatey.org/docs/CreatePackages

**Comment by xmichelo** [comment]
Hi @Kalaschnik 
I'm also a user of chocolatey, and I agree that having a package for Beeftext would be nice.

**Comment by CWempe** [comment]
fyi:

There is a choco packe since January.

https://chocolatey.org/packages?q=beeftext

If you want to install your own language via powershell, I just created this snippet of code. (not fully tested)

```powershell
Invoke-WebRequest https://beeftext.org/translations/BeeftextDe.zip -OutFile "${Env:TEMP}\BeeftextDe.zip"
Expand-Archive -LiteralPath "${Env:TEMP}\BeeftextDe.zip" -DestinationPath "${LOCALAPPDATA}\\beeftext.org\Beeftext\Translations"
```

**Comment by xmichelo** [comment]
Thanks for the information and the tip. I was not event aware that someone made a chocolatey package. I'm planning to work on a feature to easily install and maintain translations up-to-date, but your tip is interesting for automatic deployment.
