### ISSUE TITLE
Wox integration

### ISSUE THREAD

**Issue by Kalaschnik** [xmichelo/Beeftext#200]
Have you heard of Wox? It is a Alfred-like application for windows. I think you engine in Wox would be kick-ass.

https://github.com/Wox-launcher/Wox/issues/1614

**Comment by xmichelo** [comment]
Hello @Kalaschnik .

Thank you for your message. I'm a user of Alfred and Keypirinha myself, but I had never heard of Wox. Unfortunately, I already don't have enough time to work on Beeftext, so I cannot work on an API, or a plugin for another application.

(P.S.) sorry, I messed up replied to you by mail. I copied the message here for reference).
