### ISSUE TITLE
Bt disapear from my screen

### ISSUE THREAD

**Issue by Miragide** [xmichelo/Beeftext#201]
I have used Bt with a second screen, once. Since that I have put Bt window on my 2nd screen, I can't see it on my only one screen anymore (when my 2nd screen are deconnected).

**Comment by xmichelo** [comment]
Hi @Miragide 

I confirm this is a bug. I could reproduce it on my computer. 

In the mean time, you have to exit Beeftext by right clicking on the same icon in the system tray and select `Exit Beeftext', then relaunch the application.

**Comment by xmichelo** [comment]
This is actually not a problem with Beeftext, but it's a generic problem with Windows as I have the same behavior with Firefox or Visual Studio:

- If a window is visible on a monitor, if I unplug the monitor, the window is moved to a visible display (I guess it's send to the primary display).
- If a window is minimized on a monitor, the icon in the taskbar does not move to the primary display and the application remain invisible and seems unreachable. The easiest way to retrieve the application is to activate it using `Alt+Tab`. It is then moved to a visible display.
