### ISSUE TITLE
Beeftext vs Chrome

### ISSUE THREAD

**Issue by Thefaroah** [xmichelo/Beeftext#202]
Beeftext doesn't work in Chrome (Version 77.0.3865.90)

Just shows the keyword.
Opened incognito window with same results, just to prove an extension wasn't interfering.

Win 10 pro ver 1903

**Comment by xmichelo** [comment]
Some antivirus solution include a 'web protection' or 'keylogger protection' that is generally the cause of the problem you are having. If you have an antivirus, can you please try without it.

**Comment by Thefaroah** [comment]
Sorry, nothing worked. Disabled Avast, disabled Smartscreen. BTW, Beeftext does work in Firefox, Edge and Palemoon with Avast and Smartscreen enabled.

Beeftext fails not only in the search bar, but in any "fill in the blank" fields.

**Comment by Thefaroah** [comment]
I'm stumped. Resurrected Wincompose and it works fine in Chrome. For now I use both. Wincompose for Chrome and Beeftext for everything else. Really would prefer to use Beeftext.

**Comment by theictgirl** [comment]
> I'm stumped. Resurrected Wincompose and it works fine in Chrome. For now I use both. Wincompose for Chrome and Beeftext for everything else. Really would prefer to use Beeftext.
> Are there any settings in Chrome that would have an effect on Beeftext?

Just a head up: I am encountering the exact same thing. In Chome and Brave. Works fine everywhere else. Used to work ok.

**Comment by xmichelo** [comment]
Hi.

Sorry to hear you encounter problems. Unfortunately, there is not much I can do. Beeftext interacts with the system by listening to the keystrokes and copy/pasting data through the Windows clipboard. I have zero control beyond that. 
My guess the problem comes from some sort of keylogger protection that I am non aware of.

**Comment by viktorix** [comment]
I have the same issue, with Beeftext not working in Chrome. Keylogger protection is off. Tried listing chrome.exe in sensitive apps settings. No changes.

I did notice Beeftext works in Rambox, which is an Electron app and uses Chromium. So it is something very specific to Chrome that's preventing Beeftext to work.

Also, SHIFT+WIN+ENTER will not activate the combo picker when Chrome is the active window. If I minimize Chrome, combo picker works.

Will continue to test as time permits.

**Comment by Cyprian-Mirewski** [comment]
I understand that you mean entering Beeftext in the browser form fields.

But this doesn't work in Firefox, either.

It seems to me that some additions to Chrome and Firefox browsers would have to be created for this to work.

But maybe not?
Autohotkey will work.

Maybe it can be solved in the future?

**Comment by xmichelo** [comment]
There is no need for a special version. Beeftext works fine in Chrome (and Firefox) for most people. There is something interfering with the behavior of the app. Normally it the web protection module of the antivirus. But if you tell me it's still not working with AV (and any form of 'protection') turned off, then it's something else. 

Provided I cannot reproduce the problem, it extremely difficult for me to fix the issue 😞

**Comment by Thefaroah** [comment]
Is it possible that "Your browser is managed by your organization" is turned on? I don't know how to shut this off and my PC is for my personal use only.

**Comment by theictgirl** [comment]
I have that too, no idea either how to shut this off.

Met enthousiaste groet,

Marjan Crabtree Online Business Architect @ No Crap Online
[image: photo-logo]
Tel 033-7113966
Adres Wilh van Pruisenln 4, 3832CH Leusden
Website https://nocrap.online <https://img.newoldstamp.com/r/40012/w>
KVK # 59856491
<https://mail.google.com/#conversie+%23verkeer+%23optimalisatie>
Op alle diensten, offertes en aanbiedingen
van No Crap Online zijn de *Algemene Voorwaarden* van toepassing.
<https://nocrap.online/av/>
Eigenwijze Digitale Marketing

[image: banner] <https://img.newoldstamp.com/r/40012/b>



Op zo 8 dec. 2019 om 15:59 schreef Thefaroah <notifications@github.com>:

**Comment by viktorix** [comment]
Today, by accident, I typed in my keyword and it worked in Chrome. I tested in multiple places in Chrome, and it's working. I did not make any changes, so the only 2 things I can think off:

1. Chrome updated (I'm running on 78.0.3904.108)
2. I use Sophos Home antivirus, and it was updated today (2.1.10)

Hope that helps anyone. So far everything is working.

**Comment by Cyprian-Mirewski** [comment]
I confirm now works.

But I don't know what the problem was before?
Maybe the Chrome update?

**Comment by xmichelo** [comment]
OK. Glad to here it works now.
