### ISSUE TITLE
DOUBLE ACCENT CHARACTERS

### ISSUE THREAD

**Issue by javierferrand** [xmichelo/Beeftext#208]

**Comment by xmichelo** [comment]
Hi @javierferrand 
This is a known issue ( #107 ). The good news is that there is a fix on its way. It will be included in Beeftext 6.0 which will be available soon.

In the mean time, you can try test builds that include the fix. You can grab them [here](https://github.com/xmichelo/Beeftext/issues/107#issuecomment-545750954).
