### ISSUE TITLE
Imported Combos Don't Go to a Group

### ISSUE THREAD

**Issue by Mystprism** [xmichelo/Beeftext#209]
When importing combos I'm asked "Import into group" and get a dropdown of my groups. I choose the correct group, choose to overwrite existing combos, and click import. The combos should be added to that group, overwriting where applicable. 

Instead, when I overwrite a combo both the old and new combo disappear from that group. The new combos are still added in <_all combos_> but have no group associated with them.

Steps to reproduce the behavior
Choose all the combos in a group. Export them. Import them to that same group and choose "overwrite" in the Conflict resolution section.

This was reproduced on 2 different computers running Windows 10 Pro with the latest updates using Beeftext 5.1

**Comment by xmichelo** [comment]
Hi @Mystprism 
Thank you for reporting. I confirm that I could reproduce this bug.
