### ISSUE TITLE
#{combo:} not working with Rich Text combos

### ISSUE THREAD

**Issue by martinrath77** [xmichelo/Beeftext#213]
Bonjour,

Thank you for v6.0 !

On Windows 10 64bits it seems that #{combo:} do not work when the content is in rich text. 

Here is a first example where both the combo and the linked one are defined as being rich text :

![2019-11-21 08_48_44-Beeftext](https://user-images.githubusercontent.com/58013557/69290795-0cc48c00-0c3c-11ea-9a95-12f59c9622e4.png)
![2019-11-21 08_49_33-Beeftext](https://user-images.githubusercontent.com/58013557/69290796-0d5d2280-0c3c-11ea-8e17-ddbe6ac25066.png)
![2019-11-21 08_50_07-Untitled - Message (HTML)](https://user-images.githubusercontent.com/58013557/69290797-0d5d2280-0c3c-11ea-87ef-1a73aea74dc2.png)

When defining the called combo as plain text and the linked one as rich text only html is displayed :

![2019-11-21 08_55_07-Beeftext](https://user-images.githubusercontent.com/58013557/69290984-af7d0a80-0c3c-11ea-993e-c82536c28355.png)

![2019-11-21 08_49_33-Beeftext](https://user-images.githubusercontent.com/58013557/69291003-bd329000-0c3c-11ea-98cb-e6da7771d851.png)

![2019-11-21 08_56_25-Untitled - Message (HTML)](https://user-images.githubusercontent.com/58013557/69291023-d2a7ba00-0c3c-11ea-83e0-d015f2a334de.png)

Best Regards !

Martin

**Comment by xmichelo** [comment]
Oups. 

I must admit I did not test variables with rich text, so I' m not surprised it's buggy. I'll try to fix that in 6.1.

**Comment by xmichelo** [comment]
I implemented a fix for this issue. Here are some test builds:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSngfFJADp2FegwZzZDug?e=JjRjvJ).
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngfFKqdo_t12nb51Ljw?e=3hfB31).

**Comment by martinrath77** [comment]
Bonsoir de Singapour !

Je viens de tester. Cela fonctionne.

Merci beaucoup !

Best Regards,

Martin

**Comment by xmichelo** [comment]
Thanks for the feedback. I'll release v6.1 soon.

Bonne journée!
