### ISSUE TITLE
beeftext 6 quarantined by Symantec spyware protection (WS.Reputation.1)

### ISSUE THREAD

**Issue by h43ppch3n** [xmichelo/Beeftext#215]
### Expected behavior
Program execution

### Actual behavior
Beeftext.exe quarantined by Symantec Endpoint Protection, Risk: WS.Reputation.1
https://www.symantec.com/security-center/writeup/2010-051308-1854-99?vid=4294919973

### Steps to reproduce the behavior
copy deplyoment of Beeftext-6.0-Portable, start Beeftext.exe

### Operating system
Win10

**Comment by xmichelo** [comment]
Unfortunately there is not much I can do about that. By design Beeftext works by listening to keystrokes, just like malicious keyloggers do. This cause the application to sometimes be flagged as suspicious by security solutions.
