### ISSUE TITLE
Feature Request: Preferences/Settings - Path to configuration files on disk.

### ISSUE THREAD

**Issue by Cyprian-Mirewski** [xmichelo/Beeftext#216]
Preferences/Settings: Path to configuration files on disk.

Path in the settings to the parameters stored on the disk.
It could use the option of self-setting where the program parameters are stored on the disk (path).

This way you could keep the settings in the cloud, e.g. Dropbox, OneDrive ….

**Comment by xmichelo** [comment]
Hi.

I agree and will implement it soon. 

Right now the best solution if you work on multiple machines with a shared/cloud folder is to go for the 'Portable Edition' of Beeftext. All the settings and combos are stored in the application folder.

**Comment by Cyprian-Mirewski** [comment]
In which version is this solution planned?

**Comment by xmichelo** [comment]
I just checked and actually I made a confusion. For the installer based version, the settings are not stored in a file but in the Windows registry. I you want settings in a file, you **have** to use the Portable Edition, where the settings are stored in a .ini file (`Settings.ini` in the `Data` sub-folder of the application).

**Comment by Cyprian-Mirewski** [comment]
@xmichelo 

Thought something like this could be configured via settings.
Just like the backup path.

Screenshot
[https://easycaptures.com/fs/uploaded/1508/5225631898.png](url)

Maybe it could be introduced.
Because the whole program in the cloud is not always kept.
And only the configuration file would be kept on the cloud disk.
