### ISSUE TITLE
Silent Install Switch

### ISSUE THREAD

**Issue by danijeljw** [xmichelo/Beeftext#217]
### Expected behavior
Using command line to install BeefText with `/silent` or `/passive` to silently install

### Actual behavior
Prompts me to uninstall previous version before installing current version.

### Steps to reproduce the behavior
```powershell
C:\>Beeftext-6.0-Installer.exe /silent
```
or
```powershell
PS>Start-Process -FilePath .\Beeftext-6.0-Installer.exe -ArgumentList '/silent' -Wait
```
### Operating system
- [x] Windows 10 x64 1903 Enterprise
- [x] Windows 10 x64 1903 Professional
- [x] Windows 10 x64 1903 Professional N

**Comment by xmichelo** [comment]
Hi.

Thank you for spotting this issue. I never use the  /silent switch, but I definitively to forward it to the uninstaller.

**Comment by acerspyro** [comment]
I'd love to have this to deploy through PDQ Deploy.

You could also use a NullSoft installer, which contains this feature already.

**Comment by xmichelo** [comment]
The Beeftext installer is built Nullsoft NSIS, so when the issue is fixed, you should be able to deploy with PDQ deploy.

**Comment by xmichelo** [comment]
Here is a [candidate build](https://1drv.ms/u/s!AjydspuvJDSngfEBT3QJu4r01Omr2A?e=UaxJq5). The switch for silent install with NSIS installer is /S. The following PowerShell command worked fine for me:
`Start-Process "Beeftext-6.0-Installer.exe" -ArgumentList "/S" -Wait`

**Comment by jazzbanzai** [comment]
same issue in new version, would be nice if it could also silently uninstall when passing the /silent commandline.

**Comment by xmichelo** [comment]
the '/S' switch works for the uninstaller too.
