### ISSUE TITLE
Feature request: restore clipboard

### ISSUE THREAD

**Issue by vuefocus** [xmichelo/Beeftext#220]
When Beeftext kicks in it wipes the clipboard clean.
Can you restore the last clipboard entry after Beeftext has performed its action?

Example:
I **copy some text** intending to paste into my document.
I write something in the document first (and Beeftext corrects some spelling). Then I paste hoping that the text I copied will be pasted in. Nothing gets pasted in.

(Windows 10).

**Comment by acerspyro** [comment]
I agree, this is one of the things that is preventing us from pushing this to our firm. Great software otherwise.

It is also important to ensure that any rich text or miscellaneous content / binary data is placed back as-is, I know some other tools have trouble with this (FastKeys)

**Comment by xmichelo** [comment]
Hi.

Beeftext is supposed to restore the content of the clipboard (at least text, images, and formatted (rich) text). Because of the way the Windows clipboard works, The restore has to de delayed, so you need to wait for 1 second before the clipboard content returns.

I tested in some application (including Word) and it works as expected. Could you give me an example of application where it does not work?

**Comment by vuefocus** [comment]
I tested it again. Now it is working correctly as you describe.
Don't know why it didn't work for me before.
Thanks for taking a look!

**Comment by vuefocus** [comment]
I found it again!
It does not work when copying code lines from **Webstorm**.
https://www.jetbrains.com/webstorm/

Seems to work fine with everything else I've tried.

**Comment by xmichelo** [comment]
Oddly, I could not reproduce it with Webstorm, but I managed to do so in CLion. The main problem is that I rely on the clipboard API of the Qt programming framework. I already notice a few cases where the clipboard is not restored properly, for instance image copied from Photoshop are restored, but lose their transparency.

I should replace the Qt clipboard API by my own routines built upon the Windows clipboard API at some point.

**Comment by vuefocus** [comment]
Yes, it depends upon  where you are pasting to.
In my case Webstorm to the program MyInfo loses the clipboard ... if you type something in MyInfo  that triggers Beeftext before attempting a copy with ^C.
I tried in Word 2013 - it  still has something in the clipboard, but it is not what I put there from Webstorm.
IAC Beeftext is a very useful tool. Thanks!

**Comment by xmichelo** [comment]
The code for the clipboard has been changed in Beeftext 7.1. Do you still experience the issue?

**Comment by vuefocus** [comment]
Works OK now. Thanks for fixing it!!
