### ISSUE TITLE
Merge request: Dutch translation

### ISSUE THREAD

**Issue by SanderGit** [xmichelo/Beeftext#221]
[beeftext_nl.zip](https://github.com/xmichelo/Beeftext/files/3911265/beeftext_nl.zip)

### Expected behavior
Dutch translation

Please merge with Beeftext.

**Comment by xmichelo** [comment]
@SanderGit Thank you! I'm a bit ashamed I was too slow and you had to find out by yourself  😞 .

Now the translation is mostly complete, but Beeftext relies on an external library [XMiLib](https://github.com/xmichelo/XMiLib) That also require translation. There are only a few sentences so it should not take you long. I've generated the Dutch translation file, you can find it [here](https://raw.githubusercontent.com/xmichelo/XMiLib/master/XMiLib/Translations/xmilib_nl.ts) (click the 'Raw' button to get a downloadable version.

One question: what software did you use to translate the sentences. When I loaded your translation in the translation tool (Qt Linguist), I got error message and add to correct some special characters.

**Comment by SanderGit** [comment]
@xmichelo I edited it by hand, was not aware of QtLinguist. Attached file was edited in that app.
Hope you can fix the other file, otherwise please let me know if something still needs to be done.

**Comment by xmichelo** [comment]
Your translation is available in the [dedicated wiki page](https://github.com/xmichelo/Beeftext/wiki/User-provided-translations). If you want me to credit you using your real name instead of your username, just let me know what it is.

I will publish a wiki page with instructions for Qt Linguist and the translation process this weekend.

Thanks again for your work.

**Comment by xmichelo** [comment]
@SanderGit For you information, I have added some documentation about translations in the wiki: [Translating Beeftext](https://github.com/xmichelo/Beeftext/wiki/Translating-Beeftext).
