### ISSUE TITLE
Feature request: Run another application

### ISSUE THREAD

**Issue by Cyprian-Mirewski** [xmichelo/Beeftext#222]
Did you think about launching other programs with Beeftext?

Eg.
; Run Notepad; 
Run c:\PortableApps\Notepad\Notepad.exe
return

**Comment by xmichelo** [comment]
I want Beeftext to focus on a single task: text expansion. If you need a keyboard launcher, [Keypirinha](http://keypirinha.com/) does it very well, and it can do much more.
