### ISSUE TITLE
Feature request: Rich text with Images

### ISSUE THREAD

**Issue by Cyprian-Mirewski** [xmichelo/Beeftext#229]
It could be useful to embed Graphics in Rich text.

**Comment by Cyprian-Mirewski** [comment]
Embedding images could be from external files.

Some "img" variable would have to be defined
for example.

 # {img = "c: \ img \ img.png"}

**Comment by xmichelo** [comment]
Images will be implemented properly when I have edit buttons (font, color, weight...) in the combo editor dialog. They will be external (from the local disk, or the internet).

For the record, right now I'm removing any images in the text when you paste content in the snippet editor. The reason for that is that applications like Word place a copy of the image in the user's temporary folder. The combo works for a while, but when the temporary folder gets cleaned, the image disappear and the combo does not work anymore.

**Comment by xmichelo** [comment]
Support for rich text will stop with Beeftext 8.0. [More details here](https://github.com/xmichelo/Beeftext/wiki/Rich-Text).

**Comment by RyderCragie** [comment]
Is this now supported?
