### ISSUE TITLE
Rich Text: List of supported applications

### ISSUE THREAD

**Issue by Cyprian-Mirewski** [xmichelo/Beeftext#230]
List of tested working applications in Rich Text mode.
And those that will be in the future,
or which one do you need?

for example.
It could use Google Docs support.

**Comment by xmichelo** [comment]
Let's be clear on that: there will be no 'application-specific' support in Beeftext. When it comes to rich text, Beeftext is copy/pasting HTML data in the application via the Windows clipboard. If an application doesn't deal properly with HTML formatted data, their author is to blame.
