### ISSUE TITLE
Randomly inserts last clipboard item when triggered rather than the snippet

### ISSUE THREAD

**Issue by irasanchez** [xmichelo/Beeftext#232]
### Expected behavior
Inserts the snippet associated with the combo

### Actual behavior
Inserts the most recent clipboard item 

### Steps to reproduce the behavior
It's random, and I have not been able to identify a way to reproduce on purpose yet. But it's happened more than once.

### Operating system
Windows 10

Note: uninstalling and reinstalling did not help but manually clearing the clipboard did. When I inspected the clipboard, I could see the snippet was placed just before the most recent clipboard item. I read one of the issues that said it restore the clipboard item. Maybe it's doing it too early and pasting that instead of the snippet? Not sure, still new to this. 

Thanks for the work and product. It makes my life much easier, even if buggy at times.

**Comment by xmichelo** [comment]
Hi. That's strange. Never add the issue on my side. I definitely have to look into it (and my own clipboard built upon the Windows SDK routines instead of relying on the ones from Qt).

Do you use any 'clipboard enhancement tools (ClipX, 1Clipboard etc...), or just the new 'clipboard history' from Win 10?

**Comment by Keek** [comment]
I have been observing this problem as well, it is quite rare though (maybe once every 30  insertions). No clipboard enhancement tools installed, windows 10.

**Comment by irasanchez** [comment]
> Hi. That's strange. Never add the issue on my side. I definitely have to look into it (and my own clipboard built upon the Windows SDK routines instead of relying on the ones from Qt).
> 
> Do you use any 'clipboard enhancement tools (ClipX, 1Clipboard etc...), or just the new 'clipboard history' from Win 10?

I don't use any enhancement tools, just the Win + V shortcut to check the history as you've noted.

**Comment by xmichelo** [comment]
I released Beeftext v7.0 yesterday. This version introduced a very convenient feature for debugging. From the preferences dialog, you can export your preferences. 
In order to be able to reproduce the issue, could you please export your preferences and attach the file to your reply or mail it to info @ beeftext.org, mentioning the issue #232. 

The export file is text, you can review it and check that it contains nothing confidential.

**Comment by Keek** [comment]
Thank you! Please find attached my settings (I have only edited the file paths)
[20200204_BeeftextPrefs.txt](https://github.com/xmichelo/Beeftext/files/4152795/20200204_BeeftextPrefs.txt)

**Comment by xmichelo** [comment]
Unfortunately, I could not reproduce the issue. 

I'm currently working on rewriting the code used to handle the clipboard. As soon I have something to test, I will let you now.

**Comment by NDscham** [comment]
@xmichelo:
I do have the same issue and I also have the Win+V history Windows feature enabled. 
This happened to me exclusively when entering snippets in browser text boxes and if it happens once, it stays like this until rebooting or clearing the clipboard history.

FYI: I am using Firefox 77.0.1 and have configured this as "Sensitive Application". My delay setting was 0ms at the time.

**Comment by xmichelo** [comment]
@NDscham Thanks for your input. 

I'm done with the rewriting of the clipboard code. I will try to post a test build this week-end. Hopefully it will solve the issue.

**Comment by xmichelo** [comment]
Here is the test builds:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSngf9t8WjSp6RLBnMEBg?e=GOGQGh).
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngf9uKX6VFHBSCsgMxQ?e=i3wTKk).

Let me know if it fixes the issue.

**Comment by NDscham** [comment]
Thank you, I will test it during the next week. Will keep you posted on my experience / report back by end of the week.

**Comment by iksub** [comment]
Hello,
I am having the same issue on v13.0 - once I had something else, unrelated, copied, it starts inserting the last clipboard item instead of the snippet.
