### ISSUE TITLE
Feature request: Change Location of Backup

### ISSUE THREAD

**Issue by zahroc** [xmichelo/Beeftext#233]
It would be nice to be able to change the location of the backup file and also create on manually on demand,

**Comment by xmichelo** [comment]
Hi.
It makes sense.

**Comment by xmichelo** [comment]
Hi. The feature has been implemented and will be in Beeftext 7.0. Here are some test builds:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSngfY1QrNys5BX9K3qQA?e=hO9iVv).
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngfY2q1uoYHYkNQ9MsA?e=5jbrzk).

A few remarks:
- Existing backup are moved to the new location when you change the backup folder.
- For manual backups, in the main windows, you can do `Advanced ➜ Backup`. 
- Automatic backups are made every time the combo list is modified, so there is no need for an 'on demand' button in the preferences.

**Comment by zahroc** [comment]
It seems to be functioning so far. Thanks for the quick response to adding this feature.
