### ISSUE TITLE
#{clipboard} fails after upgrade to 6.1

### ISSUE THREAD

**Issue by cortstar** [xmichelo/Beeftext#234]
### Expected behavior
The #{clipboard} tag should insert the contents of the clipboard in the macro.

### Actual behavior
Empty string is added instead

### Steps to reproduce the behavior
Copy text, then activate a beeftext macro containing #{clipboard}.

### Operating system
Windows 10 PRO, v1803

**Comment by xmichelo** [comment]
I can confirm the issue. Test builds with a fix should be available tomorrow.

**Comment by xmichelo** [comment]
Here are the test build:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngfFOPH9HLkTZzmD4lQ?e=PwLFhj)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngfFPNh6vtw5Y1PegVg?e=RaFmRW)

The fix will be included in v6.2, that I will probably release tomorrow.

**Comment by cortstar** [comment]
Just a quick confirmation, tested the release of 6.2 and the bug is resolved. Thanks a lot for the fast response!
