### ISSUE TITLE
Save pause/resume state and apply it after reboot

### ISSUE THREAD

**Issue by byungjikroh** [xmichelo/Beeftext#239]
I'm very pleased that my feature request(#100) about global shortcut function has been implemented at v6.2. Thank you a lot. 😄

I pause/resume Beeftext a lot and want it to be at same state after reboot Windows.

### Expected behavior
Paused or resumed after reboot as same as it was before reboot
Or additional preference option to select if it is paused or resumed after reboot (when Windows starts)

### Actual behavior
Always resumed even if I paused it before reboot

### Steps to reproduce the behavior
Pause it and reboot PC

### Operating system
Windows 10

**Comment by xmichelo** [comment]
Done. Enable/Disable state is now preserved. Here are test builds:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngfFcD2HJBCK98H-kDg?e=OB5BSj).
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngfFdRGU39g-QujkH-g?e=b97VL6).
