### ISSUE TITLE
One Feature - desperately needed

### ISSUE THREAD

**Issue by skerby64j** [xmichelo/Beeftext#242]
### Expected behavior
asap  --->  as soon as possible (a space key NEEDED after asap to trigger)
### Actual behavior
 asap---> as soon as possible (no space key needed after asap to trigger)
### Steps to reproduce the behavior
any where / anytime
### Operating system
Windows 10

**Comment by VaslD** [comment]
For the time being you could use punctuation in keywords. Like setting keyword to `asap.` and replacement to `as soon as possible.`

It's not exactly what you wanted; but considering the ASAP shorthand is almost always followed by punctuation, it's as good as the real deal.

If you're afraid of replacing ASAP every time (in other words you want to conditionally trigger Beeftext keywords), you can prefix/suffix keywords with infrequently-used symbols, like ``"`"`` (grave accent, key sits left of number row 1 on QWERTY).

**Comment by xmichelo** [comment]
In 7.2, there is a new option to trigger a combo only after the spacebar is pressed. You can also choose to remove or to keep the final space.
The options are in `Preferences➜Combos➜Combo Triggering ➜ Trigger only after spacebar is pressed` and `Preferences➜Combos➜Combo Triggering ➜ Keep the final space character`.

**Comment by skerby64j** [comment]
Tried and super!
Thank you very much.     
James 

    On Monday, October 5, 2020, 12:46:00 PM CDT, Xavier Michelon <notifications@github.com> wrote:  
 
 


In 7.2, there is a new option to trigger a combo only after the spacebar is pressed. You can also choose to remove or to keep the final space.
The options are in Preferences➜Combos➜Combo Triggering ➜ Trigger only after spacebar is pressed and Preferences➜Combos➜Combo Triggering ➜ Keep the final space character.
