### ISSUE TITLE
Backup question and suggestion

### ISSUE THREAD

**Issue by Thefaroah** [xmichelo/Beeftext#243]
Question:
1. How often does Beeftext auto-backup? I ask this because I updated to 7.0 and have yet to see a .btbackup file created.
Suggestions:
1. Have a "Backup now" button. This feature depends on the question above. If frequently, no need for this button.
2. Can a limit be set on how many backup files can be retained?

**Comment by xmichelo** [comment]
Hi.

1. Automatic backups are made whenever changes are made to your combo list. Automatic backups do not use the btbackup extension, but .json.
2. As it is made at every change, there is no need for a 'backup now' button. You can still make manual backup by selecting 'Advanced➜Backup' from the main menu.
3. The limit is hardcoded. The last 50 backups are kept.
