### ISSUE TITLE
Win 10 - 1511 - Beeftext 6+ not working

### ISSUE THREAD

**Issue by SevenD7D** [xmichelo/Beeftext#245]
This is more an FYI. This is an old version for Windows 10 and I plan to upgrade soon.

As a workaround, I have now downgraded to Beeftext 5.1 and changed the version in the .json file to be able to load my combo list again.

### Expected behavior
Using my Combo should be replaced with my text
Combo picker should show

### Actual behavior
Combo is not being replaced
Combo picker just inserts the first combo, the selection window doesn't stay open to choose anything

### Steps to reproduce the behavior
I believe this has happened after the upgrade from Beeftext 5 to 6 (and now 7)

### Operating system
Win 10 - 1511

**Comment by xmichelo** [comment]
Hi.

Indeed I think I remember there were some changes introduced in Windows 10 that are required for the pop-up to work reliably. Thanks for notifying.
