### ISSUE TITLE
Beeftext doesn't work properly in Wordpress Gutenberg Editor

### ISSUE THREAD

**Issue by erankatz2020** [xmichelo/Beeftext#247]
### Expected behavior
I tried to use a shortcut from Beeftext while editing a post in Wordpress' Gutenberg editor. Everytime I used it the content from my clipboard (the last thing I ctrl+c'd) was inserted instead of the actual required text. It happened with two different combos.

**Comment by xmichelo** [comment]
Hi.

I think this is probably linked to issue #232. I will close this issue as duplicate, and I invite to subscrible to the other issue.
