### ISSUE TITLE
[feature] export combo cheat sheet

### ISSUE THREAD

**Issue by CWempe** [xmichelo/Beeftext#248]
I am just starting to use Beeftext with more combos.
For a beginner it would be nice to export your combos and print a cheat sheet to place next to your keyboard until you know them well enough.

The export format could be markdown and/or straight to pdf.

I am thinking of something like this:

Gropup|Name|Keyword|Snipüpet
---------|------|----------|-----------
Mail|signature1|bts1|bye
_|signature2|bts2|See you
Dev|update|btapt1|sudo apt-get update
_|upgrade|btapt2|sudo apt-get dist-upgrade
_|upgrade|btapt3|sudo apt-get update && sudo apt-get dist-upgrade

**Comment by xmichelo** [comment]
That's a good idea. thanks for the suggestion.

**Comment by martinrath77** [comment]
Until the feature becomes available, I have found the combo picker to be a good substitute for that.

**Comment by xmichelo** [comment]
I will be working on this feature now. As I already have code to export combo to CSV, I will use the CSV format. You will be able to import it into any spreadsheet and format it as you like.

**Comment by xmichelo** [comment]
I will create a wiki page and post test builds in the coming days.

**Comment by xmichelo** [comment]
The test builds are available:

- [Installer](https://1drv.ms/u/s!AjydspuvJDSngoEeGrvJp3x6aBVBjQ?e=Ywj4Ph)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngoEfAp0BKbn_q3cMhg?e=FfGKw3)

You can find instructions in the dedicated [wiki page](https://github.com/xmichelo/Beeftext/wiki/Cheat-sheets).
