### ISSUE TITLE
Snippets order

### ISSUE THREAD

**Issue by jczanfona** [xmichelo/Beeftext#249]
It would be good if the combo snippets were sorted alphabetically (now I have a mess) and with double click I could select the desired one.

Also can be useful if the icon of the combo picker, launch the application (the Beeftext main window)

**Comment by xmichelo** [comment]
Hi.

Are you talking about the main window or the combo picker? In the main window, you can re-order the snippets by clicking on the desired column name at the top. By default, sorting is done by name (the first column). Double clicking on a snippet will open a window to edit it. In the combo picker, the most recently used combos are shown first. The idea of the combo picker is to be used with the keyboard only by typing text to narrow down the list of possible options.

Opening Beeftext when double-clicking on the Beeftext icon is a good idea.

**Comment by jczanfona** [comment]
Order in the combo picker.
Tx a lot!

**Comment by jczanfona** [comment]
PLS add to Beeftext v8.0
TX a lot!

**Comment by jczanfona** [comment]
Switched to espanso.org
TX
