### ISSUE TITLE
[BUG] Trim lowercases the contents of whatever it is trimming

### ISSUE THREAD

**Issue by Corey-Keller** [xmichelo/Beeftext#254]
### Expected behavior
#{trim:comboname} should produce the contents of the combo triggered by "comboname" with the only alteration being the removal of leading and trailing whitespace.

### Actual behavior
The combo is trimmed, but also lowercased.

### Steps to reproduce the behavior
Use trim on any combo with uppercase letters

### Operating system
Windows 10 1903.

I _think_ the issue began with 7.0, but I'll have to grab old versions to test further.

**Comment by xmichelo** [comment]
I could reproduce and have a fix.
