### ISSUE TITLE
Feature Request: Linux version

### ISSUE THREAD

**Issue by kathytu** [xmichelo/Beeftext#256]
I LOVE Beeftext. Is there any chance of a Linux version of this in the future? Currently lacking a text expander as easy to use as Beeftext on Linux.

**Comment by xmichelo** [comment]
Hi.
Unfortunately, no. There will be no Linux or Mac version. I have little time to develop Beeftext, and I focus on Windows.

If you are looking for a cross platform solution, have a look at [Espanso](https://espanso.org/).
On Mac, I use [Alfred](https://www.alfredapp.com/). If you buy the Powerpack, you get access to the snippets feature.
