### ISSUE TITLE
Space added by Beeftext when pasting

### ISSUE THREAD

**Issue by Li-An** [xmichelo/Beeftext#257]
Hello, when I call this snippet

`site de l’extension sur wordpress.org : <#{clipboard}> – version testée : #{input:version}`

where the content of clipboard is an URL (like https://wordpress.org/plugins/ewww-image-optimizer/), there is a space added ad the end of the URL so I got

`site de l’extension sur wordpress.org : <https://wordpress.org/plugins/ewww-image-optimizer/ > – version testée : 1.0`

### Expected behavior
I expect 
`site de l’extension sur wordpress.org : <https://wordpress.org/plugins/ewww-image-optimizer/> – version testée : 1.0`

### Operating system
Win 10 64 bits

**Comment by xmichelo** [comment]
Hi.

I tried to reproduce, the issue (with the latest official Beeftext 7.0), but I could not. I get no space between the end of the URL and the `>`.

A few questions:

- Do the problem occur in every application you try the snippet into, or only one?
- Do you use a clipboard enhancement application?
- Could you export the snippet (right click on it ➜ export) and attach it here?

**Comment by Li-An** [comment]
Hello, you put the finger on the reason. I use [Ditto](https://ditto-cp.sourceforge.io/) as clipboard management and it is the reason of the extra space. If you have any suggestion to correct this, I will be happy to read it. I see there is a beta version of Ditto and will test it.
