### ISSUE TITLE
[Feature Request] Move cursor to specific location after pasting a combo

### ISSUE THREAD

**Issue by talent-apps** [xmichelo/Beeftext#259]
It would be nice to move the cursor automatically to a specific location after pasting a combo.
Example: The combo is "Hi, thanks for contacting us".
After pasting, the cursor would automatically move to after the "Hi" to easily fill in the name.

**Comment by xmichelo** [comment]
Hi.
It's already implemented. See the `#{cursor}` variable in the [wiki page](https://github.com/xmichelo/Beeftext/wiki/Variables#cursor).

**Comment by talent-apps** [comment]
Thanks for the reply.
This project is super handy!
