### ISSUE TITLE
#{cursor} variable not working properly when combo has emoji

### ISSUE THREAD

**Issue by talent-apps** [xmichelo/Beeftext#260]
### Expected behavior
After pasting a combo with a #{cursor} variable **and an emoji**, the cursor will be located where the #{cursor} variable was included.
### Actual behavior
The cursor is located before its expected position.
### Steps to reproduce the behavior
Use this combo:
> Hi#{cursor}, this is a combo with emoji 🏆.

**Comment by xmichelo** [comment]
Hi.

I managed to reproduce the issue. It's indeed linked to the emoji.

**Comment by xmichelo** [comment]
Hi.

Here are test build for a fix:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngoEbA4QxgQdpugwrxg?e=myuSuk)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngoEcOE_gBIeYJH35wQ?e=jqZdan)

**Important Note**: there is no way for me to make  sure the cursor variable works properly with [compound emojis](https://eclecticlight.co/2018/03/15/compound-emoji-can-confuse/). The final cursor placement is done by placing a series of 'left arrow' keys. Unfortunately application tends to have different behavior when 'traversing' a compound emoji.
