### ISSUE TITLE
Feature request: lua support

### ISSUE THREAD

**Issue by joukevandermaas** [xmichelo/Beeftext#264]
It would be really nice to add support for lua (or any other scripting language). Below follows a design that could work, but really I care most about the capability and not so much the specifics.

The only way to add functionality is to open an issue. Sometimes functionality really does not belong in BeefText itself because it is too specific, but that is currently the only way. I don't think that scripting should replace built-in variables, but it would be a nice extension.

My personal use case is more advanced date manipulation. Specifically I am using [Roam Research](roamresearch.com/) which formats dates like `June 1st, 2020`. There is currently no way to add the `st` using qt date format strings that I could find.

### Initial design

As I said above, this is just a suggestion. Similar to Combos, scrips are user defined snippets of lua code. They must be a function and can have a name. These can be called from combos.

In Combos, there's a new special variable that allows calling functions: `#{script:myFunc('some input')}`. This calls the function and inserts the returned string. The general format is `#{script:<single line of valid lua>}`.

**Comment by xmichelo** [comment]
It's an interesting idea, however I must admit this is quite a development effort, and I have limited time to work on Beeftext, so you should not expect it to be implemented soon.

**Comment by joukevandermaas** [comment]
I don't have much experience with C/C++ but if I created a mock implementation, would you be willing to review it? There would be no expectation to have it merged, just want to see if I can get it working.

**Comment by xmichelo** [comment]
Hi. 
No. I have many other things I want implemented first, and such a feature will require a level of maintenance that I cannot afford.

**Comment by joukevandermaas** [comment]
for my purposes this can be closed with #305.
