### ISSUE TITLE
Windows protected your PC

### ISSUE THREAD

**Issue by jantonacci** [xmichelo/Beeftext#267]
### Expected behavior
Beeftext.exe from BeeftextPortableEdition starts and I enjoy unicode text expansion goodness.  This has never worked, first attempt today.  

### Actual behavior
![image](https://user-images.githubusercontent.com/12749853/83277868-eace3800-a18f-11ea-858d-716addcfcec8.png)

Microsoft Defender SmartScreen prevented an unrecognized app from starting.  Running this app might put your PC at risk.

App: Beeftext.exe
Publisher: Unknown publisher

### Steps to reproduce the behavior
Run Beeftext.exe

### Steps to resolve issue
Expecting the fix will require registering as a developer or including documentation to bypass security; see image...

![image](https://user-images.githubusercontent.com/12749853/83279357-3d105880-a192-11ea-8f41-b64c5ea4951b.png)

### Operating system
Windows 10 enterprise, Version 1809, OS Build 17763.1217

**Comment by xmichelo** [comment]
Hi.

I' m aware of the issue. Unfortunately, passing the SmartScreen check requires a EV code signing certificate. This clocks at $400 per year, So it's not an option.

**Comment by Cyprian-Mirewski** [comment]
Social funding could be useful.
Donations from people.
