### ISSUE TITLE
[Bug] Date (month) is off

### ISSUE THREAD

**Issue by winpie** [xmichelo/Beeftext#279]
#### Expected behavior
Display date using snippet #{dateTime:mm/dd/yyyy} to display the date. Ex: 07/29/2020

#### Actual behavior
I get a different month 26/29/2020 (I used the snippet and got that)

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v7.0
#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment]
Hi. This is actually not a bug. lowercase 'mm' mean minutes. For months use uppercase 'MM'.
You can find all the formatting options in the following links:
- [Time](https://doc.qt.io/qt-5/qtime.html#toString)
- [Date](https://doc.qt.io/qt-5/qdate.html#toString-3)

**Comment by winpie** [comment]
Ahhh... Thank you!
