### ISSUE TITLE
Add support for rich text snippets.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#28]
Snippets should support rich text (i.e. with formatting, as opposed to  plain text).

**Comment by xmichelo** [comment]
Nobody seems to be missing this. Closing.

**Comment by rcphq** [comment]
I was actually going to suggest this feature, would it be hard to implement? i think simple bold/italic, etc would go a long way towards making the app useful in more use cases.

**Comment by vjusk** [comment]
i agree!
