### ISSUE TITLE
Single key to enter a combo?

### ISSUE THREAD

**Issue by Jodanzuki** [xmichelo/Beeftext#280]
I am coming from Breevy. Because the software is discontinued, I am looking for an alternative. Would beeftext be able to support a single key combo confirmation (I use Ctrl on Breevy). Could a user select per-combo if it will be automatic or combo-key dependent?

**Comment by xmichelo** [comment]
Hi.

Thank you for your suggestion. I will introduce an new option where the combo is not triggered before you press the space bar. Subscribe to issue #282 to be informed when it is implemented.

Use a configurable key (especially modifier keys like control) would be problematic in many case.
