### ISSUE TITLE
[Feature] Allow multi-word search in the combo picker.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#283]
Hi @xmichelo

Could you please implement the use of multiple keywords in the combo picker? In the image above, for example, I'd like to use "sample japanese" to narrow down the search. It's a very useful feature when you have hundreds of snippets.

Thank you very much.

_Originally posted by @dp1702 in https://github.com/xmichelo/Beeftext/issues/162#issuecomment-667557560_

**Comment by dp1702** [comment]
Thanks for considering the request. It would be nice to have partial word matching and incremental search as well. That way one could just type "samp jap" to find "sample japanese" in the example above. I also think that disregarding the order of the words in the combo name so "sample japanese" and "japanese sample" would return the same result is probably better to find the right combo faster.

**Comment by xmichelo** [comment]
Hi.
I've implemented the feature. Here is a test build.

- [Installer](https://1drv.ms/u/s!AjydspuvJDSngoMx4QbxkOhhQY1I7w?e=4iHr0p)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngoMylq1sKG_-wutTUw?e=s00Nbe)

Instead of considering the search string as a whole, it is now split in words. To appear in the list every word must appear - even as a partial word - in the name, keyword or snippet.

**Comment by dp1702** [comment]
I'm using the test build and the new search is working flawlessly. It's a game changer for my use of Beeftext.

I've already imported 180 combos that have from 05 to 10 words in the names and the new search makes it very easy to find the right one.

Thank you very much.

Just another question or feature request: is it possible to change the combo picker window size?

It's seems locked at 442 x 319 and some long combo names aren't fully displayed. A preference to change the window and the font sizes would be great.
