### ISSUE TITLE
[Bug] Combo won't trigger if there's no space before it

### ISSUE THREAD

**Issue by jesuslencina** [xmichelo/Beeftext#290]
#### Expected behavior
I don't have the apostrophe character on my keyboard, so I created a combo with the :apo keyword. However, it will only work if there's nothing before it; So if I wanna write "You're" it will look like "You:apore". And it's annoying to separate the word so it works and then delete the space.  
#### Actual behavior
Ex: "John:apos car" instead of John's car (unless I go back and insert a space, and delete it right after) 
#### Steps to reproduce the behavior
Use any keyword 
#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
7.1 Installed on the system
#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment]
You need to edit the combo and set the value of the `Matching` variable to `Loose`.

For details on the matching mode, see https://github.com/xmichelo/Beeftext/wiki/Matching-mode
