### ISSUE TITLE
Combo Triggering with space [Feature] 

### ISSUE THREAD

**Issue by CosimoMatassini** [xmichelo/Beeftext#291]
In order to avoid collisions AUTOMATICALLY a new feature like this is a MUST. 
For example, a combination using Strict Matching like
[ft-->feature] will prevent [ftr --> featuring] 
to work.
Instead of being triggered immediately, a combo could be triggered only when space is pressed. This can make separated words thanks to the space.
Shortcuts are not so convenient and they require a lot of time to do.

**Comment by xmichelo** [comment]
Hi.

Well, you will be happy to know that I implemented that... yesterday. How lucky! Have a look at the [original issue](https://github.com/xmichelo/Beeftext/issues/282). You'll find test builds and instructions in the comments.

**Comment by CosimoMatassini** [comment]
What about special characters like dot, comma etc?
