### ISSUE TITLE
Ability to undo a text replacement

### ISSUE THREAD

**Issue by ThatOtherAndrew** [xmichelo/Beeftext#293]
**Is your feature request related to a problem? Please describe.**
Occasionally, you might frequently use a shortcut which you find very useful, but there are times where you want to type just the keyword without it being corrected. It's not very common and is mostly a result of a bad keyword, but there are situations where it could be very helpful to be able to easily revert an auto-correction.

For example, if you are typing in German, you may wish for a double s (ss) to be auto-corrected to an eszett (ß), but there is no easy way to type just two times the letter s if you are typing an English word, for example.

**Describe the solution you'd like**
Auto-corrected text gets reverted back to the keyword if you press backspace immediately after the correction. I believe this is logical as this shares parity with mobile phone keyboards, where you can press backspace to undo a spelling correction.

**Describe alternatives you've considered**
An alternative would be the ability to assign "switches" to individual combos or groups, and maybe the ability to assign keyboard shortcuts to switches, to turn the combos on or off.

**Additional context**
None

**Comment by xmichelo** [comment]
That's not possible because the behavior of the backspace/undo is specific to each application, and Beeftext cannot read if and what have been restored. An example: 
- Notepad: An undo will revert the keyword and select it.
- MS Word: An undo will not restore the keyword.
