### ISSUE TITLE
[Feature] Enable/Disable Group

### ISSUE THREAD

**Issue by kpym** [xmichelo/Beeftext#294]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to be able to disable/enable the entire group, not just one combo at a time.

**Describe alternatives you've considered**
We can disable/enable combo by combo.

**Comment by xmichelo** [comment]
Agreed. It would be useful to be able to disable an entire group.

**Comment by kpym** [comment]
Thanks for considering my request !
