### ISSUE TITLE
can't use snipplets on my work software

### ISSUE THREAD

**Issue by Fonkybanana** [xmichelo/Beeftext#297]
Hi, 
I need help to make beeftext work in my work software.
Beeftext works great on other softwares but not on this one.
ctrl+v work on my job software, I already try to add the processus to the exception list on prefs
I don't know what I can do so thanks for the help !

**Comment by xmichelo** [comment]
A few questions:
What is actually happening? does the keyword actually disappear, do you hear the beeftext combo sound (Ensure you have `Play sound on Combo` enabled and `Use Custom sound` disabled in the Preferences.

**Comment by Fonkybanana** [comment]
Hi! Thanks for your help
Actualy nothing happen, 
I hit *ttt wich is the shortcut supposed to activate my snipplet and nothing happen, no sound, no text remplacement, the keyword stay in place.
I have tried with differents shortcuts... same result
It works great on every other software

**Comment by xmichelo** [comment]
There are two majors part in the combo substitution process:

1. Recognizing keywords: this is done universally by registering a hook that 'listens' to what you type.
2. Performing the substitution: to do that, Beeftext synthesize a copy/paste operation.

It seems that your application is actively blocking the first step. This is probably a security feature to prevent malwares from stealing your company's critical information. Unfortunately there is nothing I can do about that.

Have you tried the [Combo Picker](https://github.com/xmichelo/Beeftext/wiki/The-combo-picker-window) feature of Beeftext? I'm interested to know if it works in your application.
