### ISSUE TITLE
[Feature] Conditions based on local time/date or other variables

### ISSUE THREAD

**Issue by sLyZah** [xmichelo/Beeftext#303]
Hello,
First, thank you for your work this is an amazing tool that I should use even more!

Using it a lot for communication, it would be useful to be able to have different combo based on the time of the day.
For example, if it’s the morning it would write "Good morning", during the afternoon, "Good afternoon" etc. Based on the day of the week this could become, "Have a nice day" or "Have an excellent weekend" etc.

Thanks in advance,
Sylvain

**Comment by xmichelo** [comment]
I would like to keep snippet evaluation to a bare minimum in Beeftext. What you're asking is rather advanced, and unlikely to make it in a future release.

I understand the need however, and one of the solutions I'm considering is to introduce a variable that would run an external program/script and capture its output. 

Example: `#execute{C:\Users\username\scripts\greeting.ps1}`, where `greetings.ps1` is a PowerShell script that display the appropriate greeting formula based on the time of the day.

**Comment by xmichelo** [comment]
I'm closing this request as I have opened #305

**Comment by sLyZah** [comment]
> 
> 
> I would like to keep snippet evaluation to a bare minimum in Beeftext. What you're asking is rather advanced, and unlikely to make it in a future release.
> 
> I understand the need however, and one of the solutions I'm considering is to introduce a variable that would run an external program/script and capture its output.
> 
> Example: `#execute{C:\Users\username\scripts\greeting.ps1}`, where `greetings.ps1` is a PowerShell script that display the appropriate greeting formula based on the time of the day.

This seems rather more complicated than what I had in mind. Knowing that we can already access the local time. It would be another variable to maybe say if it’s AM/NOON/PM or something like that. Maybe with more granularities, I get your point tho.
