### ISSUE TITLE
[Bug] using #{combo:<keyword>} when keyword is assigned multiple times isn’t randomised

### ISSUE THREAD

**Issue by sLyZah** [xmichelo/Beeftext#304]
#### Expected behaviour
Having multiple snippets assigned to the same keyword randomise the snippet that’ll be inserted.

![image](https://user-images.githubusercontent.com/2497159/95329890-f81ad200-08a7-11eb-921c-18e33179cdc0.png)

It should be randomised when used within another snippet but, it always picks the first one.

![image](https://user-images.githubusercontent.com/2497159/95329936-0c5ecf00-08a8-11eb-9989-5211392cfb4a.png)

#### Actual behavior
Using #{combo:$hay} in another snippet always picks the first one.

#### Steps to reproduce the behaviour
1. Create two or more snippets with the same keyword
2. Create a snippet (X) with #{combo:\<keyword\>}
3. Use the snippet (X) multiple times

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v7.2

#### Operating system version (e.g Windows 10)
Windows 10 Pro

**Comment by xmichelo** [comment]
Obviously a bug. Thank you for reporting. I'll make sure the variable is properly evaluated in v8.0

**Comment by sLyZah** [comment]
> 
> 
> Obviously a bug. Thank you for reporting. I'll make sure the variable is properly evaluated in v8.0

You’re welcome thank you for your time/work and great tool!

**Comment by sLyZah** [comment]
It works like a charm, thank you @xmichelo
