### ISSUE TITLE
Enter variable by tabbing from one entry to the next

### ISSUE THREAD

**Issue by calvinwashere2** [xmichelo/Beeftext#307]
This is a feature request, not an issue.

Like a form letter, you set a variable for each space you want to be able to type in information and then tab to the next fill-in variable in the text. 

Something like this:

Hello #{Name}, 

Are you from #{State}? If so you it's your #{Word} day!

When you tab it goes from Name to State, and Word.

**Comment by xmichelo** [comment]
It is impossible to ensure that behavior works in most application, that's why the solution used to cope with that kind of problem is through message dialog, using the [#{input:} variable](https://github.com/xmichelo/Beeftext/wiki/Variables#input).
