### ISSUE TITLE
[Feature] Shortcut to Add Combo without opening beeftext

### ISSUE THREAD

**Issue by harun** [xmichelo/Beeftext#309]
Is there a shortcut on windows to open beeftext ?
Also shortcut for adding new combos without opening beeftext. If there is shortcut for adding new combo there is no need a shortcut for opening beeftext.

**Comment by xmichelo** [comment]
No there isn't. This would require global shortcuts, and the more you have, the more likely there is to create a conflict with other applications. Instead I will add an entry in the system tray menu. I've created a [feature request](https://github.com/xmichelo/Beeftext/issues/312) for that.
