### ISSUE TITLE
[Feature] Filter Groups on Combo Picker / Search only in specific group

### ISSUE THREAD

**Issue by harun** [xmichelo/Beeftext#310]
Is possible filter Groups by on combo picker by typing ?

i.e 
JS : Map
PY : Class
SQL: Group

When I write  "JS : Map" in picker I would like to search "Map" only in "JS" groups

**Comment by xmichelo** [comment]
At the moment the name of the group of the combo is not used during the search, but it's a good idea to add it. I will do that for v8.0.
