### ISSUE TITLE
[Feature] Smart Combo 

### ISSUE THREAD

**Issue by harun** [xmichelo/Beeftext#314]
I think this feature requires much development. 
But if this feature available, this tool will be the greatest of all text expander.
This feature will be optional via settings.

Combo Groups will be chosen **via active window**.
If I work on `VSCode,` vscode combo groups will be active. Then I will be searching only in VSCode groups.

Also Combo Groups will be chosen **via active tab on browser** (Chrome).
If I visit github.com `GITHUB `groups will be active.

**Comment by xmichelo** [comment]
Sorry, It's not going to happen. I have other development priorities.
