### ISSUE TITLE
Variables and macros feature request.

### ISSUE THREAD

**Issue by simonforget** [xmichelo/Beeftext#315]
Hi!

Would it be possible to add system (username, date, time,) and user-defined variables and basic macros support (Javascript or other scripting language) to Beeftext?

Keep up your excellent work!

**Comment by simonforget** [comment]
Please close this as an non-issue. I just figured out this was already there.

Keep up your excellent work!

**Comment by simonforget** [comment]
Non-issue. Feature request on something already there.

**Comment by xmichelo** [comment]
As you already noticed, you can already retrieve environment variables. In addition to that, Beeftext v8.0 will introduce a new `#{powershell:}` variable that will let you run a PowerShell script and capture its output.
