### ISSUE TITLE
Beeftext considered a virus, a threat.

### ISSUE THREAD

**Issue by Cyprian-Mirewski** [xmichelo/Beeftext#316]
Problem with antivirus detection of Beeftext as a threat.

It should be corrected so that the antivirus does not consider the program a threat.
Because it damages reputation.

In my case, it looks like AVG antivirus allowed the program to run.
But when it's disabled, something is happening that it considers suspicious activity.

What happens when the program is closed?
That the antivirus program considers it suspicious?

PS
There are many opensource programs that are not considered virus threat.
It is very rare for me that such a program is detected by an antivirus.
e.g. with programs from https://portableapps.com/ - there are no such problems.

**Comment by xmichelo** [comment]
At the moment, Beeftext is considered virus free by all 70 engines on [virustotal.com](https://www.virustotal.com/gui/file/7ecdef2373257eb6cd8c458041f88dbc86ddc6ff6bdfc3a2e7c73a0c666fd922/detection)

I'm done fighting with AV manufacturers. The core problem is that, by nature, Beeftext registers itself to "listen" to keyboard input, and that's exactly what a password stealing keylogger does. This causes Beeftext to be often flagged as malware/virus by [heuristic engines](https://en.wikipedia.org/wiki/Heuristic_analysis).

To be clear: Beeftext does not install any permanently running daemon/service. It's a single executable. If you close the window, you still have the tray/notification area and Beeftext is still running in the background. you can fully shutdown the application by selecting 'Exit Beeftext' from the main menu or the tray icon context menu.

**Comment by Cyprian-Mirewski** [comment]
The problem is when the program is fully shutdowns „Exit Beeftext.

This is likely to be behavior monitoring when the program is closed.
Maybe something could be changed in Beeftext?

**Comment by Cyprian-Mirewski** [comment]
It would be nice to create a test environment in which the operation of the program would be tested on various virtual machines with the most popular antivirus programs.

Or at least test a specific antivirus whenever someone reports a problem.

Failure to fix this aspect in Beeftext damages its reputation.
