### ISSUE TITLE
[Feature] add support for search combo snippet

### ISSUE THREAD

**Issue by jizhask** [xmichelo/Beeftext#317]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
currently, we only can search by name or keyword. 
Could you please add support for searching in snippet?

**Comment by xmichelo** [comment]
I just checked and the snippet context is also used when search in the combi picker.
In v8.0, the search will be extended to the combo name.

**Comment by xmichelo** [comment]
Sorry, I just realized you were not talking about the combo picker, but the search box in the main window. I'm re-opening the issue.

**Comment by jizhask** [comment]
Thanks for your reply, yes , i mean the the search box in the main window.
very expect to v8.0. 😁
