### ISSUE TITLE
[Feature] Donations from people.

### ISSUE THREAD

**Issue by Cyprian-Mirewski** [xmichelo/Beeftext#319]
**Have you thought about getting people to donate?**

For example, see:
[https://cryptomator.org/donate/](https://cryptomator.org/donate/)

Screenshot:
https://easycaptures.com/fs/uploaded/1508/9907957772.jpg

  
You may have additional value for getting paid.
Eg License to unlock the black theme.

Maybe for something like this, bonus:
[https://github.com/xmichelo/Beeftext/issues/301](https://github.com/xmichelo/Beeftext/issues/301)

Such measures will be useful for you, for example, for: EV certificate, etc.

**Comment by xmichelo** [comment]
I get donation proposals from time to time, but I refuses them.

1. I do not need money.
2. Not accepting donations preserves my freedom. 
3. Financing stuff like the EV certification is not an option. I want to keep the financial cost of development to 0. Additionally, I do not accept the policy of MS regarding SmartScreen. They should offer an option for open-source project to get a fully free certificate.
4. I want to keep Beeftext totally free for everybody. Paid extras are not an option.
