### ISSUE TITLE
[Bug] non-breaking spaces are replaced by ordinary spaces

### ISSUE THREAD

**Issue by kpym** [xmichelo/Beeftext#322]
#### Expected behavior

Be able to insert a non-braking space in the combo snippet.

#### Actual behavior

The non-breaking spaces (U+00A0) are replaced by ordinary spaces (U+0020).

#### Steps to reproduce the behavior

Copy paste a non breaking space in a snippet area or type <kbd>Alt+0160</kbd>. Use this combo. Check that the corresponding space is an ordinary space and not a non-braking one.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).

v7.2

#### Operating system version (e.g Windows 10)

Windows 10

**Comment by xmichelo** [comment]
I could reproduce the issue, and did a little search. Beeftext uses the Qt framework for its GUI (and many other functions). Unfortunately, the 'Plain Text Edit' control used for the snippet forces the [conversion of NBSP to standard space characters](https://stackoverflow.com/questions/37999812/qtextedit-changes-control-characters). I have no control over that.

**Comment by kpym** [comment]
Ok, I understand. But maybe you should open an issue on Qt framework pointing to this one (by keeping it open because it was not solved).

**Comment by xmichelo** [comment]
I think I found a workaround. I'm re-opening the issue. I'll provide you with a test build tomorrow.

**Comment by kpym** [comment]
@xmichelo Thanks for considering my comment and for all your work.

**Comment by xmichelo** [comment]
Hi. Here are test builds. As far as I can tell, NBSP are preserved. Please let me know if it works for you.

- [Installer](https://1drv.ms/u/s!AjydspuvJDSngoUJfvxx00DaE_heMA?e=W4rNKF)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngoUIId8ctHuLxer5Qw?e=rEJcON)

**Comment by kpym** [comment]
@xmichelo I tested the new portable edition and it works for me. Thanks for your fantastic job!
