### ISSUE TITLE
[BUG] Cursor placement does not work if contained in a subcombo.

### ISSUE THREAD

**Issue by NDscham** [xmichelo/Beeftext#323]
I have created a "#main" combo that calls two other combos , of which one contains a cursor placement ("#{cursor}").
When calling the #main combo, the cursor is not placed at the desired position. Instead "#{cursor}" is inserted.

I suggest to place the cursor at the position of the first "#{cursor}" magic string occurring, regardless of being inside a subcombo..

Example:
```
**#main combo:**
#{combo:#comment}
#{combo:#args}

**#comment Combo:**
%%%%%% some text
% #{cursor}
%%%%%%
```

**Comment by xmichelo** [comment]
Hi.

Thank you for reporting. I will have a look at the issue soon.
