### ISSUE TITLE
[Bug] Combos (with empty keyword) get lost after restart the app

### ISSUE THREAD

**Issue by greatghoul** [xmichelo/Beeftext#326]
![image](https://user-images.githubusercontent.com/208966/100093762-f1b1db00-2e92-11eb-9d15-7cca8ce0bdc6.png)

I don't like to remeber the keyword, so I created a lot of combos without keyword, it works fine with the combo picker.

But after I restart my computer or app, all combos with empty keywords get lost.

#### Expected behavior

All combos are still in the list after restart the app.

#### Actual behavior

![image](https://user-images.githubusercontent.com/208966/100093989-481f1980-2e93-11eb-859d-d20e2cc2e5d5.png)

When I start the app, it raises this error, and my combos get lost.

#### Steps to reproduce the behavior

![image](https://user-images.githubusercontent.com/208966/100093762-f1b1db00-2e92-11eb-9d15-7cca8ce0bdc6.png)

1. Create a combo with name "example 1", snippet what ever, don't enter any keyword
2. Create another combo with name "example 2", snippet what ever, don't enter any keyword
3. When beeftext tells you "The keyword is alreay in use", click continue, the two combos both get saved and available in combo picker
4. close beeftext
5. start beeftext, it tells you "An error occurred while parsing the bombo list file: One of the combo in the list is invalid"

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).

Beeftext v7.2 Installer Edition

#### Operating system version (e.g Windows 10)

Windows 10

**Comment by xmichelo** [comment]
Hi.

This is rather serious. Thank you for reporting. I will investigate soon.
