### ISSUE TITLE
[Feature] Functional Inputs

### ISSUE THREAD

**Issue by SyncMasta** [xmichelo/Beeftext#329]
Hello, 

my request refers to the insertion of "functional content".

I mean things like the following example:
You create a block with the name #d.
The block should then output the current date in a certain FOrmat (e.g. 2020-11-25). The function "date(yyy-mm-dd)" could then be written in the block as a function

Or that you work with placeholders within the blocks, which are then queried when inserting them. e.g. Input("Enter Name").

Example block:
---------------------------------
Dear Input("Enter Name"),
thanks for your email ...
-------------------------------

When using the block, a modal dialog should come up with an input field.
If you then enter the name, the following output is generated:
---------------------------
Dear SyncMasta,
thanks for your email ...
------------------------------

**Comment by xmichelo** [comment]
There is already such a feature, it's called `variables`. Have a look at the [dedicated page in the wiki](https://github.com/xmichelo/Beeftext/wiki/Variables).
