### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by highend** [xmichelo/Beeftext#331]
#### Expected behavior
On a combo like:
```
a'
```
_after_ another char, print ä

#### Actual behavior
It doesn't convert it to ä

As long as I have no other leading char it works fine but if I want it to be converted in a word, it doesn't work.
Word that I'd like to type: Wären
Wa'
and then it doesn't convert the combo...

#### Steps to reproduce the behavior
Create a combo:
Name: ä
Keyword: a'
Type (plain text): ä

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v7.0 Portable Edition

#### Operating system version (e.g Windows 10)
Microsoft Windows Server 2019 10.0.17763.107

**Comment by xmichelo** [comment]
Hi. Can you please tell me what keyboard layout / language you are using?

**Comment by xmichelo** [comment]
Never mind,  the solution is to edit the combo and set the value of the `Matching` parameter to `Loose`.
You can find the explanation in this [wiki page](https://github.com/xmichelo/Beeftext/wiki/Matching-mode).
