### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by 666EvilGenius666** [xmichelo/Beeftext#333]
*** Removed support for rich text snippets in Beeftext and implemented automatic conversion to plain text. ***

Why would you do this??? This was probably my most used feature and the reason I chose Beeftext in the first place. Please re-implement rich text snippets.

**Comment by xmichelo** [comment]
Hi.

The reasons are detailed [here](https://github.com/xmichelo/Beeftext/wiki/Rich-text).
