### ISSUE TITLE
[Feature] Keypress other than space to trigger combo

### ISSUE THREAD

**Issue by ThomasBisset** [xmichelo/Beeftext#337]
I'll start by saying I have found Beeftext immensely useful - thank you so much Xavier!

**Is your feature request related to a problem? Please describe.**
It's a minor bug-bear. I work in a medical field and I have Beeftext replace the shorthand `rx` to `prescription` in my notes. This works great but a postcode I regularly need to use also has the same letters so I set it to trigger after a space. Unfortunately `rx.` doesn't match, so I'm out of luck if the word falls at the end of a sentence!

**Describe the solution you'd like**
There is already a checkbox under *Automatic Combo Triggering* to *trigger only after spacebar is pressed*. Perhaps it may be possible to allow the user to list some alternative trigger keys? I would imagine the most elegant way of doing it would be to have a text-box where the user can just type the keys they wish to use to trigger, perhaps with defaults being common end-of-sentence punctuation such as `.,!?"')}]`? 

I imagine this would probably result in some unintended substitutions in many users' use cases so I'd definitely make it a toggle-able option, and probably wouldn't make it a default when people upgrade versions!

Cheers!

**Comment by xmichelo** [comment]
Beeftext heavily relies on the fact that Space is the trigger. You'll have to adapt. Have you considered automatic triggering instead?
