### ISSUE TITLE
[Feature] Ability to insert GIF smiles with BeefText

### ISSUE THREAD

**Issue by craziedde** [xmichelo/Beeftext#338]
**Is your feature request related to a problem? Please describe.**
Ability to insert GIF smiles with BeefText

**Comment by xmichelo** [comment]
The 'rich text' feature has been removed from Beeftext (you can find the reasons in [this wiki page](https://github.com/xmichelo/Beeftext/wiki/Rich-text)). So no. But:
- You can still use emojis. 
- Of course you can still have a link to a gif in your combos, but the application you're writing in has to process it by itself.

**Comment by craziedde** [comment]
> The 'rich text' feature has been removed from Beeftext
       ok :( hopefully one day you will have some more time or better framework to bring rich text back
