### ISSUE TITLE
[Bug] Manual sorting not working in Groups

### ISSUE THREAD

**Issue by g33k247** [xmichelo/Beeftext#339]
#### Expected behavior
- Drag and drop groups to perform manual sorting

#### Actual behavior
- Beeftet allows me to drag and drop, but the action does not stick

#### Steps to reproduce the behavior
- Perform a manual move (sort) of a group to change it's position

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
- Beeftext v7.2 Portable Edition 

#### Operating system version (e.g Windows 10)
- Windows 10

**Comment by xmichelo** [comment]
This has been fixed in v8.0.
