### ISSUE TITLE
Bug with Unity Game Client (Legends of Aria): Does not replace all of the trigger text

### ISSUE THREAD

**Issue by therealgorgan** [xmichelo/Beeftext#340]
I am using Beeftext on Windows 10 Pro, freshly installed OS on my laptop. 

I am using Beeftext in conjunction with a video game client for the game Legends of Aria, designed on the Unity platform. 

The issue I am experiencing: 
- The last letter of the trigger text is prepending to the replacement text 
- When typing my trigger text, for example:  /hello  the O is prepended to the front of the replacement text. So if my snippet is to replace /hello with a string: "Hello there! Nice to see you!" then what I would actually result in is "oHello there! Nice to see you!" 

Steps to reproduce: 
- Create any snippet 
- Go into the game window and test the snippet 
- See that the text is replaced by with the last letter of the snippet included at the front 

Troubleshooting completed: 
- Have tried adding the exe to Sensitive Applications list, and watched as the noticeable delay between each character is added, but does not solve the issue 
- Have tried increasing the delay between characters, also does not solve 
- Have tried enabling Use Legacy Copy/Paste, which doesn't appear to change anything 

More info: 
- The game client can be downloaded from Steam or directly from the LegendsOfAria.com website: https://cdn.legendsofaria.com/LegendsOfAria-1.4.0.0.zip 
- The snippets can be tested directly on the first screen inside the Email login text box

**Comment by therealgorgan** [comment]
I should mention that the issue is intermittent, it happens at least 50% or more of the time, sometimes it works as intended though.

**Comment by xmichelo** [comment]
Hi.

Game engines generally implement low level custom code for keyboard input, and as a consequence, may or may not work with Beeftext. I have no resource to implement special treatment for games.

**Comment by therealgorgan** [comment]
Thanks anyways, I'll just have to use AHK or something.
