### ISSUE TITLE
Windows flags installer as Unknown Publisher [Bug] 

### ISSUE THREAD

**Issue by kudosscience** [xmichelo/Beeftext#341]
#### Expected behavior
Installer runs without objection
#### Actual behavior
Windows recommends not running the installer as it's from Unknown Publisher
#### Steps to reproduce the behavior
Run v8.0 exe installer
#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v8.0
#### Operating system version (e.g Windows 10)
Windows 10 Version 10.0.19041 Build 19041

**Comment by xmichelo** [comment]
Hi.

Getting rid of this problem requires that the installer and executable for Beeftext are digitally signed with an [EV Certificate](https://en.wikipedia.org/wiki/Extended_Validation_Certificate). 

Such certificates cost at least $400 per year. This is simply not an option.

**Comment by kudosscience** [comment]
Thanks for explaining. Understandable. It could be worth putting a warning of this with download links so inexperienced Windows users are not discouraged from installing.
