### ISSUE TITLE
[Bug] Wiki PowerShell Sample

### ISSUE THREAD

**Issue by harunflc** [xmichelo/Beeftext#342]
Colon is missing after drive letter : Hello #{powershell:C\Temp\script.ps1}!

Hello #{powershell:C:\Temp\script.ps1}!

https://github.com/xmichelo/Beeftext/wiki/Variables#powershell

Also is it possible to list some usefull scenarios for beeftext + powershell usings.

**Comment by xmichelo** [comment]
Hi.

Thanks for reporting. I've fixed the issue and added a second sample script.
