### ISSUE TITLE
Combo Picker [Feature] 

### ISSUE THREAD

**Issue by Formingus** [xmichelo/Beeftext#346]
After we open Combo Picker on Mouse Click to add text (At moment we need to add with enter)
Thanks in Advance

**Comment by xmichelo** [comment]
Agreed. Thanks for the suggestion.

**Comment by Formingus** [comment]
Friend, should i download new exe file after modification , to compile or
what? No so familiar with Github

*With Respect : Sherif Aliti*

**Comment by xmichelo** [comment]
Hi. I will make a test build for you to test, and will post a link to it later today.

**Comment by Formingus** [comment]
👍 thanks, just notify me when you do. Regards

⁣Get BlueMail for Android ​

**Comment by xmichelo** [comment]
@Formingus, here are the test builds:
- [Installer](https://1drv.ms/u/s!AjydspuvJDSngoVa-GYVCozvfhceIQ?e=OVwv8h)
- [Portable Edition](https://1drv.ms/u/s!AjydspuvJDSngoVZKqov_m2p9jQ_CA?e=Q3gSnu)

**Comment by Formingus** [comment]
Will test and let you know, thanks. 

⁣Get BlueMail for Android ​

**Comment by xmichelo** [comment]
@Formingus I have spotted a nasty bug with the test build (carriage returns are skipped when you create/edit a combo), please do not use and wait for the official 8.1 release.

**Comment by Formingus** [comment]
Tested and working gr8 ad on Mouse Click, what about other requests ?
Should I write here or open a request on GitHub ?
Or neither of them ?

*With Respect : Sherif Aliti*

**Comment by xmichelo** [comment]
Hi. Please create issues. When you create a new issue, you get ask if you want to create a bug report or a feature request.
Please create one issue per request, it's easier for me to track and reference them from GitHub.

**Comment by Formingus** [comment]
Roger that

⁣Get BlueMail for Android ​
