### ISSUE TITLE
A prefix prevents keywords to be expanded

### ISSUE THREAD

**Issue by epikgit** [xmichelo/Beeftext#347]
I'm using the last Beeftext version.

I have a keyword ssff that automatically expand in SELECT * FROM in my DB editor software.

I often use a subquery such as (SELECT * FROM but if I use the parentesis "(" before my keyword, this one is not expanded and I get a useless (ssff

I suspect that the "(" char could be only one of several prefix that prevent the expansion.

Regards

**Comment by xmichelo** [comment]
Hi.
The solution to your problem is to edit your combo(s), and set the *Matching* value to `Loose`. You will find more explanations in [this wiki page](https://github.com/xmichelo/Beeftext/wiki/Matching-mode).
