### ISSUE TITLE
Combo Picker to have option to stay on Top

### ISSUE THREAD

**Issue by Formingus** [xmichelo/Beeftext#349]
Combo Picker to have option to stay on Top will be good option for multipasting.
If we pick stay on top Combo windows will not hide - will past on any double click at cursor position
If we dont pick stay at top , after past Combo window will hide.

Thanks

**Comment by xmichelo** [comment]
This is not possible. The only way for Beeftext to be sure which application the picker was invoked from, it's important that the window disappear as soon as it loose the focus.

**Comment by Formingus** [comment]
Ok thanks , understand ....
*With Respect : Sherif Aliti*
