### ISSUE TITLE
[Feature] Cursor position

### ISSUE THREAD

**Issue by abogawat** [xmichelo/Beeftext#358]
It would be great to have the ability to specify the cursor location once the text has been expanded. This would work really well for programming snippets, for example. 

Let's say I'm adding a tag in HTML, I would want the cursor to be in between the opening and closing tags, rather than at the end.

`<p>[Cursor]</p>`

**Comment by xmichelo** [comment]
It's already possible. See the [#{cursor} variable](https://github.com/xmichelo/Beeftext/wiki/Variables#cursor).

**Comment by abogawat** [comment]
Thanks, @xmichelo! I tried looking for the documentation but didn't find the variables.
