### ISSUE TITLE
Error message on first launch.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#36]
Due to recent changes, the application now display an error message when it is first launched on PC because there is no combo list file.

**Comment by smaragdus** [comment]
I can confirm this error message on first start under Windows 8 x64:

![beeftext 0 8 - 2018-02-06 - error - 001](https://user-images.githubusercontent.com/9025757/35853988-b6ebcb10-0b37-11e8-928e-abf12daa161e.png)

and yes- second run resolves the issue.

**Comment by xmichelo** [comment]
Thank you for your feedback, @smaragdus. The issue is fixed in v0.9 that has just been released.

**Comment by smaragdus** [comment]
@xmichelo 
Thanks for the express fix. I downloaded the latest version of **Beeftext**- **0.9** and will test it later, perhaps tonight.

**Off-topic**
**Beeftext** project is very promising and I will keep an eye on it. There are not many free and open source snippet managers and I like that **Beeftext** is written in C++. Currently I use a commercial product- [PhraseExpress](http://www.phraseexpress.com/), the portable version, but most of its features are disabled in the free version so would like to replace it with an open source alternative. Keep your good work!
