### ISSUE TITLE
[Bug] unhandled exception: Could not register a keyboard hook

### ISSUE THREAD

**Issue by ova13lastar** [xmichelo/Beeftext#360]
#### Expected behavior
No bug ! :-)

#### Actual behavior
Bug at startup from the portable version.
When Beeftext starts with Windows startup, an unhanded exception is generated : "Could not register a keyboard hook"

#### Steps to reproduce the behavior
1. Place a Beeftext's shortcut in %APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\
2. Restart Windows
3. Bug after Desktop appears ! :-(
If I try to relaunch manually Beeftext after 5 seconds, Beeftext starts without exception.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v8.1 Portable Edition

#### Operating system version (e.g Windows 10)
Windows 10 x64 Pro

**Comment by xmichelo** [comment]
Hi.

Is it not an option for your to use the installer version of Beeftext? The Portable Edition is not intended to be compatible with automatic launch at startup.

Otherwise, I think there are options in Windows 10 to delay the startup of an application. See https://www.google.com/search?q=windows+10+delay+startup+app

**Comment by ova13lastar** [comment]
Hi.

I tried with the installer version and the result is the same: "unhandled exception: Could not register a keyboard hook" when Windows start up.

I also tried to delay the start of beeftext with "Autorun Organizer" and "Startup Delayer" and still the same problem... :-/

**Comment by ova13lastar** [comment]
Finally, the problem no longer arises after creating a scheduled task to delay the start of the portable version.
