### ISSUE TITLE
[Bug] Beeftext macro persists too long in clipboard - does not clear quick enough

### ISSUE THREAD

**Issue by Bananamon** [xmichelo/Beeftext#362]
#### Expected behavior

Let us assume I have first copied the text "DEF" using Ctrl + C in Windows 10

1. I use a macro `/abc` which contains the text "ABC"
2. and then I do Ctrl + V in about 1 second

The text that should appear: "ABCDEF"

#### Actual behavior

The macro persists in the clipboard for too long and does not revert copied text DEF quick enough.

What appears: "ABCABC"

#### Steps to reproduce the behavior

1. Copy some text using Ctrl + C. 
2. Use a macro. 
3. Press Ctrl + V immediately

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v8.1

#### Operating system version (e.g Windows 10)

Windows 10 Enterprise
Version 20H2
OS build 19042.928

**Comment by xmichelo** [comment]
Hi. 

Thanks for reporting. That's a limitation of the windows copy/paste mechanism. I have to introduce a delay before restoring the clipboard, otherwise it often leads to erratic behaviors.

**Comment by Bananamon** [comment]
Hello

sorry but I do not face this problem with AHK or Espanso. why is the limitation only on beeftext?

I love beeftext more than others because of the GUI (a well designed one too) and the Combo Picker feature. it is the killer feature of this software.
