### ISSUE TITLE
Beeftext Keeps Closing By Itself[Bug] 

### ISSUE THREAD

**Issue by rickey78** [xmichelo/Beeftext#367]

**Comment by Bananamon** [comment]
this happens to me sometimes on the Discord app. I have to restart Discord app to make Beeftext to stop crashing.

dont know how to reproduce, sorry. it happens on my laptop.

Windows 10

**Comment by Bananamon** [comment]
I think I have figured out what causes the bug

If you have an image copied in clipboard, and if you are using a website/app where you can paste images in chat (eg: Discord app) and you try to do a macro, it crashes Beeftext.

To fix, i copied some random text "awsg;akje" and beeftext stopped crashing.

**Comment by xmichelo** [comment]
Hi.  I could not reproduce the issue with an image in the clipboard (an image itself, or a link to an image file) in discord.
- Does the problem still occur with beeftext v9.0.
- Could you export a combo that exhibits the issue and attach?
- If possible, an image that causes the crash could also be helpful.
- What version of Windows are you using?

**Comment by Bananamon** [comment]
- Unable to replicate it now. It used to happen on Discord and Zendesk. It _seems_ that 9.0/9.1 has fixed it.
- Windows 10 Home, Version 20H2, OS build 19042.1083

**Comment by xmichelo** [comment]
Well, happy to hear. There was a major upgrade from Qt 5 to Qt 6. There's a good chance it fixed the problem, because on my side, nothing has changed in the combo substitution and copy-paste mechanism.
