### ISSUE TITLE
[Feature] Variable for week number

### ISSUE THREAD

**Issue by egabrum** [xmichelo/Beeftext#368]
I know that qdate supports weekNumber() but, as far as I know, there is no way in Beeftext to access the week number as a variable.

Maybe we could use something like 'w' for the week number in the date variables?

**Comment by xmichelo** [comment]
Good point. It's not available at the moment, but I will add support for the following values in the format string of the date variables.
- `w`: week number without leading zero, e.g. `8`. 
- `ww`: week number with leading zero, e.g. `08`.
