### ISSUE TITLE
[Feature] Enable/disable individual macros

### ISSUE THREAD

**Issue by Bananamon** [xmichelo/Beeftext#369]
**Describe the solution you'd like**
A toggle next to each macro, to unable or disable them as we please, instead of enabling/disabling all macros on Beeftext.

**Comment by xmichelo** [comment]
At the moment there are three ways to disable combo:
- Enable/Disable Beeftext from the Beeftext icon menu in the notification area. this will disable all combos.
- Enable/Disable all combos in a group by right clicking on the group name and selecting (enable/disable)
- Enable/Disable a single combo by right clicking on the combo in the list name and selecting (enable/disable).

Notes: there is a bug where a disabled combo is not greyed-out in the list if disabled (see issue #370).
You cannot select multiple combos and enable/disable them in a single operation.
