### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by smaragdus** [xmichelo/Beeftext#37]
Currently **Beeftext** (as of version **0.8**) saves settings in Windows registry:

`HKEY_CURRENT_USER\Software\beeftext.org\Beeftext`

and data in AppData ("C:\Users\UserName\AppData\Local\beeftext.org\Beeftext"- combos- "comboList.json", logs- "log.txt")

For such type of programs for me it is of great importance to be able to use a portable version which saves all its data and settings in program folder (where "Beeftext.exe" resides) so that I can use it with all data and settings on other machines without leaving any traces behind.

Portable version can be implemented in many different ways, for example:

- A dedicated portable version (archive or portable installer) which force **Beeftext** to store all data and settings in program folder without writing to Windows registry and to AppData;
- Portable mode installation- the installer asks whether to install **Beeftext** as normal program or as portable program;
- Command-line argument, for example if **Beeftext** is started with "Beeftext.exe --portable" it does not save settings in registry but in program folder and it does not save data in AppData but in program folder as well;
- Portable flag triggers portable mode- on start **Beeftext** checks program folder for "Portable" flag and if available it saves data and settings in program folder;
- A specific configuration file (for example Beeftext.json in program folder) or a sub-folder (for example- "Data") trigger portable mode.

For many any way to use **Beeftext** in portable mode would be fine.

**Comment by xmichelo** [comment]
Good idea. At the moment I am leaning towards a 'dedicated' portable version, because the update process will be simpler.

I also plan to make Beeftext available on the [PortableApps.com](https://portableapps.com/) platform.

**Comment by smaragdus** [comment]
@xmichelo 

> Good idea. At the moment I am leaning towards a 'dedicated' portable version, because the update process will be simpler.

I think that a separate portable version will be the best choice- it would be easier to use, especially for the average users. I suppose that you may use a "JSON" file to save settings in program folder.

> I also plan to make Beeftext available on the [PortableApps.com](https://portableapps.com/) platform.

Good idea- I think that if [Beeftext](https://beeftext.org/) is available at [PortableApps](https://portableapps.com/) this will make your program more popular.

If you release a portable version of **Beeftext** I may write a short review about it.

If additional tests of the future portable version are needed you can rely on me to test the unofficial builds.

Regards

**Comment by xmichelo** [comment]
@smaragdus I've packed a first preview version of the **Portable Edition** of Beeftext. You can grab it [here](https://nextcloud.x-mi.com/index.php/s/9hZbUQdpPSEOtNg/download).

I have written a [wiki page](https://github.com/xmichelo/Beeftext/wiki/Portable-Edition) that give some details about the Portable Edition, its motivations and its limitations.

For the record, the Portable Edition is using the same executable as the regular version. The portable mode is triggered by the fact that a dummy `Portable.bin` file is located in the same folder as the executable.

Regards,
Xavier

**Comment by smaragdus** [comment]
@xmichelo 

Thank you very much for your work on the portable edition, for notifying me about it and for providing a download link! I downloaded the the archive and I will test it soon. This is just a short message to show my gratitude and appreciation. By the way the [Wiki Article](https://github.com/xmichelo/Beeftext/wiki/Portable-Edition) is well-written. It is obvious but yet you may add a line that the portable edition should not be started from system and other write-protected folders.

I suppose that the portable edition would be useful to you too,

Regards

**Comment by xmichelo** [comment]
Thanks for your feedback and support. 
I will edit the wiki with your suggestion. A paragraph about how to properly upgrade the Portable Edition to a newer version will also appear at some point.

**Comment by smaragdus** [comment]
@xmichelo 

For me updating **Beeftext**  would be rather simple since all data and settings files are kept in a single folder- 'Data'.

I forgot to mention that I prefer the native portable edition- just extract and run, to planned [PortableApps](https://portableapps.com/) version, but I know that there are many people who like to organize their **PortableApps** programs via [PortableApps Suite](https://portableapps.com/suite) so I suppose everyone would be happy with 2 different portable versions available.

Regards
