### ISSUE TITLE
Beeftext recently fails to replace on Firefox and Opera but works on  Vivaldi

### ISSUE THREAD

**Issue by Mike-R-B** [xmichelo/Beeftext#372]

**Comment by xmichelo** [comment]
That kind of problem is generally caused by the anti-virus/web protection software installed on the PC, in order to avoid malicious keyloggers capturing your credentials. I suggest you retry with all AV/Web protection software disabled.

**Comment by Mike-R-B** [comment]
I just saw your answer and disabled Webroot. It worked but I would prefer to e able to set Beeftext as an exception, however I can't find any way to exercise that granularity of control.
