### ISSUE TITLE
[Bug] Additional letter after combo activation while typing in Dynalist

### ISSUE THREAD

**Issue by MinorSingingAirhead** [xmichelo/Beeftext#373]
For example, I want the keyword "da.." to result in displaying the current date.

#### Expected behavior
2021.05.31
#### Actual behavior
2021.05.31d
#### Context
This happens when I use Beeftext in Dynalist (web version [I use Chrome and Firefox, in both the problem accurs] and windows app). It does happen frequently but not always. Don't know why.
#### Operating system: Windows 10

**Comment by xmichelo** [comment]
I'm afraid there's not much I can do about that, as dynalist code is probably messing with the key sequence that Beeftext is generating to perform the substitution. I guess there is a hook defined in dynalist for each keyboard input, and the processing applied sometimes interferes with Beeftext.
