### ISSUE TITLE
[Feature] Silent Install Options for install 

### ISSUE THREAD

**Issue by zero80472** [xmichelo/Beeftext#377]
Silent install options for Deployment packages using switch's 

**Describe the solution you'd like**
MSI installer pack or slient options for deployment 

**Describe alternatives you've considered**
IV tried packing the portable version up as deploying not working

**Comment by xmichelo** [comment]
Hi.

There's already a silent install option: see issue #217. 

From a PowerShell prompt, the following should do the job: 

`Start-Process "Beeftext-6.0-Installer.exe" -ArgumentList "/S" -Wait`

The command-line options for the installer (which is based on NSIS) are listed [here](https://nsis.sourceforge.io/Docs/Chapter3.html).
