### ISSUE TITLE
Combo Picker regression, special characters clears the list[Bug] 

### ISSUE THREAD

**Issue by n00ble** [xmichelo/Beeftext#380]
#### Expected behavior
Combo Picker search field should not be affected by special characters used in the "name" or "Keyword" e.g. C-Bx
Previous version 8.1 a matched "Combo" was displayed and could be pasted

![image](https://user-images.githubusercontent.com/12575312/124480449-eec78300-ddaf-11eb-9b34-546590fe66e0.png)

#### Actual behavior
In version 9.0 the combo list is blank after entering the "-"   e.g. C-

![image](https://user-images.githubusercontent.com/12575312/124480512-0272e980-ddb0-11eb-9e97-216081fd6703.png)

#### Steps to reproduce the behavior
1. create or restore (from backup) a combo with a - or + or / in the "name" or "Keyword"
2. use the "Combo Picker Shortcut" to open the combo search window
3. type a combo name or keyword with a special character in it
4. the options (list) will become empty after entering the special character
#### Beeftext version (e.g. Beeftext v9.0 Portable Edition).
Beeftext v9.0 Portable Edition
#### Operating system version (e.g Windows 10)
Windows 10 x64
I was able to reproduce the bug on two different machines.

**Comment by xmichelo** [comment]
Hi. Thanks for reporting. I can confirm this is a bug. I'll work on a fix for v9.1.

**Comment by xmichelo** [comment]
Here are test builds. Let me know if it fixes the problem for you:
- Installer: [Beeftext-9.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/6767807/Beeftext-9.0-Installer.zip)
- Portable Edition: [Beeftext-9.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/6767809/Beeftext-9.0-PortableEdition.zip)

**Comment by n00ble** [comment]
I tried the Portable version (from the above links), and it seems to work as expected (similar to 8.1). i.e. bug is fixed,

Thank you for your efforts and for a great software.
