### ISSUE TITLE
[Bug]  Beeftext v9.0 Combo Search

### ISSUE THREAD

**Issue by harun** [xmichelo/Beeftext#381]
Combo Name : UI5 : SDK : BUTTON XML

When I search "button" keyword, I get result.

But with this keyword "button xml", I get nothing !

**Comment by xmichelo** [comment]
Hi. Thank you for reporting.

I can confirm there is a bug. I'll fix that ASAP.

**Comment by xmichelo** [comment]
It should be fixed. Here are test builds. Let me know if it fixes the problem for you.

- [Beeftext-9.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/6777188/Beeftext-9.0-Installer.zip)
- [Beeftext-9.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/6777195/Beeftext-9.0-PortableEdition.zip)

**Comment by harun** [comment]
It worked, thank you
