### ISSUE TITLE
[Feature] Show group in combo picker

### ISSUE THREAD

**Issue by Techsigns** [xmichelo/Beeftext#383]
It would be nice to see the related group for each list entry in the combo picker. Especially when there are combos with the same name in different groups and without a key, there is no way to see which group the combo belongs to

**Comment by xmichelo** [comment]
Hi. That's an interesting suggestion. It should be implemented in a future release.

**Comment by xmichelo** [comment]
It should be fixed. Here are test builds. 

- [Beeftext-9.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/6794830/Beeftext-9.0-Installer.zip)
- [Beeftext-9.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/6794832/Beeftext-9.0-PortableEdition.zip)

**Comment by Techsigns** [comment]
thanks for your fast response and the fix, thats perfect
