### ISSUE TITLE
4 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by vipaxis** [xmichelo/Beeftext#384]
VirusTotal detected 4 security vendors flagged this file as malicious
![virustotal](https://user-images.githubusercontent.com/87235866/125166467-b6d28e00-e169-11eb-8070-2daaaf54b74d.png)

SecureAge APEX Malicious
Bkav Pro W32.AIDetect.malware2
Cylance Unsafe
McAfee-GW-Edition BehavesLike.Win32.Generic.rc
https://www.virustotal.com/gui/file/056f9464fbc12d7f27f65b3c4825b27cbad758ed4efc4f5e6f179845b4091688/detection

**Comment by xmichelo** [comment]
Hi.

You will find some explanation [in this wiki page](https://github.com/xmichelo/Beeftext/wiki/Beeftext-is-safe).

**Comment by vipaxis** [comment]
Perfect! Thank you very much Xmichelo. You made my day because I LOVE BEEFTEXT! KUDOS on a great app!
