### ISSUE TITLE
[Feature] Turn off timeout for powershell scripts used in variable

### ISSUE THREAD

**Issue by th-schall** [xmichelo/Beeftext#395]
**Is your feature request related to a problem? Please describe.**
I am trying to use Powershell scripts for a variable to open file/folder selection dialogs in order to have the selected file/folder inserted in the combo text. 

The scripts are terminated after a few seconds before it is possible to navigate to a "distant" path location.

**Describe the solution you'd like**
I would like have a general or per combo/variable configuration turning off or extending the timeout for the script.
If possible, additional usage of script parameters would be great as well reducing the number of scripts for my use case from four to one. 

**Describe alternatives you've considered**
None, since the use case depends on the usage of dialogs which will not close by themselves before a selection is made. 

**Additional context**
Powershell example scripts used: 

# Script 1: File dialog returning file name only
Add-Type -AssemblyName System.Windows.Forms

$dialog = New-Object System.Windows.Forms.OpenFileDialog
$dialog.initialDirectory = "C:\"
$dialog.filter = "All Files (*.*)|*.*"
$dialog.ShowDialog((New-Object System.Windows.Forms.Form -Property @{TopMost = $true })) | Out-Null

$filename = Split-Path $dialog.Filename -leaf
Write-Host $filename

# Script 2: Folder dialog returning folder name only 
Add-Type -AssemblyName System.Windows.Forms

$dialog = New-Object System.Windows.Forms.FolderBrowserDialog
$dialog.ShowNewFolderButton = $true
$dialog.RootFolder = "MyComputer"
$dialog.ShowDialog((New-Object System.Windows.Forms.Form -Property @{TopMost = $true })) | Out-Null

$dirname = Split-Path $dialog.SelectedPath -leaf
Write-Host $dirname

**Comment by xmichelo** [comment]
Fair point. I'll add the option to specify an optional timeout value in ms. If set to 0, there will be no timeout.

**Comment by th-schall** [comment]
Awesome! In case you want to add it to the documentation or to the distribution, I can provide improved scripts for the individual use cases. I would just attach a zip file to this issue, if desired.

**Comment by xmichelo** [comment]
Thanks. I'll for sure update the [wiki](https://github.com/xmichelo/Beeftext/wiki/Variables#powershell) when implemented. Can I use of one your sample scripts as an example? You will be credited, obviously.

**Comment by th-schall** [comment]
Sure you can. Maybe you want to use this one: 

```
# File dialog returning file name only
Add-Type -AssemblyName System.Windows.Forms
$outstring = "No selection"
$dialog = New-Object System.Windows.Forms.OpenFileDialog
$dialog.initialDirectory = "C:\"
$dialog.filter = "All Files (*.*)|*.*"
$dialog.ShowDialog((New-Object System.Windows.Forms.Form -Property @{TopMost = $true })) | Out-Null
if ($dialog.Filename) { $outstring = Split-Path $dialog.Filename -leaf }
Write-Host $outstring
```

I am currently working on a better solution, which uses one-liners in Beeftext calling a single unified script with a keyword parameter. All operational logic for each of the five individual use cases is done in this unified script based on the keyword parameter. I can provide this solution as well, if you want it. It should be completed later today or tomorrow.

**Comment by th-schall** [comment]
Just realised, I pasted the wrong script from an old source in my last post. This one is probably better:

```
$outstring = "No selection"
$dialog = New-Object System.Windows.Forms.OpenFileDialog
$dialog.initialDirectory = "MyComputer"
$dialog.filter = "All Files (*.*)|*.*"
$response = $dialog.ShowDialog((New-Object System.Windows.Forms.Form -Property @{TopMost = $true }))
if ($dialog.Filename) { $outstring = Split-Path $dialog.Filename -leaf }
Write-Host -NoNewLine $outstring
```

**Comment by xmichelo** [comment]
It's done. Here are some test builds.

[Beeftext-10.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/6949387/Beeftext-10.0-Installer.zip)
[Beeftext-10.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/6949388/Beeftext-10.0-PortableEdition.zip)

Excerpt the upcoming wiki documentation:

- The snippet `The name of the file is "#{powershell:C:\Temp\filename.ps1}".` will display a dialog that will disappear automatically after 10 seconds.
- The snippet `The name of the file is "#{powershell:C:\Temp\filename.ps1:5000}".` will display a dialog that will disappear automatically after 5 seconds.
- The snippet `The name of the file is "#{powershell:C:\Temp\filename.ps1:0}".` will display a dialog that will only disappear when the user validates or cancels it.

**Comment by th-schall** [comment]
I did some testing with the portable build. It works like a breeze when used as intended with my use cases, but I wanted to share two observations: 

1. When errouneously setting a _negative_ number for the timeout, the script is terminated immediately without result. I would have expected that the default of 10 seconds is used.
2. Like before, the UI lags for about 3 seconds when a script is started. This does not happen, if the script is started from a powershell directly. It is not problematic, only a little nuisance. 

Find my scripts attached for reference.

Thanks for enabling this use case!
[powershell.zip](https://github.com/xmichelo/Beeftext/files/6950957/powershell.zip)
