### ISSUE TITLE
[Bug] Import button is disabled

### ISSUE THREAD

**Issue by cser** [xmichelo/Beeftext#396]
#### Expected behavior
Import button in import dialog is enabled after file selection or reason for disabling showing

#### Actual behavior
Import button is always disabled and it is impossible to understand why - https://github.com/xmichelo/Beeftext/wiki/Import-and-export didn't help me.

#### Steps to reproduce the behavior
Combos -> Import -> Browse -> select CSV file with this content:
```
"1","first",""
"2","second",""
```
#### Beeftext version
Beeftext v10.0 Portable Edition

#### Operating system version
Windows 7

**Comment by xmichelo** [comment]
Hi.

I can confirm this is a bug. The bug occurs when the CSV file ends with an empty value and does not contain a final return character. 

It will be fixed in the next release. In the mean time, just add an empty line at the end of the file and it should do the trick.

**Comment by cser** [comment]
Thanks for response!
It's strange: I tried to:
- append empty line;
- append two empty lines;
- change line breaks (CRLF, CR, LF);
- put file to D:\expample.csv
Nothing changes.

**Comment by cser** [comment]
Sorry, I've tryed on file with ";", correct file works with empty line!
