### ISSUE TITLE
[Feature] Addition & subtraction in numeric variables

### ISSUE THREAD

**Issue by cmtgcps** [xmichelo/Beeftext#403]
For example, I'd really love to see the date/time functions allow us to use parentheses to add or subtract. So one might be able to create a shortcut for, "a year from today" by putting in, 

`#{dateTime:MM/dd/(yyyy+1)}` which would yield the output "08/17/2022" instead of "08/17/(2021+1)".

**Comment by xmichelo** [comment]
This is actually already possible, I just forgot to document it in the wiki. It is now done, see [this link](https://github.com/xmichelo/Beeftext/wiki/Variables#datetime-2). you can use `#{dateTime:+1d-1y+2h:yyyy-MM-dd hh:mm:ss}` to get the current date plus one day, minus 1 year and plus 2 hours.

**Comment by cmtgcps** [comment]
Hey, thanks for that! Always glad to hear when something is already there and I just didn't know about it.
