### ISSUE TITLE
Problems /w v11: Entries Don't Paste (Blanks) Corrupts Keyboard (Shift always pressed)

### ISSUE THREAD

**Issue by alienfxfiend** [xmichelo/Beeftext#411]
Is v11 & above for Windows 11 only ? Because there are lots of problems in v11: The text doesn't paste, it get's pasted as blank texts\ space in most applications —like Edge browser et. al. (both /w Legacy Paste & unchecked.) Also it corrupts the keyboard & the Shift key gets permanently pressed, have to SignOut & back in. I had no issues /w v10 so I went back to it. Sadly my computer doesn't meet hardware requirements for Windows 11 so I cannot get on it to verify (I'll be on Win 10 throughout) so let me know if I should migrate to v10 permanently.

**Comment by alienfxfiend** [comment]
I don't know for sure, just that it's a new problem that's cropped up with v11: It may be conflicting with "Ditto" Clipboard app from Windows Store I have a few entries attached to keyboard [hooks] keys (also use PowerToys if that's relatable.) My AV, which is Comodo Internet Security Premium has HIPS (Host Intrusion Prevention System) & Auto-Containment disabled plus there's no issue with v10 (it is stable) (v11 corrupts the system or presses the Shift key permanently down when I tested it further)... I like how BeefText never gets unresponsive that's why I use it. I have hundreds of entries [for chatting text replacements], & use the Ctrl+SEMICOLON key for the Combo Picker Window, if that helps —also I would like to add: I want to be able to use Alt+Space for the Combo Picker Window, but currently that's not possible.

**Comment by alienfxfiend** [comment]
I'll give v11.1 another try —it might be because I used Resource Hacker to modify the executable's icon (wasn't an issue with v10 though.) 🤞

**Comment by xmichelo** [comment]
Strange. There are two versions of Beeftext (the installer based-version, and the Portable Edition). Do you have the same problem with both?

**Comment by alienfxfiend** [comment]
I use the Portable Edition. The problem seems to be gone if I don't modify the icon using Resource Hacker. Thank you for your time ! 👍

**Comment by alienfxfiend** [comment]
I use the Portable Edition. The problem seems to be gone if I don't modify the icon using Resource Hacker. Thank you for your time ! 👍

**Comment by xmichelo** [comment]
Good to know. Thanks for the update. I'll add Resource Hacker to the list of thing to check for when troubleshooting.
