### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by alstevneson** [xmichelo/Beeftext#414]
I would like a shortcut - keyboard combo, Beeftext snippet, or Start bar icon to open Beeftext to add new snippets rather than having to find the program and open it

**Comment by xmichelo** [comment]
When the application is running, you can create a new combo or group by right clicking on the Beeftext icon in the notification area (a.k,a. system tray) and selecting the appropriate option in the context menu.
![image](https://user-images.githubusercontent.com/1926756/132037509-43312e4a-1eba-498f-96d4-5062c40c90a9.png)
