### ISSUE TITLE
Pause Beeftext

### ISSUE THREAD

**Issue by smaragdus** [xmichelo/Beeftext#42]
There may be cases when the users would need to disable the automatic execution of combos and in stead of exiting **Beeftext** I think it would be better to be able to pause/disable the program. I would like to suggest a simple implementation- two new commands:

- **Pause Beeftext**, accessible from 'File' menu and from 'Tray' menu, which disables the execution of combos;
- **Resume Beeftext**, also accessible from 'File' menu and 'Tray' menu, which resumes the execution of combos;

When **Beeftext** is paused **Pause Beeftext** command is grayed-out (inactive) and **Resume Beeftext** is active and vice versa- when **Beeftext** is running normally (active state), **Resume Beeftext** is grayed-out (inactive) and **Pause Beeftext** is active.

If you don't like the idea please feel free to discard it and close the issue.

**Comment by xmichelo** [comment]
Once again, a feature I though about and forgot to write down. Thanks.
I will also change the tray and application icon to a grayscale version while paused.

**Comment by xmichelo** [comment]
Fixed by 86662cc
