### ISSUE TITLE
[Feature] Position cursor in a specific position after writing keystrokes

### ISSUE THREAD

**Issue by Mikeypc** [xmichelo/Beeftext#425]
I'm not sure if this is possible, but it would be neat if the cursor could be placed to a defined place in the text after the text has been typed.  For example, I would like to have my cursor in between the quotes after the text has been inserted in the following snippet.

<div class="">

</div>

**Comment by xmichelo** [comment]
It's already possible. Have a look at the `#{cursor}` variable in the [wiki](https://github.com/xmichelo/Beeftext/wiki/Variables#cursor).
