### ISSUE TITLE
Combos Grouping

### ISSUE THREAD

**Issue by smaragdus** [xmichelo/Beeftext#43]
Combos are automatically sorted in alphabetical order which is nice but when the list of combos grows up I think it would be better to be able to group them into folders, for example "Mail', 'Passwords', 'Private', 'Software', 'Web', etc. I believe that folders would contribute to a better organizations of combos. I suppose that the implementation of this feature would not be that simple. This is roughly my idea about grouping of combos into folders:

- New command- **Add Folder**;
- Right-click on a folder- new commands- **Add Combo** and **Delete Folder** (there may be a warning message about folder deletion);
- Current command- **Add** may be renamed to **Add Combo**;
- Double-clicking on a folder expands/collapses it;
- Existing Combos can be moved to folders via drag & drop;

I think that thematic grouping of combos into folders would be useful- it would bring some order into combos list and would also facilitate finding combos.

**Comment by xmichelo** [comment]
Hi.

This is actually already planned. See issue #31.  I called it 'Classification' because I'm still unsure about how it will be implemented. It could be folders as you suggest, or tags à la GMail.

I'm closing this issue as duplicate.
