### ISSUE TITLE
V12: False Trojan detection by Edge/Win 10

### ISSUE THREAD

**Issue by lduchastel** [xmichelo/Beeftext#430]
https://i.imgur.com/dv2txeP.png

**Comment by xmichelo** [comment]
Hi

You'll find the explanation in [this wiki page](https://github.com/xmichelo/Beeftext/wiki/Beeftext-is-safe).

**Comment by lduchastel** [comment]
Thank you for the reminder. I read the wiki page the first time I downloaded v11.1 portable edition and bypassed at that time the common Edge warning. This time, v12 is flagged as "Severe" by Defender and I had to disable/bypass at antivirus level. I thought it was worth mentioning. I understand there is little you can do to solve the issue.

Thank you for your dedication to BeefText and fast response.
This morning, we had a professional training for new managers of large healthcare public organizations in Québec; "we" being École de santé publique de l'Université de Montréal. I made a point to present BeefText to increase significantly productivity !

**Comment by xmichelo** [comment]
Thank you for the free advertisement :)
