### ISSUE TITLE
[Bug] Pause Beeftext does not work in v12

### ISSUE THREAD

**Issue by brian3t** [xmichelo/Beeftext#435]
#### Expected behavior
Pause beeftext
#### Actual behavior
Text still expanding

#### Steps to reproduce the behavior
Right click icon, Pause BeefText

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v12
#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment]
I can confirm there is a problem. Thank you for reporting.

**Comment by xmichelo** [comment]
Here are test builds that include a fix for the issue. Please let me know if it solves the problem on your side:

[Beeftext-12.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/7525270/Beeftext-12.0-Installer.zip)
[Beeftext-12.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/7525271/Beeftext-12.0-PortableEdition.zip)

**Comment by brian3t** [comment]
Awesome, thanks for the quick fix @xmichelo 
I will share with my colleagues
