### ISSUE TITLE
Choosing "Skip" doesn't skip version update

### ISSUE THREAD

**Issue by elle8che** [xmichelo/Beeftext#436]
When an update is available and the "skip" option is offered and selected, the program again shows the update dialogue within x amount of hours. In actuality, we are not allowed to skip a version update. Selecting the "skip" option should result in no further update dialogues (nags) until there truly is an update available beyond the current update. "Skip" should skip. This has happened forever (or as far back as I can recall, through numerous version updates). 

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Latest and at least several versions prior.

#### Operating system version (e.g Windows 10)
Windows 10.

**Comment by xmichelo** [comment]
You're right. The wording is incorrect. The label should be `Not Now`, instead of `Skip`. I will first fix the wording, this will be included in 12.1. And I will implement a new feature to offer a `Skip This Version` option (see issue #437)
