### ISSUE TITLE
Launch Website 

### ISSUE THREAD

**Issue by mdrefat73** [xmichelo/Beeftext#438]
I'd like to be able to open/launch a website automatically as a snippet of part of a snippet

e.g #{RUN:https://github.com} to automatically open the 'github' website

**Comment by xmichelo** [comment]
This is out of the scope of Beeftext. However if you really want to achieve this, you can create a Powershell script and the [#{powershell: variable}](https://github.com/xmichelo/Beeftext/wiki/Variables#powershell), with as script such as

```powershell
Start-Process "https://github.com"
```

**Comment by mdrefat73** [comment]
Thank you so much Xavier for your kind concern and support
Many thanks
Mohamed

Sent from Mail for Windows
