### ISSUE TITLE
[Feature] Update Beeftext automatically ("Install now" button) 

### ISSUE THREAD

**Issue by Keek** [xmichelo/Beeftext#441]
It should be possible to update Beeftext automatically (similar to how Windows updates itself):

![image](https://user-images.githubusercontent.com/337206/143003105-5f3b2934-3b0f-4215-9cd5-0b155f08e1c8.png)

**Comment by xmichelo** [comment]
Beeftext can be set to check for updates from the preferences (one check per day). You will get a notification when a new version is available. (note there is a [bug](https://github.com/xmichelo/Beeftext/issues/445) for some users at the moment and the update check fails).
