### ISSUE TITLE
Combos starting with @ stopped working in ver 12.0 [Bug] 

### ISSUE THREAD

**Issue by zrotar** [xmichelo/Beeftext#443]
#### Expected behavior

after I enter a combo, the assigned text should be pasted

#### Actual behavior

after I enter a combo starting with @ nothing happens in ver 12.0

#### Steps to reproduce the behavior

as described above.

**Comment by xmichelo** [comment]
Hi.

combos starting with @ are working fine for me. Can you help me try to reproduce it by giving me the following information:
- What language and keyboard layout are you using?
- Can you give me an example of keyword that doesn't work.

**Comment by zrotar** [comment]
Slovenian, Slovenian keyboard
@zrg @zrkc @ahg ...

**Comment by xmichelo** [comment]
Hi.

Thank you. I could reproduce it. 

The problem likely comes from the fact that the `@` character uses the `AltGr` key (or `Ctrl+Alt`) on a Slovenian keyboard. I will investigate that.

**Comment by jspidey03** [comment]
Hello,
I have the same issue here with a French keyboard / French language on Windows 10.
And I confirm that I use the `AltGr` key for the `@` character with this configuration.

**Comment by xmichelo** [comment]
Hi. I found the cause of the problem. Please check the following builds, they should fix  the issue:

- [Beeftext-12.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/7792353/Beeftext-12.0-Installer.zip)
- [Beeftext-12.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/7792354/Beeftext-12.0-PortableEdition.zip)
