### ISSUE TITLE
Add copy to clipboard to the picker window[Feature] 

### ISSUE THREAD

**Issue by joe8878** [xmichelo/Beeftext#444]
**Is your feature request related to a problem? Please describe.**
I have an emulator application that will not accept keywords and requires a button to be pressed to add the contents of the clipboard into the command window of the emulator.

**Describe the solution you'd like**
It would be helpful to have the option to copy the snippet directly from the picker window, either via a right-click menu or a button in the picker window.

**Describe alternatives you've considered**
Currently, I type the keyword in notepad and then copy the snippet.  I then use the emulator clipboard button to paste the snippet into the emulator

Something like this:
![CopySnippet](https://user-images.githubusercontent.com/94995988/143312815-4bbfe8b9-f6d0-4440-a299-122fb1dfe013.png)

**Comment by xmichelo** [comment]
Hi.

I like the idea. However, I want to keep the interface of the picker window as clean as possible, so instead of adding a button, I will implement the two following shortcuts to close the window and copy the selected combo into the clipboard:

- With the keyboard: Ctrl+Enter.
- With the mouse: Right click.

**Comment by xmichelo** [comment]
It's implemented, as described above. Here are test builds:
- [Beeftext-12.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/7655455/Beeftext-12.0-Installer.zip)
- [Beeftext-12.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/7655456/Beeftext-12.0-PortableEdition.zip)
