### ISSUE TITLE
[Bug] Replacing keyword when paused

### ISSUE THREAD

**Issue by byungjikroh** [xmichelo/Beeftext#447]
#### Expected behavior
Beeftext should not work when it is paused.

#### Actual behavior
Beeftext replace keyword when it is paused. 

#### Steps to reproduce the behavior
Set Beeftext to be paused and type any keyword.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v12.0

#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment]
Hi. This is a know issue. It's already been fixed and will be included in the next release. Have a look at issue #435 for details. There are link to test builds in the comments.

Closing this issue as duplicate.
