### ISSUE TITLE
[Feature] Support for Linux

### ISSUE THREAD

**Issue by chiggiddi** [xmichelo/Beeftext#450]
This is a very remarkable tool! Easy to use and quite capable to help us developers and product managers close a successful workday with a smile. 

After I have shown my developer colleagues this product, they started to really like it and asked me about its compatibility with Linux. May I ask whether this can be ported to Linux as well?

Best
Cheng

**Comment by xmichelo** [comment]
Hi. Thank you for the message. Unfortunatately there will be no Linux version, as explained in issue #256.
