### ISSUE TITLE
[Bug] Line Breaks not working as expected on Discord

### ISSUE THREAD

**Issue by Taidakun** [xmichelo/Beeftext#452]
#### Expected behavior
Creating a new combo from the main BeefText window and adding a line break should make a line break when the combo is called.
https://i.imgur.com/1eSqdSj.png

#### Actual behavior
When called, the combo does not include the line break, and adds a symbol instead. 
https://i.imgur.com/2BD4cS5.png

#### Workaround
If editing the .json file with basic notepad and replacing the line breaks in the list, it works as intended.

#### Steps to reproduce the behavior
Just create a new combo that includes a line break.

**Comment by xmichelo** [comment]
Hi. This happen to me only when using Shift+Enter instead of enter. When you do that, you get a [line separator (U+2028)](https://www.fileformat.info/info/unicode/char/2028/index.htm) Unicode character (a 3 bytes sequence `0xe280a8`), which does not get interpreted properly.

**Comment by Taidakun** [comment]
Hello there,
Thank you for the reply ! This is indeed the issue. Would it be something that's worth a fix ? I've been using Shift+Enter as per force of habit, since a mere Enter just sends the message in the Discord application. 
If not, I'm happy to work around with a simple enter, but others might face the same issue ! 

Regards,

**Comment by xmichelo** [comment]
I will leave the behavior as, in order not to break Beeftext for people that would actually use the Unicode line separator.
