### ISSUE TITLE
[Bug]  disable/enable doesn't work

### ISSUE THREAD

**Issue by alexofrhodes** [xmichelo/Beeftext#453]
#### Expected behavior
Use shortcut to disable/enable BeefText
#### Actual behavior
Using shortcut changes the color (greyy/red) of the BeefText tray icon but expansion still occurs when using keywords
Same bug when manually enabling/disabling from tray icon
#### Beeftext version 
BeefText 12 installed version
#### Operating system version 
Windows 10

**Comment by xmichelo** [comment]
Hi. This issue has already been reported and fixed. The fix will be in the next release. In the mean time, you can try the test builds that you can find in the comments of the [original issue](https://github.com/xmichelo/Beeftext/issues/435).
