### ISSUE TITLE
[Feature] Allow spaces in keyword

### ISSUE THREAD

**Issue by numeralnathan** [xmichelo/Beeftext#457]
I would like to have a combo with " / " for a keyword.  When entered, Beeftext will replace it with " ÷ ".  I don't want Beeftext to replace / when surrounded by other characters (e.g., a file path).

**Comment by xmichelo** [comment]
Hi.
Sorry, Beeftext heavy relies on space as a mark of the end of a combo.

**Comment by numeralnathan** [comment]
Please allow for specifying the front and end delimiters.  The default should be whitespace.  However, the user may want to specify something else.  Please see PhraseExpress for how they handle delimiters.  That worked very well.
