### ISSUE TITLE
[Feature] Disable Beeftext in specified apps

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#464]
The user may want to disable Beeftext in certain apps, for instance for performance reasons in games.
There should be a way to specify process names for which Beeftext will be disabled.

**Comment by winstxnhdw** [comment]
Is Beeftext disabled when you add a process to "Sensitive Applications"? Not sure how optimised the app is, but I don't really want Beeftext to be attempting to match my WASD key events in the background when I am playing a game.

**Comment by xmichelo** [comment]
The sensitive application box does not turn off Beeftext it modifies the behaviour for snippet replacement. I understand the naming can be a little confusing.

**Comment by xmichelo** [comment]
Good news. I have this implemented. Will be in 15.0.
Also, I just noticed this is a duplicate of #429
