### ISSUE TITLE
New Column - Times Used

### ISSUE THREAD

**Issue by smaragdus** [xmichelo/Beeftext#47]
@xmichelo 

You may add a new column to **Combos** tab- **Times Used** or just **Used** which shows the number of times a snippet has been executed.

This is not a suggestion but just an idea which does not have great value- for me it would be just curious to see how many times a snippet has been used.

If you don't like the idea just ignore it and close the issue.

**Off-topic**
Renaming **combo text** to **keyword** and **substitution text** to **snippet** was a good idea- the shorter the better and the clearer.
Also removing the uninstaller (**Uninstall.exe**) from the portable package makes sense since it was useless.

**Comment by xmichelo** [comment]
Hi.
Thanks for the suggestion. I'm not fond of this one and I'll mark it as rejected. 

The main reason is that, I prefer to keep away from any form of statistics as it could (incorrectly) give the impression that Beeftext is somehow spying on you. 

It may come back later in the form of a 'Usage Statistics' window that would be disabled until you manually activate it in the Preferences.
