### ISSUE TITLE
Any chance to have a variable pull the domain of the current website you are viewing?

### ISSUE THREAD

**Issue by rolltidehero** [xmichelo/Beeftext#471]
Holy sh*t! I can't believe I just learned of the variables this tool uses. That makes this tool even more incredible!

So, for my request, a browser extension would probably be the answer, but it wouldn't hurt to see if this is something you guys can put together easily.

Basically, I have a domain with catch-all email forwarding setup. 
Every time I register on a website, I use that websites hostname as the email address. Eg: github.com@mydomain.com
...and they all get forwarded to my one Gmail account.

There are many reasons why I do this...

1. So I can keep my email private
2. So I can easily block emails from a website that is spamming or that I no longer use
3. My password generator uses a certain hash algorithm with the username as the modifier, so all the passwords are different, but I could easily decrypt them by using my master password, my generated email, my secret prefix/suffix and the hash-type that I use. (See PasswordMaker.org if you're interested. Open source and is available for every OS, every browser, CLI, PHP, anything 😂)

There are probably more reasons, but I think that's enough info to explain why I would like this feature.

Anyways, thanks so much to everyone who committed to this! 
This and another program actually got me off of AHK, which I thought I would use forever.
Beeftext rocks!!!

**Comment by xmichelo** [comment]
Hi. Beeftext cannot do that. You may however try to write your own PowerShell script and use the [#{powershell:}](https://github.com/xmichelo/Beeftext/wiki/Variables#powershell) variable. I'm not even sure this would be possible.

**Comment by rolltidehero** [comment]
I actually found a browser extension that does it. 

My bad. I should have closed this and posted my workaround.

[Copy Host](https://chrome.google.com/webstore/detail/copy-host/bnimbjbohdeakocjbldadiggnlmlgmie) - All you gotta do is press Alt+C
