### ISSUE TITLE
[Bug] using snippet too quickly after another snippet makes it paste the last snippet again

### ISSUE THREAD

**Issue by VladiusMagnum** [xmichelo/Beeftext#473]
#### Expected behavior
Use one snippet, then a different one close after.

#### Actual behavior
If I type a snippet too quickly after another one, without waiting around 2 seconds, it will often use the first one. Sometimes it will even skip places, so if I do snippets A, B, C, C will get replaced with A somehow. It seems like it's some kind of problem with the clipboard but I'm not sure. I increased the delay between simulated keystrokes to the maximum but I can't tell if it did anything.
I ran into this because I use Beeftext for transcription.

#### Steps to reproduce the behavior
I am unsure but I would think just typing snippets really quickly, one after another.

**Comment by xmichelo** [comment]
Hi. This is a known problem. There can be issues when modifying the clipboard too fast, so there is a delay between below which you have the problem that your describe. Unfortunately I have no solution to this problem at this time.
