### ISSUE TITLE
[Bug] Beeftext not working on Notion

### ISSUE THREAD

**Issue by dudaele** [xmichelo/Beeftext#476]
#### Expected behavior
normal text replacement

#### Actual behavior
the combo sound plays as normal, but instead of the keyword being replaced by the snippet, the keyboard is erased and the snippet never appears

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v.13.0

#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment]
Hi. 
Thanks for reporting. 
- Are you using Notion in a web browser, or in the dedicated notion app? Does the alternate version have the same problem for.
- If you have an antivirus / web protection solution, please try disabling it if you can.
- Do you a 3rd party clipboard management software (Ditto, ClipX.... )?

**Comment by dudaele** [comment]
• Hi! Thank you for getting back to me. I am using Notion in its own app on my PC, but I tried on Google Chrome and it turns out it does not work there either. 
[Notion will recognize the text replacements from the built-in Apple setting in my Mac, but not the ones from BeefText on my PC]

• I do not have an antivirus app besides the protection y PC already comes with (I am not 100% sure about how it works, but sometimes I get notifications). The ad block apps I use sometimes also send me notifications about sketchy websites, but I don't know if those could be considered antivirus apps.

• I do not have a 3rd party clipboard management software

**Comment by dudaele** [comment]
Update:
they work now?? I am not sure what happened. 
They are all working for the first time, and this changed in a matter of minutes. While I was typing my response to you, I checked and they were not working. After I sent you my response, I tried again and now they are working in Notion.

The only difference between Notion and the other apps is that in Notion I have to press the spacebar two times to add a space after a text replacement, while on the other apps one time is sufficient. 

If it was fixed from your end, I appreciate it!! :) thank you

**Comment by xmichelo** [comment]
Hi.

I checked the Notion desktop app, and it is working fine for me. Unfortunately, when a problem occurs withing a single application and works anywhere else, there is nothing I. Beeftext is designed to work universally. There is are two possible cause for the misbehavior:
1. The application itself is messing with the keyboard input or the clipboard.
2. An external application is preventing normal operation of Beeftext. This happens mostly with web browser, as some antivirus solutions have web protection module against keyloggers that try to steal your password.
