### ISSUE TITLE
Microsoft Store

### ISSUE THREAD

**Issue by Kenya-West** [xmichelo/Beeftext#477]
**Is your feature request related to a problem? Please describe.**
Microsoft Store is becoming the main trusted source of all apps being installed on a machine, so I (and many less competent in terms of basic computer knowledge) expect every program to be here.

**Describe the solution you'd like**
Publish the app to Microsoft Store.

**Describe alternatives you've considered**
Publishing the app to WinGet Package Registry.

**Additional context**
Publishing to Microsoft Store makes the app automatically available in WinGet but the opposite does not make the app available on Microsoft Store.

**Comment by xmichelo** [comment]
Hi.

Beeftext is available on WinGet via an anonymous contributor, who manager to register the latest version faster than I do.

I will not publish Beeftext on the Microsoft Store:

1. I'm against the principle of regulated stores.
2. Microsoft Store requires the application to be signed, which cost nearly $500 per year.
