### ISSUE TITLE
Pressing Esc to restore the keyword 

### ISSUE THREAD

**Issue by minawaheed9697** [xmichelo/Beeftext#479]
Hi there, 

First, thank you so much for this great app. 

Second, I want any way  to make pressing "Esc" restore the keyword from snippet, not erasing the snippet. 
E.g. I made "hl" for "Hello", I want pressing "Esc" to make it back to "hl" not "Hell"

**Comment by xmichelo** [comment]
In order to work universally, Beeftext does not 'see' the text it's erasing. It does it by sending it repeated  backspaces. This means, that Beeftext cannot restore the keyword.
