### ISSUE TITLE
exporting Combos

### ISSUE THREAD

**Issue by sagimos** [xmichelo/Beeftext#488]

**Comment by sagimos** [comment]
hi, how to i exporst my combos to a different computer? back-up and then Restore on the new pc? this one doesn't seam to work - is it bc the app on the other pc has already few combos of it's own?

ps - it is really a life changing this one!

tnx
Sagi

**Comment by beeftextuser** [comment]
The same problem, very much please solve it. I can not import combos, as long as the program has at least one snippet. I have to delete the combo and only then import the backup. Considering I have multiple backups, this is very inconvenient.

**Comment by xmichelo** [comment]
Hi.

If you backup and restore, the existing combos on the destination computer will *all* be removed and replaced by the one from the backup.

At the moment, there is no way to "synchronize" two instances of Beeftext. It's one of the majors addition I want for Beeftext, but it requires a large amount of time I cannot afford in invest in Beeftext right now.
