### ISSUE TITLE
Feature Request: Allow space at end of keyword

### ISSUE THREAD

**Issue by youngheart80** [xmichelo/Beeftext#49]
This is request is based on how I use TyperTask, but I think Beeftext could benefit from it. I'd like the ability to end the keyword combo with a space so that the combo is only triggered when the space is evaluated. This allows stacking of related combos.

In my case, I'd want' something like, ",d " to trigger date, while ",dt " triggers date and time stamp.

Thanks

**Comment by xmichelo** [comment]
Hi.

Unfortunately space is the *only* printable character that is not allowed in a keyword, and the text substitution engine relies on it as its main *combo breaker*. Whenever a redesign of this core mechanism is planned, I will try to change that, but it is not going to happen in the foreseeable future.

**Comment by youngheart80** [comment]
Understood, that makes sense. Thanks.
