### ISSUE TITLE
[Bug] random non correct parses in specific apps

### ISSUE THREAD

**Issue by makedir** [xmichelo/Beeftext#495]
I get a weird non consistent parse behavior for example in the password input field of the Ubisoft client.

Example:

![image](https://user-images.githubusercontent.com/6721083/169470093-40594551-1dc1-46ff-af43-3f41dc31e5f4.png)

Then I get a double parse in the app Notepads:

![image](https://user-images.githubusercontent.com/6721083/169470196-c2f86a72-e936-475b-90ed-202e1de72f23.png)

**Comment by xmichelo** [comment]
Some applications tends to monitor interfere with the keyboard input, and unfortunately there is nothing Beeftext can do about that.

Note: please do not use Beeftext to store passwords. It's not made for that and it's not safer. Use a password manager (Keepass, 1Password, Bitwarden...)

**Comment by makedir** [comment]
No i think it is a bug. When I use the hotkey and then click on the password to let it being inserted, it works fine.

It just wont work properly when used via regex paste.
