### ISSUE TITLE
[Bug] Sistem unable to star in windows 8.1 -0 

### ISSUE THREAD

**Issue by victorolmo** [xmichelo/Beeftext#496]
I've installed the software and it doesn't open. It shows the message that follows.
#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v14.0
#### Operating system version (e.g Windows 10)
Windows 8.1

![image](https://user-images.githubusercontent.com/40234343/171883876-b198d32a-6f03-4fbe-87f9-5561f9897d7c.png)

**Comment by xmichelo** [comment]
Unfortunately, Beeftext now uses qt6 which only support Windows 10 and 11. The last release compatible with Windows 7 is [here](https://github.com/xmichelo/Beeftext/releases/tag/v11.1). I hope it works with 8.1. If it's not the case, there is not much I can do about it.

**Comment by victorolmo** [comment]
Xmichelo, good night. 

The version 13 worked very well and I'm in love with beeftext. Thank you very much.
