### ISSUE TITLE
[Bug] Double line breaks missing when used in MS Teams

### ISSUE THREAD

**Issue by bailsafe** [xmichelo/Beeftext#501]
#### Expected behavior

Beeftext should be processing double line breaks as shown in the editor, with one blank line between lines of text.

#### Actual behavior

When used in Microsoft Teams, it seems to ignore repeated line breaks and only creates a single one. See image.

#### Steps to reproduce the behavior

[![Snipaste-2022-07-13-10-38-12.png](https://i.postimg.cc/wBYK9pjN/Snipaste-2022-07-13-10-38-12.png)](https://postimg.cc/QFmYqv5N)

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).

v14.0

#### Operating system version (e.g Windows 10)

Windows 10 21H1 (19043.1766)

**Comment by xmichelo** [comment]
Hi.

I just tested and confirm the problem, but it's not Beeftext's fault. All Beeftext does is simulating a copy/paste. When pasting, Teams remove the second line break. It does the exact same thing if you copy manually from another text application like Notepad.
