### ISSUE TITLE
Not working in cmd (solved)

### ISSUE THREAD

**Issue by Thefaroah** [xmichelo/Beeftext#505]
Solved 2 issues:
Started Beeftext with administrator privileges. Had been using the option to start at login (no admin privileges).
1. Now it works in cmd.
2. Most importantly, now it works in Chrome!!

--- Original post ---
#### Expected behavior
Should work

#### Actual behavior
Doesn't work

#### Steps to reproduce the behavior
Using a shortcut to a .bat file.
If the shortcut has "Run as administrator" set (Properties>Advanced), Beeftext will not work.
Remove the "Run as administrator", and all is well.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v14.0

#### Operating system version (e.g Windows 10)
Win 10

**Comment by xmichelo** [comment]
Hi. Add `cmd.exe` to the list of sensitive applications (Preferences -> Advanced -> Sensitive Applications). Beeftext uses Ctrl+V to paste the content of the combo, but cmd supports only Shift+Insert for pasting. Or you can changes the settings of the Command Prompt application to accept `Ctrl+V`.
