### ISSUE TITLE
Using #{cursor} is very slow

### ISSUE THREAD

**Issue by janhink** [xmichelo/Beeftext#509]
#### Expected behavior

When using the #{cursor} variable, the pasted text should be pasted (almost) immediately with the cursor set to the correct position.

#### Actual behavior

When using the #{cursor} variable with a combo of about 700 characters, I need to wait about 5s before the cursor moves to the correct position.

I don't know if it's possible here but for example the Text Blaze extension for Chrome does this instantly.

#### Steps to reproduce the behavior

Insert a combo with about 700 characters, something like:

Hi, #{cursor}

and here insert about 700 characters...

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).

Beeftext v14.0 installed

#### Operating system version (e.g Windows 10)

Windows 11

**Comment by xmichelo** [comment]
Unfortunately, there is not much I can do about that. To work universally, Beeftext simulates left arrow key presses to position the cursor. A delay is needed in between keys not to flood the application.

**Comment by janhink** [comment]
Hi @xmichelo, thank you for the fast response.

Could the program maybe determine if it's better to start from the beginning and then use right arrow? And maybe even use ctrl + arrow to jump through words and not letters?

**Comment by xmichelo** [comment]
Unfortunately, I cannot start from the beginning, and Ctrl+arrow is not universally supported.

**Comment by shortyorty** [comment]
How about an up arrow for cases where the snippet includes one or more line breaks && the cursor position is beyond at least one?
