### ISSUE TITLE
[Bug] In Outlook - New Mail - Key or shortcut not working

### ISSUE THREAD

**Issue by Tomiliy** [xmichelo/Beeftext#511]
In Outlook I click on new mail.
Then I am in the window where I can write text.
But I want to jump to the To or CC field (Shift +Tab) x2 or x3
write there the mail address and then with 1 or 2 tabs to subject and forwad with tab to the text field.
But it does not work.
Neither with "Shortcut" nor with "Key:".
Either it does nothing, or it does everything in the text field.

#{key:Umschalt+Tab}
mail@test.de #{key:enter} #{key:down:3}
Test Subject
#{combo:Begr1}

Text....

#{combo:ViDa}

**Comment by xmichelo** [comment]
Unfortunately app, may responds erratically to keys and shortcuts variables. Try to insert some [delays](https://github.com/xmichelo/Beeftext/wiki/Variables#delay) and see if it helps.

**Comment by Tomiliy** [comment]
I already tried. But No Effekt.
I don't understand why.
IT is possible that you try Out, or we made a Screen Session, so i can Show
the Problem.

Thanks

Xavier Michelon ***@***.***> schrieb am Mo. 19. Sept. 2022 um
08:08:
