### ISSUE TITLE
[Feature] generate an Outlook Mail and add a picture to the signature 

### ISSUE THREAD

**Issue by Tomiliy** [xmichelo/Beeftext#512]
there should be a function that opens a new mail in Outlook, directly pre-populated with the variables you defined before.
It would also be good if you could add images to the signature instead of just names.

**Comment by xmichelo** [comment]
Hi.

Beeftext is application agnostic and will remain so.
There used to be support for rich text (formatting, images, ...), but it was not working universally and required a lot of maintenance, so it was removed.

Regards
