### ISSUE TITLE
[Bug] dateTime format with polish locale displays week number instead of "w"

### ISSUE THREAD

**Issue by bstrulak** [xmichelo/Beeftext#514]
When I format dateTime variable to display month name using  #{dateTime:MMMM} with polish locale, instead of displaying "września" (September) it displays "37rześnia". It looks like "w" is replaced with #{dateTime:w}.
The same happens to other month with "w" in the name : kwietnia (April) and czerwca (June).

#### Expected behavior
#{dateTime:w} #{dateTime:MMMM}  --> 37 września
#{dateTime:+7M:w} #{dateTime:+7M:MMMM} --> 15 kwietnia
#{dateTime:+9M:w} #{dateTime:+9M:MMMM} --> 24 czerwca
#### Actual behavior
37 37rześnia
15 k15ietnia
24 czer24ca

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext v14.0 
#### Operating system version (e.g Windows 10)
Windows 11 Pro 21H2 22000.856
polish language

**Comment by bstrulak** [comment]
I found that in `evaluateDateTimeVariable` function after formatting the date function replaces "ww" and "w" into week number.
`result.replace("ww", QString("%1").arg(weekNumber, 2, 10, QChar('0')));`
`return result.replace("w", QString::number(weekNumber));`
I think it should first check if `formatStr == "w" || "ww"`

**Comment by xmichelo** [comment]
Hi.

Thank you for reporting. You're obviously right. I'll fix that and post a build soon.

**Comment by xmichelo** [comment]
Hi. The issue should be fixed. Here are test builds:

- [Beeftext-14.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/9604273/Beeftext-14.0-Installer.zip)
-  [Beeftext-14.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/9604274/Beeftext-14.0-PortableEdition.zip)

**Comment by bstrulak** [comment]
Thank you. 
Works great.
