### ISSUE TITLE
[Bug] Does not work within MS Teams

### ISSUE THREAD

**Issue by rgkey9000** [xmichelo/Beeftext#518]
#### Expected behavior
Works within MS Teams as everywhere else 

#### Actual behavior
Does not do anything

#### Steps to reproduce the behavior
try using the picker or the text replacer in a chat-window within the Teams.exe application

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext installed 14
#### Operating system version (e.g Windows 10)
Windows 10 19044.2006

**Comment by xmichelo** [comment]
Hi. Beeftext does not apply any specific treatment to Teams. You should address your request to Microsoft.
