### ISSUE TITLE
[Bug] duplicates replacement in Teams Web chat window

### ISSUE THREAD

**Issue by rgkey9000** [xmichelo/Beeftext#519]
#### Expected behavior
Just fills in text replacement once

#### Actual behavior
Fills in text replacement twice (after eachother in serial)

#### Steps to reproduce the behavior
Normal text replacement method in a chat window within: https://teams.microsoft.com/

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
Beeftext 14 Installed
#### Operating system version (e.g Windows 10)
Windows 10 19044.2006

**Comment by xmichelo** [comment]
See #518 518
