### ISSUE TITLE
Input Box close when clicking on other software

### ISSUE THREAD

**Issue by Funkystrings** [xmichelo/Beeftext#521]
#### Expected behavior
The input Box should stay open when clicking elsewhere 

#### Actual behavior
The inpu box close as soon as we click somewhere else

#### Steps to reproduce the behavior
Start a combo with input box and click elsewhere

**Comment by xmichelo** [comment]
Hi. This is not a bug. Beeftext relies on the fact that the application it was called from is the one that will become active again we the input box closes. If you can click elsewhere, this does not work anymore, that's why beeftext closes the input box automatically.
