### ISSUE TITLE
Windows Defender detects a virus

### ISSUE THREAD

**Issue by onsamyj** [xmichelo/Beeftext#526]
In `Beeftext-15.0-PortableEdition.zip`, Windows 11 detects a virus:

> Detected: Trojan:Script/Wacatac.H!ml
> Status: Quarantined
> Quarantined files are in a restricted area where they can't harm your device. They will be removed automatically.
> Date: 17/11/2022 13:22
> Details: This program is dangerous and executes commands from an attacker.

[VirusTotal gives all clear](https://www.virustotal.com/gui/url/d06a3ef10bcaf5224b8975b19a799da81e5836f2ec7c9fb0793784667b160da8?nocache=1), so it is a false detection, I guess. Seems like Windows Defender makes a lot of false positives recently, so consider it as a warning of that, not a bug of Beeftext.
#### Beeftext version

15 Portable

#### Operating system version

Windows 11 21H2

**Comment by onsamyj** [comment]
Seems like Windows Defender makes a lot of false positives recently, so consider it as a warning of that, not a bug of Beeftext.

**Comment by xmichelo** [comment]
This is unfortunately a frequent problem with new releases of Beeftext. 
See https://github.com/xmichelo/Beeftext/wiki/Beeftext-is-safe
