### ISSUE TITLE
[Bug]  Snippet not filled into "Open document"-path field of Qt-Application

### ISSUE THREAD

**Issue by LeFish1** [xmichelo/Beeftext#532]
#### Expected behavior

When the keyword is recognized and the content of the path field in an "Open document"-dialog or "Save document"-dialog is marked the snippet should be filled in.

[Screenshot of "Backup" dialog within Beeftext](https://i.paste.pics/193247f79f50fbbaae8d823f711e69cf.png) <Keyword> is replaced by my keyword (i.e. ^^ldo)
[Screenshot of "Open document" dialog of FreeCAD](https://i.paste.pics/e98f585f7e0611e35c617738e5d18deb.png)

FreeCAD: [https://github.com/FreeCAD](url)

Used libraries of FreeCAD include Qt 5.15.2.

If the keyword is filled in another "Open document"-dialog (i.e. MS Word) the snippet is filled in just fine.

#### Actual behavior

The Beeftext-Combo-sound is not played and the snippet is not filled in.

#### Steps to reproduce the behavior

FreeCAD (0.20.1). Choose the "Open document"-Dialog. Mark the path field. Type in keyword.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).

Beeftext v.15 (installed on System)

#### Operating system version (e.g Windows 10)

Windows 10.0.19045

**Comment by xmichelo** [comment]
Hi.
You should submit the issue to the FreeCAD developers. See https://github.com/xmichelo/Beeftext/wiki/Beefext-does-not-work-in--%22insertApplicationName%22.

**Comment by LeFish1** [comment]
Hello @xmichelo,

have you tried typing in a keyword within the Beeftext Back Up dialog? It is the same behavior there on my system (not replacing the keyword).

Could this be a Beeftext/Qt issue?

**Comment by xmichelo** [comment]
No, this is expected. Combo substitution is disabled if the active application is Beeftext itself, because otherwise it can be difficult to edit combos.

**Comment by LeFish1** [comment]
I tried again today and "magically" it is working now. I don't know - maybe a system reboot got things going.

I could not say that anything changed (no updates or anything)

Probably a mistake on my side...

Sorry about that!
