### ISSUE TITLE
[Feature] Multiple keywords, same snippet

### ISSUE THREAD

**Issue by elle8che** [xmichelo/Beeftext#535]
Please forgive if this has been mentioned before. A search for "keyword" results in many many posts.

Is it possible to allow multiple keywords to be assigned to a snippet? 

As a simple example, keywords "twodays" and "2days" would both apply to the same snippet. "2days" would be an alternate keyword for the same snippet. 

Side note: Amazon has recently changed Alexa routines to allow us to specify multiple key phrases to trigger actions, so now I can say "Alexa, morning" and "Alexa, good morning" and she'll complete the routine. Helps tremendously, as it's easy to forget all the things that are supposed to help us be efficient!

**Comment by xmichelo** [comment]
Snippets can only have one keyword, but you can create a second snippet that references the first one to get a second keyword, using the [#{combo}](https://github.com/xmichelo/Beeftext/wiki/Variables#combo) variable.
Snippet 1:
  - keyword: `2days`
  - snippet: `The text you want`

Snippet 2:
  - keyword: `twodays`
  - snippet: `#{combo:2days}`
