### ISSUE TITLE
soft enter instead of enter

### ISSUE THREAD

**Issue by poho19** [xmichelo/Beeftext#537]
Hi,
I have this text in snippet:
1 line
2 line
3 line
name as "eennter"
When I enable Nonprinting Characters (ctrl+F10) and use "eennter" in OpenOffice Writer or LibreOffice Writer I can see soft enter after first two lines.
Is it possible to have a normal enter used throughout the text?

**Comment by xmichelo** [comment]
Hi. Thank you for reporting. You're right, Beeftext paste text with LF line ending instead of CR/LF which is the standard used by Windows. I will fix that.

**Comment by peter-fb** [comment]
Hi. I use Windows, but configure all my text editors (Notepad++, VS Code etc.) to use LF line endings (which is a very common configuration for these source code editors). Will this bug fix change something in my use case?

**Comment by xmichelo** [comment]
Beeftext uses 'copy/paste' to insert snippets. If your editor supports LF line ending, it must takes care of converting CR/LF to LF when text is pasted, so you should not have problems.

Here are test build files if you want to check.
[Beeftext-15.0-Installer.zip](https://github.com/xmichelo/Beeftext/files/10256357/Beeftext-15.0-Installer.zip)
[Beeftext-15.0-PortableEdition.zip](https://github.com/xmichelo/Beeftext/files/10256358/Beeftext-15.0-PortableEdition.zip)

**Comment by peter-fb** [comment]
Hi Xavier, I tested Beeftext-15.0-PortableEdition.zip in Notepad++ and VS Code and this build seems to work fine if these editors are set to use LF line endings, so thank you for that.
