### ISSUE TITLE
Is there a generic snippet list[Feature] 

### ISSUE THREAD

**Issue by decard123** [xmichelo/Beeftext#539]
**Is your feature request related to a problem? Please describe.**
is there a generic snippet list somewhere?
and i means as a text or CSV file; not a HTML article that just list sll the possible options

**Describe the solution you'd like**
a generic snippet list as TXT or CSV file to add to

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by xmichelo** [comment]
There is not such list for now. It may happen in the future.

**Comment by decard123** [comment]
i thought i would work on one.
