### ISSUE TITLE
Not running, getting error message

### ISSUE THREAD

**Issue by harryray33** [xmichelo/Beeftext#544]
#### Actual behavior
I'm getting an error message 'the procedure entry point createDXGIFactory2 could not be located in the dynamic link library'
#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
V15 installed
#### Operating system version (e.g Windows 10)
Windows 7

**Comment by xmichelo** [comment]
Hi. Beeftext requires Windows 10. You can find older version that can run on Windows 7 [here](https://github.com/xmichelo/Beeftext/wiki/Older-versions).
