### ISSUE TITLE
[Feature] Context aware text substitution 

### ISSUE THREAD

**Issue by lennon101** [xmichelo/Beeftext#546]
**Is your feature request related to a problem? Please describe.**
I have a text substitution that has the following rules: 

- keyword: https
- snippet: https:// 

This works great except when using chrome and attempting to use it while the cursor is in the url field of the Chrome Browser. Chrome seems to inserting an extra "h" after the snippet is inserted so the result is: hhttps:// 
I don't believe this is a bug in Beeftext because the behaviour is only present in the Chrome Browser. 

- Chrome OS Version 108.0.5359.125 (Official Build) (64-bit)
- Windows 10 Pro OS Build 19044.2364
- Beeftext version: V15.0

**Describe the solution you'd like**
I think possibly a solution to this might be some sort of context aware feature where BeefText detects when the cursor is being used in the Chrome Browser and have BeefText not insert the leading character. OR maybe have beeftext do a post-text-insertion analysis to detect any issues? 

**Describe alternatives you've considered**
N/A

**Additional context**
Happy to provide any other help/advice if needed. I think the app is great otherwise. Very neat and tidy! Great job!

**Comment by xmichelo** [comment]
I'm not willing to introduce app or context specific behaviour in Beeftext. If Chrome behaves poorly, Google should fix it.
