### ISSUE TITLE
[Feature] shortcut to pause/unpause

### ISSUE THREAD

**Issue by C0deGyver** [xmichelo/Beeftext#547]
Before I say anything. I LOVE this software. It has and I am sure will continue to save me time.

It would be nice to have a shortcut key to pause and unpause BeefText. Ideally, the shortcut could be changed or set up by the user.

**Comment by xmichelo** [comment]
Hi.
There's one, but it's disabled by default. You can enable it and change it in the `Behavior` tab of the preferences. Just check the `Use shortcut to enable/disable Beeftext`.
