### ISSUE TITLE
Doesn't seem to work in Twitter (which seems odd)

### ISSUE THREAD

**Issue by decard123** [xmichelo/Beeftext#549]
Doesn't seem to work in Twitter (which seems odd)

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
v15
#### Operating system version (e.g Windows 10)
Win10/FF

**Comment by xmichelo** [comment]
Hi. There is no special treatment applied to twitter. It probably your browser, an add-on, or anti-virus/web protection.

See [this wiki page](https://github.com/xmichelo/Beeftext/wiki/Beefext-does-not-work-in--%22insertApplicationName%22).
