### ISSUE TITLE
[Bug] wrong version listed in help

### ISSUE THREAD

**Issue by JoyWorksToo** [xmichelo/Beeftext#551]
**#### Expected behavior**
When I click Help and about, I expect to see v16.0

**#### Actual behavior**
It still says v14.0 

**#### Steps to reproduce the behavior**
Switched from portable to installed version and it still comes up as 14
I figured maybe 1 file got missed but I installed in new dir and just as version 15 did for me it still says 14
it also didn't need me to restore my backup it grabbed my current snippets

**#### Beeftext version**
Installed and Portable Edition Beeftext v16.0 
"C:\Program Files\Beeftext\Beeftext.exe" 
Details of file say 16 last modified 31-DEC

**#### Operating system version** 
Windows 10

![image](https://user-images.githubusercontent.com/29585770/210414837-e5f221c0-28d1-4881-b0cf-b9ef2b15971b.png)

**Comment by xmichelo** [comment]
Hi.

This is extremely strange... I checked both the installer and portable versions from the download link, and both report 16.0 in the About dialog.

Is there a chance the version that is running is auto-started and is actually located somewhere else? 

You can check that when Beeftext is running: 
- Open  the Task Manager (Ctrl+Shift+Esc)
- Right Click on Beeftext in the list ➜ Properties
- in the General tab, check the value for 'Location'.

**Comment by JoyWorksToo** [comment]
Well don't I feel smart 
Thank You
