### ISSUE TITLE
Feature Request: — Password Protection on GUI — and/or — Hidden Combos e.g. ********

### ISSUE THREAD

**Issue by rolltidehero** [xmichelo/Beeftext#555]
This would be a cool feature for those of us that have addresses, phone numbers, etc. as combos.

Obviously, they could still view the data from the JSON and backups if they knew what they were doing, but most people don't know what they are doing 😂

I could have swore that this was already a feature but I guess not.

Regardless, BeefText kicks ass! Thanks for the awesome app!

**Comment by xmichelo** [comment]
You seem to be aware of be it, but please, do not store sensitive information in Beeftext. Use a password manager (1Password, Bitwarden, Keepass...). I do want want to implement a feature that will encourage a potentially dangerous behavior.
