### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by JamesTheGray** [xmichelo/Beeftext#560]
#### Expected behavior

Beeftext used to enter text in Sharepoint Form fields, worked on Friday, now does not work in Edge or Chrome

#### Actual behavior

Text seems to be generated (sound effect is heard) but is not displayed in field. Can generate text in notepad and paste into field with no issues.

#### Steps to reproduce the behavior

Open Sharepoint Online List form with rich text field, place cursor in field, try to generate text

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
V13.0 Portable or  V16.0 installed, neither have expected behavior.

#### Operating system version (e.g Windows 10)
Windows 10

**Comment by xmichelo** [comment]
Hi. I guess a patch from MS caused a change in the way clipboard is handled. Unfortunately there is not much I can do :( . 
https://github.com/xmichelo/Beeftext/wiki/Beefext-does-not-work-in--%22insertApplicationName%22
