### ISSUE TITLE
[Working on Emulator BlueStacks / LDplayer] 

### ISSUE THREAD

**Issue by Go2v** [xmichelo/Beeftext#561]
Hello, thank you again for this wonderful software you have produced, I love it.
I'm frustrated because I can't use the text with emojis on Emulator like BlueStacks or LDPlayer (it'w working on Nox idk why)

I tried to use the sensitive application mode. When I do that the text is replaced but the emojis are transformed into "????"

I let you see for yourself :

<img width="409" alt="image" src="https://user-images.githubusercontent.com/63112880/217940405-2146814c-7837-44ae-9760-9bed309d378f.png">

<img width="240" alt="image" src="https://user-images.githubusercontent.com/63112880/217941033-15578011-b97f-49e1-895e-7f9ee8983612.png">

**Comment by xmichelo** [comment]
Unfortunately, there is not much I can do from the Beeftext side. Sensitive application mode works by typing keys one-by-one, and it will not work with emojis.
