### ISSUE TITLE
[Bug] Powershell scripts do not works in beeftext

### ISSUE THREAD

**Issue by userQAY** [xmichelo/Beeftext#562]
#### Expected behavior
powershell script works as described

#### Actual behavior
example snippet and script: 

Hello #{powershell:C:\Temp\script.ps1}!
Write-Host -NoNewLine ([System.Environment]::UserName)   -   works fine in powershell
but do not work in beeftext. It only return string "Hello !"

second script - for beeftext version -  works the same way.

Doing I something wrong? 
Thanks for Help.

#### Beeftext version (e.g. Beeftext v7.0 Portable Edition).
16.
#### Operating system version (e.g Windows 10)
win 10 22H2   |  build 19045.2486

**Comment by xmichelo** [comment]
Hi.
 
Can you please try again, then see if there is an error message in the log file (Advanced ➜ Open Log File) in the main menu.

**Comment by userQAY** [comment]
LOG:   2023-02-19 21:44:50.979 - WARNING - Evaluation of #{powershell:} variable failed: execution of `d:\Utility\BeeftextPortableEdition\scripts\script.ps1`
