### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MohammedHoosen** [xmichelo/Beeftext#563]
#### Expected behavior
Open without any errors.

#### Actual behavior
Error when running the application: 
Beeftext.exe - Entry Point Not Found
The Procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll

#### Steps to reproduce the behavior
Either install the application or open the portable version and the error pops up.

**Comment by xmichelo** [comment]
Hi.
Beeftext requires Windows 10 or 11 (it's a requirement for Qt, upon which Beeftext is built). It seems you are using Windows 7 or 8. You can find older version of Beeftext that will be compatible [in this page](https://github.com/xmichelo/Beeftext/wiki/Older-versions).
