### ISSUE TITLE
Spell Checking and Rich Text Formats

### ISSUE THREAD

**Issue by makdaddy8888** [xmichelo/Beeftext#568]
Fantastic product can I please make 2 suggestions?
Spell Check based on Locale
Simple Rich Text Editing like Bold, Italics and Underline

**Comment by xmichelo** [comment]
Hi.  Thank you for the suggestions.
- Spell Check is courtesy of your operating system. Beeftext does not include one.
_ Rich text was supported at some point, but it was not working properly everywhere, and was taking way too much time to maintain, so the feature was removed.
