### ISSUE TITLE
[Feature] OpenAI API Integration : Chat Endpoint

### ISSUE THREAD

**Issue by OLH21** [xmichelo/Beeftext#578]
Blaze is typical a saas version of beeftext , and they just introduced a connection with OpenAi GPT API

(https://dashboard.blaze.today/packs/0vJtXxohFCmRX1Jc6Ru6)

That open so many use case in automation and completion... like 
https://blaze.today/gallery/gpt/chatgpt-summarize/

Especially if it could be used with the {CLIPBOARD} to send clip board content
they use  to the completion end point and i think chat endpoint would be better especially if you expose the system prompt that allow very precise control of the GPT output

Text completion automation could be very very simplifyed by such an integration
API use is very straight forward and the possibilities are endless

**Comment by xmichelo** [comment]
Beeftext is made with privacy in mind. As such, it will never use any external API, and it will not feed any LLM / ML model.
