### ISSUE TITLE
Not replacing text in Windows Explorer file upload window

### ISSUE THREAD

**Issue by viktorix** [xmichelo/Beeftext#64]
### Expected behavior
Typing in a keyword will replace text.

### Actual behavior
Nothing happens.

### Steps to reproduce the behavior
Text replacement works inside Windows Explorer, this is specific to file upload window. When you need to upload files on a website, you click a button like "Select a File" and Windows Explorer window comes up where you find and upload a file. Text replacement does not work in the folder path field and file name field. 

See screenshot.
![02d6db7e-15c0-4d29-9678-c0299213ab22](https://user-images.githubusercontent.com/1692600/38523271-f4af787c-3c18-11e8-93b8-37e6c050abe0.png)

### Operating system
Windows 10

**Comment by xmichelo** [comment]
As for issue #63, Beeftext works fine for me in the Windows file upload dialog in Chrome.

I would apply the same recommendations as for issue #63.

I'm keeping the issue open for now, but I may merge it later.
