### ISSUE TITLE
Remove tabbed interface.

### ISSUE THREAD

**Issue by xmichelo** [xmichelo/Beeftext#65]
The tabbed interface should be replaced. The main window should contain only the combo list. The Preferences and About frames should be moved into modal dialog.

**Comment by smaragdus** [comment]
Tabbed interface is fast- switching from Combos to Preferences is just one click away.

**Comment by xmichelo** [comment]
Now Preferences will be one keyboard shortcut away. Or two clicks.

Additionally, having a modal dialog allows to defer and potentially undo you latest preferences changes via the 'Cancel' button.
