### ISSUE TITLE
Allow saving the file with combos in a custom location

### ISSUE THREAD

**Issue by harireghu** [xmichelo/Beeftext#82]
This is a request for enhancement - not a bug.

I would like to save the combos in my dropbox so that it is not lost.
It would be helpful if there is an option to specify the location of the comboList.json.

I'm using Beeftext-1.4-PortableEdition.zip downloaded from https://beeftext.org/
I would like this option in the installed version too.

**Comment by xmichelo** [comment]
Hi.

This feature already exists, but it is not available in the *Portable Edition*, where all configuration files must be located in the application folder.

If you use the installer based version of Beeftext, you can change the location of the combo list file by going to `File ➜ Preferences ➜ Advanced ➜ Combo list folder`

**Comment by harireghu** [comment]
Thanks @xmichelo -   I installed the installer based version and I am able to change the location.
