### ISSUE TITLE
When a new combo is created by Duplicating an existing combo, it is not saved in comboList.json

### ISSUE THREAD

**Issue by harireghu** [xmichelo/Beeftext#83]
### Expected behavior
Combos are saved when a duplicated combo is saved.

### Actual behavior
Combos are not saved when a duplicated combo is saved.

### Steps to reproduce the behavior
1. Download and unzip portable edition. Start the app.
2. Create a group and then create a combo (let's call it comboA ) in that group
Observation : The comboList.json is created and the created group and combo are seen.

3. Create a new combo ( let's call it comboB ) by dulicating the combo created in step2.
Observation : The comboList.json is not updated and the contents are the same as after step 2.
comboB is not saved.

4. Exit the app
Observation : The comboList.json is not updated and the contents are the same as after step 2.
comboB is not saved.

5. Open the app again and repeat step 3. Create another combo (Let's call it comboC ) from scratch.
Observation : The comboList.json is updated with both comboB and comboC.

It looks like the duplicate operation does not trigger a save.

### Operating system
Windows 10 Pro.

I'm using Beeftext-1.4-PortableEdition.zip downloaded from https://beeftext.org/

**Comment by xmichelo** [comment]
Hi @harireghu 
Thanks for your report. I managed to reproduce the issue, it affects all versions of the application. A fix coming soon.

**Comment by xmichelo** [comment]
@harireghu,

The fix was straightforward. If you are willing to test, here is a test build (commit a104e57) that fixes the issue (and issue #84 too):
- [Installer](https://owncloud.x-mi.com/index.php/s/UK7dMDF1kjXfhcV/download)
- [Portable Edition](https://owncloud.x-mi.com/index.php/s/YIAtLDfkD87xyhM/download)

I'll test too, and will publish an official v1.5 at the end of the week.

**Comment by harireghu** [comment]
Thanks @xmichelo for the quick fix!

This issue and the #84 seem to be fixed in the test build ( I used the portable edition )
