### ISSUE TITLE
unable to cut/copy in snippet

### ISSUE THREAD

**Issue by leschek** [xmichelo/Beeftext#86]
### Expected behaviour

Let's say that I want to create a new combo with the help of some previously created combo. I'm able to  duplicate the old combo, edit its name and keyword, but I'm not able to copy or cut any part of snippet and paste that part somewhere else. If I highlight a part of snippet and right click on it, it opens menu, but copy and cut commands are grey. I'm able to use windows shortcuts "ctrl + c" or "ctrl + x" and "ctrl + v", but not commands in right click menu.

The same thing happens when I try to edit snippet.
 
### Operating system

Windows 8.1 and 10, Beeftext 1.5 portable

**Comment by xmichelo** [comment]
Hi @leschek. 
Thank you for reporting the problem. I confirm that I could reproduce this issue.
