### ISSUE TITLE
Beeftext modifies snippet due to line breaks

### ISSUE THREAD

**Issue by viktorix** [xmichelo/Beeftext#92]
### Expected behavior
The snippet should be 100% accurate, without any modifications.

### Actual behavior
Something weird is happening with .htaccess rewrites when they are entered as snippets.

Here's what the combo looks like:
https://share.projectarmy.net/f7d1643d-3305-40b5-9365-3720f12e5db6

And here's what it looks like when the keyword is replaced:
https://share.projectarmy.net/c10db7a4-244e-424c-a45a-60d10fe76709

### Steps to reproduce the behavior
Here's json of the combo, looking at it, I think \n breaks are combined with previous characters.

```
{
    "combos": [
        {
            "creationDateTime": "2018-07-08T13:28:39.424",
            "enabled": true,
            "keyword": "`wpht",
            "modificationDateTime": "2018-07-08T13:29:19.447",
            "name": "WordPress htaccess",
            "snippet": "# BEGIN WordPress\n<IfModule mod_rewrite.c>\nRewriteEngine On\nRewriteBase /\nRewriteRule ^index\\.php$ - [L]\nRewriteCond %{REQUEST_FILENAME} !-f\nRewriteCond %{REQUEST_FILENAME} !-d\nRewriteRule . /index.php [L]\n</IfModule>\n# END WordPress",
            "useLooseMatch": false,
            "uuid": "{b968cceb-9ed8-43b4-903d-a046d6aa82c2}"
        }
    ],
    "fileFormatVersion": 4,
    "groups": [
    ]
}
```
Might need a better way of escaping certain characters or different line breaks.

### Operating system
Windows 10

**Comment by xmichelo** [comment]
No reply. Closing.
