### ISSUE TITLE
Disabled combos are still working

### ISSUE THREAD

**Issue by byungjikroh** [xmichelo/Beeftext#93]
### Expected behavior
Disabled combos are expected not to work until enabling them again.

### Actual behavior
Disabled combos are still working and replaced or extended with their snippets.

### Steps to reproduce the behavior
1) Add a new combo 
2) Disable the combo 
3) Type the combo's keyword
4) Keyword is replaced with the snippet

### Operating system
Windows 10

**Comment by xmichelo** [comment]
Hi @byungjikroh 

Thank you for reporting the issue. I could reproduce it and it will be fixed in the next release.
