### ISSUE TITLE
Upon elevated installation, application should be started with the logged in user account

### ISSUE THREAD

**Issue by TerDale** [xmichelo/Beeftext#98]
Hi @xmichelo,

### Expected behavior
1. when installing Beeftext, if the currently logged in user does not have administrator privileges, the setup will request a privilege elevation asking for an administrator account, so far so good...
2. at the end of the setup, one has the possibility to start the just installed application,
3. if this is accepted, the application is started using the administrator account

### Actual behavior
In step 3, the application should be started with the logged in user account

### Steps to reproduce the behavior
Install Beeftext while the currently logged in user is not an administrator

### Operating system
W7

Thanks in advance!

**Comment by xmichelo** [comment]
Hi, @TerDale 

You're right. Beeftext uses [NSIS](http://nsis.sourceforge.net/Main_Page) for its installer. There is a [UAC plugin](http://nsis.sourceforge.net/UAC_plug-in) that could fix the problem, but it is considered beta and has not been updated in 3 years, so it would require quite a lot of testing.

I want to evaluate alternative installer technologies, so I will take time to investigate various approaches.

**Comment by TerDale** [comment]
Salut Xavier,
OK, thanks for taking this issue into account.
However, I should have stated that it is low priority FMPOV, as once Beeftext is exited, one will run it again with its least privilege user account.
